### ISSUE TITLE
drag and drop with nested plugins and the property 'CellPlugin.cellPlugins'

### ISSUE THREAD

**Issue by ibaasch-evorhei** [react-page/react-page#1000]
**Describe the bug**

there are two bugs when using nested plugins and the property `CellPlugin.cellPlugins`:
- changes of plugin order or position are not possible anymore in nested plugins
- dragging and dropping a nested plugin outside its parent plugin on the same nesting level (the level of the Editor) is still possible though it is not allowed there

- see details below
- tested on v2.2.7 online on https://react-page.github.io/examples/nestedPlugins
- bugs existing probably since v2.1.0 (introduction of property `CellPlugin.cellPlugins`)

**To Reproduce**

- goto https://react-page.github.io/examples/nestedPlugins

- click on Add button

- insert the plugin `deeplyNestedA` (title: 'Some plugin A with needply nested child plugins').
  (there is a typo in the title: is: '...needply nested..' should: '...deeply nested...')

- click add button of plugin `deeplyNestedA`

- Add plugin `deeplyNestedB` 3 times (title: 'Some plugin B with nested child plugins').

=> error a) changes of plugin order or position of `deeplyNestedB` by drag and drop are not possible anymore

=> error b) dragging and dropping a plugin (`deeplyNestedB`) to the border of `deeplyNestedA` and thus placing it next to the plugin `deeplyNestedA` on the same nesting level (the level of the Editor) is still possible (with exception thrown). This happens only if the corner area of `deeplyNestedA` is used as drop target

**Expected behavior**

a) changes of plugin order or position of `deeplyNestedB` by drag and drop should be possible

b) dragging and dropping a plugin (`deeplyNestedB`) to the border of `deeplyNestedA` should not be possible

**Comment by macrozone** [comment]
@ibaasch-evorhei looking into this now

**Comment by macrozone** [comment]
@ibaasch-evorhei i fixed it! Can you verify? (will be v2.2.13 or above i guess, its currently being baked)

**Comment by ibaasch-evorhei** [comment]
@macrozone Version 2.2.13 works as expected. The issue has been fixed successfully. 
Thank you, Marco!
