### ISSUE TITLE
Decorate plugin example is now broken

### ISSUE THREAD

**Issue by zehawki** [react-page/react-page#1003]
**Describe the bug**
Error when opening styling tab of any cell plugin

**To Reproduce**
1. Go to https://react-page.github.io/examples/decorateplugins
2. Click on any block
3. Click on styling tab
4. See error: this._compiledSchema[e] is undefined

**Expected behavior**
Styling tab should display

**Screenshots**

![image](https://user-images.githubusercontent.com/8095144/118620382-1607c800-b7e3-11eb-9959-16ebd7d94ff8.png)

**Additional context**
This is a regression. Was working just fine earlier, and working fine on my side on v2.1.4

**Comment by zehawki** [comment]
Actually, this may be on many of the examples. See https://react-page.github.io/examples/multicontrols as well. Same issue.

**Comment by dan89farhan** [comment]
@zehawki it is probably because of the uniform library update. 
Even I have raised the issue to solve it on priority.
Link for the issue: #996

**Comment by macrozone** [comment]
looking into this now. this is indeed a change in uniforms

**Comment by macrozone** [comment]
works again!
