### ISSUE TITLE
Strange DnD error on ColorPicker

### ISSUE THREAD

**Issue by zehawki** [react-page/react-page#1004]
**Describe the bug**
When dragging from color picker and dropping outside, the page crashes. Any color picker on any cellPlugin shows this behavior.

![image](https://user-images.githubusercontent.com/8095144/118682823-694b3c00-b81e-11eb-981a-2dd693dece42.png)

**To Reproduce**
Best to see the video: https://user-images.githubusercontent.com/8095144/118682299-f2ae3e80-b81d-11eb-9800-601acc7ad12a.mp4

**Expected behavior**
Maybe not crash? :-)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser: any

**Additional context**
I'm not even sure where and how to start debugging this. Any pointers appreciated. Has anyone else seen this?

**Comment by macrozone** [comment]
@zehawki wow, thats a fun one. i'll check if i can fix it

**Comment by macrozone** [comment]
@zehawki cannot reproduce it locally, but i guarded the line that crashes
