### ISSUE TITLE
plugin type detection

### ISSUE THREAD

**Issue by gevhambarzumyan93** [react-page/react-page#1005]
I have an issue whid some custom plugin. they must be unique, so I decided to collect a map of the type of the plugin that I use, BUT because I can't know which plugin the user use, I mast loop over the whole data to get them.

so now I think maybe it won't be hard to make isUnique param which will set hideInMenu to true after use, or in onChange will be the second parameter with the used plugin

**Comment by macrozone** [comment]
@gevhambarzumyan93 can you elaborate the use case? I don't really understand it.

plugin ids need to be unique, that is true.

**Comment by gevhambarzumyan93** [comment]
@macrozone for example.  I want to give my users opportunity to create their page using my widgets( plugins ), but they can use every plugin just 1 time. so I need option to detect used plugins ids or names
