### ISSUE TITLE
onRemove event listener

### ISSUE THREAD

**Issue by gevhambarzumyan93** [react-page/react-page#1007]
I want to detect if the user deletes ( click on trash button ) the plugin, I cant use onChange event because it returns new data not charged one.

why it's useful 
for example, I want to update some inner state (in my case I want to update the used plugins map) after my plugin is deleted.

**Comment by macrozone** [comment]
some hooks/event listeners would definitly be nice.

we could theoretically read actions in redux, but i consider redux to be an implementation detail that could get removed any time.

I guess it could look like this:

```

<Editor onRemoveCell={yourEventListener} />

```

it would receive the current Cell object as argument. There you get the pluginId that was removed

**Comment by oleksiisurnin** [comment]
Hello @macrozone ,

I've been trying to implement a feature to detect when a user deletes a plugin in react-page. However, the suggested approach using <Editor onRemoveCell={yourEventListener} /> doesn't seem to work. It appears that this event listener is not supported or requires a different implementation. Can you please provide guidance on how to properly detect the removal of a cell or plugin in react-page? Any insights or alternative solutions would be greatly appreciated.

Thank you!
