### ISSUE TITLE
PluginDrawer functionality is broken

### ISSUE THREAD

**Issue by avoskresensky** [react-page/react-page#1008]
**Describe the bug**
PluginDrawer functionality was recently broken. It looks like it happened in this commit:
067b464963229343bc50ee7309ac5c0e97ee895a

After the aforementioned change focusing the newly inserted plugin is an opt-in behavior and it needs to be added to PluginDrawer.

**To Reproduce**
1. Open PluginDrawer
2. Click any plugin
3. The plugin is added, but the drawer is not closed and the plugin is not being focused (bug number one)
4. Drag and drop any plugin
5. The editor switches to the layout mode, plugin is added, no focus, no switching to the edit mode (bug number two)

**Expected behavior**
In both cases the editor should switch to the edit mode and the newly inserted plugin should get focused

The first problem is easy to fix by modifying components/hooks/nodeActions.ts:
```
dispatch(
        action({
          cellPlugins,
          lang,
          focusAfter: true, // add this
        })(partialCell, { id: parentCellId })
      );
```

Not sure if the second problem is fixable just as easy though.

**Comment by macrozone** [comment]
i am also confused by this change. I fixed it for clicking on it, but it still seems to be broken for draging: https://github.com/react-page/react-page/issues/1012

@PeterKottas it seems you just fixed it for some niche use case, but broke it for the general use case. I think we need to have more tests to avoid breaking like this

**Comment by macrozone** [comment]
@avoskresensky fixed in master (will be released soon).

**Comment by avoskresensky** [comment]
@macrozone , thanks a lot!

**Comment by PeterKottas** [comment]
@macrozone yeah some tests around this would be good.
