### ISSUE TITLE
Ability to modify controls 

### ISSUE THREAD

**Issue by hb90dev** [react-page/react-page#1009]
**Is your feature request related to a problem? Please describe.**
It will be good to change styles of controls.

**Describe the solution you'd like**
Editor can receive props as components for modifying specific controls, or modifying only styles.

**Comment by macrozone** [comment]
@hb90dev which controls do you have in mind?

**Comment by hb90dev** [comment]
Controls from right side.( view / edit mode, add plugin, etc... )
