### ISSUE TITLE
How to add figcaption in @react-page/plugins-image 

### ISSUE THREAD

**Issue by thang148** [react-page/react-page#1016]
Help me please!
![image](https://user-images.githubusercontent.com/46104430/120263950-f4204200-c2c6-11eb-9a8e-44e6b076d8eb.png)

how to add figcaption in @react-page/plugins-image

**Comment by zehawki** [comment]
@thang148 if its not something that you are particularly precise about, you can achieve what you need by just putting a textbox below an image. Does that work?
