### ISSUE TITLE
Custom CellPlugins with inputs

### ISSUE THREAD

**Issue by Max0nyshchenko** [react-page/react-page#1022]
Let's consider a situation when I want to have a plugin with input type checkboxes. So I'd expect in readOnly mode to be possible of modifying those checkboxes, checking them. But it's not possible. Is there a way to implement this behavior?

**Comment by macrozone** [comment]
@Max0nyshchenko what is the exact use case? I don't really understand your question.

**Comment by Max0nyshchenko** [comment]
I wrote cutstom plugin where added checkboxes input, and I want for other users to be able to check/modify them in readOnly mode, but its not possible, content is not editable in readOnly mode.

Is it possible to make input fields editable (like textarea, input tags) but restict user from editing all other the content of the page?

**Comment by macrozone** [comment]
@Max0nyshchenko i still don't get your precise use case. 
Why would users in edit mode require to check checkboxes. What do they select exactly? Do these users modify the content or is it just some kind of interactive component?

You can use any component. So you can also mount a form or something like that. But i can't really help as its still unclear what you try to achieve
