### ISSUE TITLE
Exporting to HTML doesn't seem to work

### ISSUE THREAD

**Issue by yuneszadi** [react-page/react-page#1024]
Hi,

Following [this issue](https://github.com/react-page/react-page/issues/741) I tried to export the content of editor to HTML format. But every time I get an empty div `<div class="ory-row"></div>`. How can this problem be solved?

Thanks.

```
import React from 'react';
import Editor from '@react-page/editor';
import PageLayout from './PageLayout';
import image from '@react-page/plugins-image';
import slate from '@react-page/plugins-slate';
import { HTMLRenderer } from '@react-page/renderer';
import ReactDOMServer from 'react-dom/server';

const cellPlugins = [slate(), image];

class Page extends React.Component {
  ...
  onChange = (value) => {
    this.setState({
      value: value
    });
    const html = ReactDOMServer.renderToString(<HTMLRenderer state={value} plugins={cellPlugins} />)
  }

  render = () => {
    return (
      <div>
        <Editor
          value={this.state.content}
          onChange={this.onChange}
          cellPlugins={cellPlugins}
        />
      </div>
    )
  }
}
```

**Comment by macrozone** [comment]
@yuneszadi the `@react-page/renderer` no longer exist. You can use `<Editor readOnly value={value} cellPlugins={cellPlugins} />` to mount the component without editor ui. This also works on the server.

I am a bit irritated by your example as you use `ReactDOMServer` on the client, i am not aware that this works.

If you want to export an html string on the browser, you can simply use the dom api:

```

const ref = useRef()

const onClick= () => {
   alert(ref.current?.innerHTML)
}

return <div ref={ref}>
  <Editor .... />
</div>

```

But i am unsure what you try to achieve with that.

**Comment by mikeljoe1** [comment]
@macrozone  
return <div ref={ref}>
  <Editor .... />
</div>
Using the above approach it exports the HTML of Editor as well, what if i want to fetch HTML of cell plugins alone.

**Comment by macrozone** [comment]
> @macrozone return
> 
> 
> <Editor .... />
> Using the above approach it exports HTML of Editor as well, what if i want to fetch HTML of cell plugins alone.

set `readOnly` to true! Sorry i forgot to write that

**Comment by mikeljoe1** [comment]
<Editor cellPlugins={cellPlugins} value={value} onChange={setValue} readOnly/> you mean this one ?

i want to extract HTML of the content which user is editing actively ? HTML of the content alone should be saved once the user is done with the editing
