### ISSUE TITLE
Error compiling slate plugin

### ISSUE THREAD

**Issue by rgamm** [react-page/react-page#1028]
Hi! This is perhaps a bit odd so I'm hoping it's a simple fix... I need to compile everything including the types, but when I try I get an error:
```
node_modules/@react-page/plugins-slate/lib/types/slatePluginDefinitions.d.ts:5:27 - error TS2307: Cannot find module '../slateTypes' or its corresponding type declarations.

5 import type { Data } from '../slateTypes';

```
I'm using bit.dev so you could try to reproduce the exact error by using it inside a component and using their isolated build environment, but it's probably easier to just look at the source code in github: https://github.com/react-page/react-page/blob/master/packages/plugins/content/slate/src/slateTypes.d.ts
and then browse a npm installed version and note that within `node_modules` directory `slateTypes.d.ts` does not exist, but is referenced by https://github.com/react-page/react-page/blob/master/packages/plugins/content/slate/src/types/slatePluginDefinitions.ts

This may be expected so please feel free to shut this down and I'll continue looking for a work-around, though seems odd for Typescript to not include base types with the lib.

Thanks for the great tool!

**Comment by macrozone** [comment]
thx for reporting @rgamm,

is there a reason why you can't use the npm module itself (and therefore the compiled code)?

slate needs this definition file, but maybe i can split the other exports out of it (Data), maybe i can optimize this

**Comment by rgamm** [comment]
I have to export it with underlying types because I use it in a library which then exposes some of them. Yeah I think it's only that Data type that gets lost so if that can be put into a non `d.ts` file, maybe i can make a PR

**Comment by macrozone** [comment]
@rgamm can you check with latest version?
