### ISSUE TITLE
Copy & Paste Blocks

### ISSUE THREAD

**Issue by konfilios** [react-page/react-page#1064]
I'm trying to copy a whole block from a react-page to another, but all I can find is "duplicate" within the same document. How can I "duplicate into clipboard" and "paste from clipboard"?

**Comment by macrozone** [comment]
@konfilios this is currently not supported, but it would be awesome to have that feature.
Maybe i can work on this next week or find someone.

Technically, it would be not that hard, its just copy the object of a Node (Cell) and past it (with a new id).

**Comment by konfilios** [comment]
That would be humongous! Thanks a lot for the immediate response!

**Comment by macrozone** [comment]
@konfilios you can test it on the beta version!

**Comment by konfilios** [comment]
Thank you very much! I'll test it asap!

**Comment by macrozone** [comment]
@konfilios its not explained directly in the editor, but you can basically select multiple cells by holding cmd or ctrl and then copy & paste with your usual shortcuts (cmd+c / cmd+v)

you can also copy a single cell that is focused (unless you have selected some text of course)

**Comment by konfilios** [comment]
I checked the demo. Works great! Thank you again!

**Comment by macrozone** [comment]
this has been released
