### ISSUE TITLE
support Material-ui 5

### ISSUE THREAD

**Issue by noorsheikh** [react-page/react-page#1085]
Does react-page support material UI version 5 or will it be supported anytime sooner?

**Comment by macrozone** [comment]
@noorsheikh did not test it yet, but i am aware of this. I hope that we can do it in a way, that both 4 and 5 should work (as it is a peer dependency. 

i am also thinking about abtracting the editor-ui-layer a bit more, that way we could provide a mui-4-compatibility layer and open up the possibility to bring your own ui

**Comment by masanaikeshima** [comment]
As a Tailwind user, a bring your own UI would be a great addition.

**Comment by agloolik** [comment]
Hi team, I would also like react page to support mui5, what can be done to help start this project ?

**Comment by macrozone** [comment]
> Hi team, I would also like react page to support mui5, what can be done to help start this project ?

you can clone it and try make it work with mui5!

you can then push a branch and open a PR (work in progres)

**Comment by MichaelKheel** [comment]
Yes, mui5 support is very lacking. I even tried to install both versions and it even works, but there is a style conflict between mui4 and mui5 and the use of the library becomes impossible. :(

**Comment by macrozone** [comment]
> Yes, mui5 support is very lacking. I even tried to install both versions and it even works, but there is a style conflict between mui4 and mui5 and the use of the library becomes impossible. :(

this is a problem of material-ui, which is surprising, because we use a custom prefix for the class-generator

**Comment by MichaelKheel** [comment]
Anyway, I really liked your library, I will try to transfer it to mui5 and if it works out, I will open a PR. Thank you.

**Comment by Clovel** [comment]
MUI switch from `@material-ui/<package>/<component>` to `@mui/metarial/<component>` in v5. It's not just bumping the existing dependency from v4 to v5. This might require some heavy rewriting if `react-page` is to use both. 

In the meanwhile, we are stuck with using v4. If you wish to use v5 and `react-page`, you'll have to install both v4 & v5 sadly.

**Comment by macrozone** [comment]
ideally, material ui can be used as a direct dependency, not as a peer dependency and can be used alongside other versions of material-ui.

there were some mixed results in the past with that approach, but we should give it a try once more.

the underlying ui-library should be an implementation detail and users should not worry about it.
I really don't like the way it is now with it beeing a peer dependency, but that was a trade off to fix bugs that could occure with having multiple versions of material ui

**Comment by macrozone** [comment]
i just released a first beta, which comes with material-ui version 5.

it may contains bugs and gitches and things that could be improved, so please give feedback!

you can see the result here https://react-page.github.io/beta

you can install it with the @beta tag

**Comment by agloolik** [comment]
This is great, I'll give it a few test runs and give feedback. :)
