### ISSUE TITLE
disable some controls in the sidebar

### ISSUE THREAD

**Issue by macrozone** [react-page/react-page#1088]
### Discussed in https://github.com/react-page/react-page/discussions/1087

<div type='discussions-op-text'>

<sup>Originally posted by **RajathShanmugaiah** October 22, 2021</sup>
![Capturenew](https://user-images.githubusercontent.com/63197365/138450196-cf8b9c8e-52af-4fb1-b7ea-389c0d0a54e9.PNG)
Is there a way I can pick only few controls out of these as I don't require resize and move option in my project.</div>

proposal:

add `disableLayoutMode`, `disableResizeMode`  which would remove these buttons.

these could then be used here: https://github.com/react-page/react-page/blob/master/packages/editor/src/ui/Sidebar/index.tsx#L55

that should be straight forward and could be a good first issue for a community contribution!

**Comment by shanthi-techie** [comment]
Any update on this ?

**Comment by macrozone** [comment]
no, feel free to open a Pull request!
