### ISSUE TITLE
shows error with typescript strict:true

### ISSUE THREAD

**Issue by macrozone** [react-page/react-page#1104]
see also https://github.com/react-page/react-page/issues/1103

**Comment by macrozone** [comment]
will be fixed soon

**Comment by yektas** [comment]
The PR is still open, when will it merge?

**Comment by macrozone** [comment]
@yektas should be fixed in beta. Not fully tested though (thats why beta), but on first sight it works properly

**Comment by macrozone** [comment]
fixed
