### ISSUE TITLE
Change the variant of the move node buttons

### ISSUE THREAD

**Issue by zehawki** [react-page/react-page#1138]
Suggest that the variant of the cell movement buttons not be "contained" and should be same as < ScaleButton /> and other buttons to match the same UI. They needless take away visual focus from other important controls.

Also, as per Material guidelines, since these are not the main actions on the taskbar they should not be "contained" anyway.

**Comment by macrozone** [comment]
> Suggest that the variant of the cell movement buttons not be "contained" and should be same as < ScaleButton /> and other buttons to match the same UI. They needless take away visual focus from other important controls.
> 
> Also, as per Material guidelines, since these are not the main actions on the taskbar they should not be "contained" anyway.

i agree with you, they take away too much visual focus as they are not that important.

**Comment by zehawki** [comment]
Any chance this can make it way into the next release?
