### ISSUE TITLE
Image plugin: "Open link in new window checkbox" is always unchecked 

### ISSUE THREAD

**Issue by vasilis-lts** [react-page/react-page#1140]
**Describe the bug**
The "Open link in new window" checkbox of the image plugin, is not showing it's correct state.

**To Reproduce**
1. Go to https://react-page.github.io/
2. Click on the image plugin to edit it. (located left of the list that says batteries included at this time)
3. Add an image, a link and check "Open link in new window"
4. Click on preview page and click the image (it opens the url that you entered correctly, in a new window)
5. Back to react page click on edit blocks and click the image again to view it's settings
6. The "Open link in new window" checkbox is unchecked

**Expected behavior**
The "Open link in new window" checkbox should show the correct state of the plugin

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome
 - Version 97.0.4692.99

**Additional context**
Just want to say thanks for this great plugin, it helps a lot with our current project.

**Comment by konfilios** [comment]
Hello! We have reproduced this issue in our project, too. Are there any plans for a fix?

Thank you in advance!
