### ISSUE TITLE
Can't perform a React state update on an unmounted

### ISSUE THREAD

**Issue by neutron92** [react-page/react-page#1147]
**Describe the bug**
Im using the module  of @react-page/react-admin
when i add more than one component i got those 2 errors
```
createTheme.js:94 Material-UI: the createMuiTheme function was renamed to createTheme.

You should use `import { createTheme } from '@material-ui/core/styles'`
createMuiTheme @ createTheme.js:94
./node_modules/@react-page/editor/lib-es/ui/ThemeProvider/DarkTheme/index.js @ index.ts:3
```
` Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.`

**To Reproduce**
Just add more the one component in the screen in the same time for example 2 texts or video and text

**Expected behavior**
no console error

**Screenshots**
![image](https://user-images.githubusercontent.com/6135555/151279062-ee220803-ac5b-46ab-8e9e-5bbec73b1268.png)

**Desktop (please complete the following information):**
 - OS: window
 - Version React page: 4.5.0
 - React-admin version: 3.19.7
 - React version: 17.0.2
 - Browser: chrome
 - Stack trace (in case of a JS error):
```
 react-dom.development.js:67 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    at Renderer (http://localhost:3000/static/js/bundle.js:43465:70)
    at div
printWarning @ react-dom.development.js:67
error @ react-dom.development.js:43
warnAboutUpdateOnUnmountedFiberInDEV @ react-dom.development.js:23914
scheduleUpdateOnFiber @ react-dom.development.js:21840
dispatchAction @ react-dom.development.js:16139
(anonymous) @ index.tsx:132
Promise.then (async)
Renderer @ index.tsx:132
renderWithHooks @ react-dom.development.js:14985
updateFunctionComponent @ react-dom.development.js:17356
beginWork @ react-dom.development.js:19063
beginWork$1 @ react-dom.development.js:23940
performUnitOfWork @ react-dom.development.js:22776
workLoopSync @ react-dom.development.js:22707
renderRootSync @ react-dom.development.js:22670
performSyncWorkOnRoot @ react-dom.development.js:22293
(anonymous) @ react-dom.development.js:11327
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushSyncCallbackQueueImpl @ react-dom.development.js:11322
flushSyncCallbackQueue @ react-dom.development.js:11309
batchedUpdates$1 @ react-dom.development.js:22387
notify @ Subscription.js:15
notifyNestedSubs @ Subscription.js:85
handleChangeWrapper @ Subscription.js:90
dispatch @ redux.js:297
(anonymous) @ index.js:20
dispatch @ redux.js:659
(anonymous) @ insert.ts:205
setTimeout (async)
(anonymous) @ insert.ts:204
(anonymous) @ index.js:16
(anonymous) @ nodeActions.ts:282
(anonymous) @ index.tsx:32
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:4070
executeDispatch @ react-dom.development.js:8243
processDispatchQueueItemsInOrder @ react-dom.development.js:8275
processDispatchQueue @ react-dom.development.js:8288
dispatchEventsForPlugins @ react-dom.development.js:8299
(anonymous) @ react-dom.development.js:8508
batchedEventUpdates$1 @ react-dom.development.js:22396
batchedEventUpdates @ react-dom.development.js:3745
dispatchEventForPluginEventSystem @ react-dom.development.js:8507
attemptToDispatchEvent @ react-dom.development.js:6005
dispatchEvent @ react-dom.development.js:5924
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
discreteUpdates$1 @ react-dom.development.js:22413
discreteUpdates @ react-dom.development.js:3756
dispatchDiscreteEvent @ react-dom.development.js:5889

```

**Comment by neutron92** [comment]
you can check it here

https://stackoverflow.com/questions/70880844/react-page-react-admin-cant-perform-a-react-state-update-on-an-unmounted
https://codesandbox.io/s/adoring-tess-x11ve?file=/src/App.tsx

**Comment by neutron92** [comment]
@macrozone is it in the slate plugin right? i'm in the good way?

**Comment by macrozone** [comment]
> @macrozone its in the slate plugin right? i'm in the good way?

yes, its in the slate plugin's renderer, where we lazy load the SlateProvider in order to keep bundle size low when using it in readOnly.

Due to some reason this component unmounts before the slateProvider is loaded, which calls setState on an unmounted component.

there is nothing particularly wrong with that, but that warning is a bit annoying

This is a good read about the topic: https://www.rockyourcode.com/avoid-memory-leak-with-react-setstate-on-an-unmounted-component/

in this case, the simplests solution is to use a `IsMounted` variable as suggested in that link (chapter "Keep Track of Mounted State")

**Comment by neutron92** [comment]
@macrozone i do not have access to create a branch and push in your repo

**Comment by neutron92** [comment]
@macrozone  https://github.com/react-page/react-page/pull/1149

**Comment by macrozone** [comment]
@neutron92 thx, will look into it
