### ISSUE TITLE
Autoforms in the slate-plugins get displayed even if the schema is null

### ISSUE THREAD

**Issue by shanthi-techie** [react-page/react-page#1175]
Autoforms available in the slate-plugins is getting displayed when schema of the auto form is null.

```
import React, { useState } from 'react';
import { lazyLoad } from '@react-page/editor';
import { Field } from '../../type/Field';
import { pluginFactories } from '@react-page/plugins-slate';
import { Rnd } from "react-rnd";
import { textField } from '../Table/icons';

const TextFieldIcon = lazyLoad(
    () => import('@material-ui/icons/TextFields')
);
export default pluginFactories.createComponentPlugin<{   
}>({
    Component: () => {      
        return (
                <input type="text" 
                ></input>
        );
    },
    addHoverButton: false,
    addToolbarButton: true,
    type: 'FormFields',
    object: 'inline',
    isVoid: true, // <--- makes it a void plugin
    icon: <TextFieldIcon style={{ color: 'rgb(54, 69, 79)' }} />,    
    label: 'InputField',
});
```

**Expected behavior**
No autofrom should be displayed when the component is clicked on 

**current behavior**
its diplaying a pop up with cancel and ok button
**Screenshots**

![image](https://user-images.githubusercontent.com/66308775/162216390-724263ac-9080-4839-a4db-1e1a8925b35b.png)

**Desktop (please complete the following information):**
 - OS: [e.g. windows]

**Comment by macrozone** [comment]
ah that was an oversight with the isVoid type! thank you!

**Comment by shanthi-techie** [comment]
@macrozone  the usecase is, when 'formField' has been clicked a field should have been added to RTE because user has to no data to fill in the autoform

**Comment by macrozone** [comment]
wille come back to this
