### ISSUE TITLE
showIf in uniforms schema seems not to work with custom component

### ISSUE THREAD

**Issue by zehawki** [react-page/react-page#1187]
**Describe the bug**
"autoform controls now support showIf in schema to show fields conditionally" seems not to work with `ColorPickerField`. It works fine without a custom component.

`showIf` as shown here https://react-page.github.io/docs/#/custom-cell-plugins?id=passing-props-to-fields

**To Reproduce**
Example with schema defined as follows:

        color: {
          type: 'string',
          default: 'default',
          uniforms: {
            helperText: "Select the divider color.",
            options: [
              { label: 'Default', value: 'default' },
              { label: 'Primary', value: 'primaryColor' },
              { label: 'Secondary', value: 'secondaryColor' },
              { label: 'Custom', value: 'custom' },
            ]
          },
        },
        customColor: {
          type: 'string',
          default: '#CCCCCC',
          uniforms: {
            showIf: (data) => data.color === "custom", // show the field conditionally
            component: ColorPickerField,
          },
        }

The ColorPickerField always shows up:

![image](https://user-images.githubusercontent.com/8095144/168438600-b43b66cb-17e0-427c-8697-727b059a2c83.png)

Just to test, if I comment out the custom component in the schema, then it behaves as expected:

![image](https://user-images.githubusercontent.com/8095144/168438839-d7ceda54-8172-493f-8bad-22821abd5804.png)

![image](https://user-images.githubusercontent.com/8095144/168438854-e37d058b-d894-43c4-94c5-07beb91258f1.png)

**Expected behavior**

The ColorPickerField field should only show when the previous drop down value is "custom"

**Version**

4.10.0

**Comment by macrozone** [comment]
can confirm, this happens when you specify a custom component.

unfortunatly it has to do with the way the `showif` prop is implemented, as it is not supported by uniforms out-of-the-box, see https://github.com/vazco/uniforms/issues/1114

Have to think about another implementation

**Comment by jink-e** [comment]
Warning: React does not recognize the `_customComponent` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `_customcomponent` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

**Comment by macrozone** [comment]
> Warning: React does not recognize the `_customComponent` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `_customcomponent` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
> 
> env: "@emotion/react": "11.10.4", "@emotion/styled": "11.10.4", "@react-page/editor": "^5.1.5", "react": "17.0.2", "react-dom": "17.0.2",

this is unrelated, can you open an issue for that?
