### ISSUE TITLE
The editor meddles with the existing theme in case you are using MUI

### ISSUE THREAD

**Issue by amartya-dev** [react-page/react-page#1198]
**Describe the bug**
I am using mui with a custom theme, when I install and run this editor (which is awesome BTW), my navigation drawer's style gets messed up (after clicking the add blocks sign). Please let me know if I can somehow fix that

**To Reproduce**
1. Create a nav drawer with a custom theme, plug in the editor
2. Click on the `+` sign and see your theme get messed up.

**Expected behavior**
It probably should not override 

**Screenshots**
Before:
![image](https://user-images.githubusercontent.com/49491061/174141705-60892775-b567-4f9a-8fde-0bf9511365e9.png)
After:
![image](https://user-images.githubusercontent.com/49491061/174141796-5ded2a32-ed9f-4f12-96fc-2e9cafc15d71.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows :( but WSL] 
 - Browser [chrome]

**Comment by macrozone** [comment]
which version of material-ui do you use for the rest of the page? and which version of react-page do you use?

**Comment by amartya-dev** [comment]
I am using `"@mui/material": "^5.8.1"` and `4.11.1` for react-page/editor

**Comment by techfortified** [comment]
It is the same issue that i'm facing. Any solution to this?

**Comment by macrozone** [comment]
Version 5 of react-page uses @mui version 5 and is no longer a peer-dependency.

you now only have a conflict if you use material-ui 4, which is solveable and documented.

**Comment by techfortified** [comment]
wow thank you very much. I will update my packages asap.

**Comment by macrozone** [comment]
see the instroctions on the release-notes https://github.com/react-page/react-page/releases/tag/v5.0.0

should you encounter problems with it, please don't hesitate to open an issue!

**Comment by techfortified** [comment]
> see the instructions on the release-notes https://github.com/react-page/react-page/releases/tag/v5.0.0
> 
> should you encounter problems with it, please don't hesitate to open an issue!

Thank you. I have updated and everything is working great. No issues so far.
Keep the good work.
