### ISSUE TITLE
(v4) tabs on background block dont work

### ISSUE THREAD

**Issue by zehawki** [react-page/react-page#1206]
1. Starting here https://react-page.github.io/
2. Click on the 1st background block - controls open up
3. Clicking on tabs (single color, gradient color) doesnt switch tabs

@macrozone possible to make fix available on v4 branch? Given the breaking change of MUI5 in v5.

**Comment by macrozone** [comment]
@zehawki use v4 until this is fixed.

duplicate of https://github.com/react-page/react-page/issues/1210

**Comment by zehawki** [comment]
I am on v4 - version "4.11.0". That's why I was requesting if a fix can be made available on v4 branch. 

Its broken on v4 and then I tested on the latest demo and found the same behavior.

**Comment by macrozone** [comment]
i am not sure if configured semantic release properly to do maintenance releases, maybe i have to push that manually
