### ISSUE TITLE
Direct children for container components

### ISSUE THREAD

**Issue by IBelet** [react-page/react-page#1218]
First of all: I really like, what you've already done 👍

**Is your feature request related to a problem? Please describe.**
I wanna to create component, which will align its child using flex, but now an extra div is appended between parent and child https://github.com/react-page/react-page/blob/master/packages/editor/src/renderer/HTMLRenderer.tsx#L142

**Describe the solution you'd like**
I'd like to have plugins inside container plugin as direct children

And a more general question: WDYT about getting away from column layout?

**Comment by IBelet** [comment]
Do you think it's possible to remove most of the wrapper <div>'s (including ones with react-page-cell-sm-8)
It seems to be easy in readOnly, but kinda complicated in the editor mode. Just your opinion and maybe advice would be enough 😀

**Comment by macrozone** [comment]
@IBelet thx!

getting away from classic column layout is definitly a thing, but its breaking so it should be done with care.

That div is for inner padding / margin, not sure if its required when margin is 0, but it cannot be just removed as it is also a breaking change.

You should still be able to style that inner div though with css, styled-components or similar!
