### ISSUE TITLE
RaReactPageInput not working with react-admin

### ISSUE THREAD

**Issue by PiochU19** [react-page/react-page#1221]
Hi, I'm trying to connect react-page with react-admin, based on example code.
I downgraded couple of packages (React to v17, react-admin to ^3.14.2).

Problem is that when the content is empty, toolbar is in one line horizontally, and when there is an content, everything is spread out to the sides.
```
{
  "name": "test-admin",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@emotion/react": "^11.10.0",
    "@emotion/styled": "^11.10.0",
    "@react-page/editor": "^5.0.2",
    "@react-page/plugins-background": "^5.0.2",
    "@react-page/plugins-divider": "^5.0.2",
    "@react-page/plugins-html5-video": "^5.0.2",
    "@react-page/plugins-image": "^5.0.2",
    "@react-page/plugins-slate": "^5.0.2",
    "@react-page/plugins-spacer": "^5.0.2",
    "@react-page/plugins-video": "^5.0.2",
    "@react-page/react-admin": "^5.0.2",
    "@testing-library/jest-dom": "^5.14.1",
    "@testing-library/react": "^13.0.0",
    "@testing-library/user-event": "^13.2.1",
    "@types/jest": "^27.0.1",
    "@types/node": "^16.7.13",
    "@types/react": "^18.0.0",
    "@types/react-dom": "^18.0.0",
    "prop-types": "^15.8.1",
    "ra-data-fakerest": "^4.2.6",
    "ra-data-json-server": "^4.2.6",
    "react": "^17.0.2",
    "react-admin": "^3.14.2",
    "react-dom": "^17.0.2",
    "react-katex": "^3.0.1",
    "react-scripts": "5.0.1",
    "styled-components": "^5.3.5",
    "typescript": "^4.4.2",
    "web-vitals": "^2.1.0"
  },
  "scripts": {
    "start": "GENERATE_SOURCEMAP=false react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}
```
<img width="1206" alt="Screenshot 2022-08-12 at 10 00 21" src="https://user-images.githubusercontent.com/74414211/184315674-35fdf92e-518f-41ce-86f4-fe3045c70724.png">
<img width="1161" alt="Screenshot 2022-08-12 at 10 00 35" src="https://user-images.githubusercontent.com/74414211/184315719-b5cc085f-e5ff-406d-9e75-2410069c8298.png">

**Comment by macrozone** [comment]
make sure to include `import '@react-page/editor/lib/index.css';` somewhere in your admin code.

That should fix the issue

**Comment by PiochU19** [comment]
> make sure to include `import '@react-page/editor/lib/index.css';` somewhere in your admin code.
> 
> That should fix the issue

Thanks :) Fixed everything

**Comment by PiochU19** [comment]
> make sure to include `import '@react-page/editor/lib/index.css';` somewhere in your admin code.
> 
> That should fix the issue

Thanks :) Fixed everything
