### ISSUE TITLE
Proposal - Custom Rendering for inner Rows to achieve carousel, slider, tabs … etc.

### ISSUE THREAD

**Issue by NedalEldeen** [react-page/react-page#1231]
I’ve been exploring this editor for a while. And I’m pretty interested in it. I've been comparing different editors but I’m seeing potential in this one. **But what I’m facing right now with `react-page` editor is** “custom Cells/Rows rendering is kind of limited”.

I started a discussion regarding this point (https://github.com/react-page/react-page/discussions/1222). Plus, after I’ve explored many issues/PRs I found many people asking for this ability/flexibility but I don’t see any solution until now. **SO,** I need to re-open this discussion again. I have some ideas in my mind and I need to think out loud with you guys.

**_First,_** let’s look at the end result that I hope `react-page` to have;

**A - Carousel Use Case;**

![carousel -optimized](https://user-images.githubusercontent.com/26748456/187289131-315bda1c-4543-4b1f-8bd6-dfeeebaa2cc4.gif)

**B - Tabs Use Case;**

![tabs-optimized](https://user-images.githubusercontent.com/26748456/187289181-81de9bd5-7dfd-4063-b16a-392028888545.gif)

**_Second,_** let’s think together to achieve such a thing; **I’m proposing that we may** extend the props of the `Renderer` component of the cell plugin definition. Let's look at the current props of the `Renderer`;

<img width="1168" alt="Screen Shot 2022-08-29 at 10 28 53 PM" src="https://user-images.githubusercontent.com/26748456/187292852-5694dc1f-273d-435a-88f3-3a0f91a0fca4.png">

As we know, to insert/render inner cells/rows we must consume the `children` prop inside the `Renderer` component as the following example;

```js
const sliderPlugin: CellPlugin = {
  ...,
  Renderer: ({ children }) => (
    <div className='slider-container'>{children}</div>
  ),
};
```

This approach is simple and straightforward to insert/render inner cells/rows but it comes with its limitation. So, I’m thinking of passing extra props into `Renderer` component as;

- `innerRows: ReactElement[]` is an array of react Row components. We pass this prop into `Renderer` component so that if the user needs to render the inner Rows in a customized way, he can iterate through it.
- `insertInnerCell` is a callback function that the user can use to add inner cells or open the plugin drawer with the current reference node id. (_Maybe we use hooks for insertion instead of this prop_)
- `cellValue` is the value of this cell including the inner cells' data. It’s like the editor value but the root point starts at this cell. It’s an editor value slice. I don’t have final thoughts about this prop but I think it will be amazing to have. From this prop, we can access the data of inner cells. For example, `Tabs` cell can access the names of its inner `Tab` cells.

With those extra props, we can offer 2 approaches to users to insert/render inner cells/rows;

**A - Consuming `children` prop** which is so simple and straightforward but it comes with its rendering-customization limitation.
**B - Consuming `innerRows + insertInnerCell + cellValue` props** which gives users more flexibility to customize the inner rendering, and of course, it will come with its cost that will make users render the inner content on their own. It’s a cheap cost compared to the flexibility of the customization they will get.

**Let's have some code examples to show the difference between those 2 approaches;**

```js
const sliderPlugin: CellPlugin = {
  id: 'slider',
  version: 1,
  title: 'Slider',
  description: 'Insert Slider',
  allowClickInside: true,
  Renderer: ({ readOnly, innerRows, insertInnerCell }) => (
    <div className='slider-container'>
      {
        !readOnly && (<button onClick={insertInnerCell}>Insert Slider Item</button>)
      }
      <Carousel>
        {
          innerRows.map(row => <Carousel.Item>{row}</Carousel.Item>)
        }
      </Carousel>
    </div>
  ),
};

// --- VS ---

const sliderPlugin: CellPlugin = {
  ...,
  Renderer: ({ children }) => (
    <div className='slider-container'>{children}</div>
  ),
};
```

Another example that highlights the using of `cellData`;

```js
const tabsPlugin: CellPlugin = {
  id: 'tabs',
  version: 1,
  title: 'Tabs',
  description: 'Insert Tabs',
  allowClickInside: true,
  Renderer: ({ innerRows, cellData }) => {
    // we can itrate over the cellData to get the names of inner tab cells
    return (
      <div className='tabs-container'>
         <Tabs>
          {
            innerRows.map((row, i) => (<Tab label={`Tab (${i+1})`}>{row}</Tab>))
          }
        </Tabs>
      </div>
    );
  }
};

// --- VS ---

const tabsPlugin: CellPlugin = {
  ...,
  Renderer: ({ children }) => (<div className='tabs-container'>{children}</div>)
};
```

* _The code in the snippets is a dummy code for demo purposes._
* _The style in the GIFs is just a quick simple style for demo purposes._
* _The names of the extended props I’m proposing are just initial names, we can come up with more suitable and convenient names._

If anybody, especially the people who are familiar with the codebase, is interested in this proposal, please tell me your opinion and any considerations that should be taken before I start to make a PR.

**Comment by NedalEldeen** [comment]
Any thoughts here?

**Comment by macrozone** [comment]
@NedalEldeen not yet, I did not have the time to really understand it thoroughly.

One first input:

The Renderer is usually not there to mount ui elements for editor. It should just be the read-only component (ideally). The reason is that this guarantees that developers do not mount and load unessecary components in ready-only mode.

There is one exception which is slate, which does editing and displaying content in the Renderer.
So normally the controls of any cell should be in the bottom toolbar instead using the `controls` property.
If we allow to mount controls inside the cell (or around the cell), that we might do this with another property, so that Renderer stays what it is.

But still, we could think about some api or hook to make it easier to add a child inside the current cell. Maybe you could make a proposal in another issue?

So with that out of the way, let's talk about children:

children in a CellPlugin is already an array of rows, so you can distribute it in Tabs if you want. Did you try that?

**Comment by NedalEldeen** [comment]
@macrozone sorry for my late response.

I was talking about extending the `Renderer` itself. I thought it will work fine within the `read-only` mode. We will give the `Renderer` consumer the ability to render the cell whatever the editor is in `edit` mode or `read-only`.

Maybe you're right, we may think to extend the API or provide some hooks.

>children in a CellPlugin is already an array of rows, so you can distribute it in Tabs if you want. Did you try that?

Yes, I did but, if I remember correctly, `children` is a div containing an inner div and then the rows. I think `looping/traversal through children` is not a best practice at all.

**Comment by macrozone** [comment]
@NedalEldeen 

> Yes, I did but, if I remember correctly, children is a div containing an inner div and then the rows. I think looping/traversal through children is not a best practice at all.

yes, you are totally right!

the inner div is not even that important, its just to add some consistent cell-spacing (which is a questionable implementation anyway)


https://github.com/react-page/react-page/blob/master/packages/editor/src/core/components/Cell/Inner/index.tsx#L101

What might be a first solution is to introduce some ChildrenWrapper for CellPlugin's that could replace the default div , so you could replace it with a fragment

**Comment by natschz** [comment]
Is there any progress regarding this? 

This would be extremely helpful and needed!

**Comment by h0jeZvgoxFepBQ2C** [comment]
Yeah I would also need this fixed!
