### ISSUE TITLE
How to get the nodeId in the uniforms component

### ISSUE THREAD

**Issue by jink-e** [react-page/react-page#1246]
**Is your feature request related to a problem? Please describe.**
I was trying to manipulate the dataI18n (multi-language) data as
```js
// packages/editor/src/ui/I18nTools/I18nDialog.tsx
 const dataI18n = useCellDataI18nRaw(nodeId);

  const updateCellData = useUpdateCellData(nodeId);
  const reset = useCallback(
    (lang: string) => {
      updateCellData(null, {
        lang,
      });
    },
    [updateCellData]
  );
```
in a `uniforms' custom component`. I don't know how to get the `nodeId` for `useUpdateCellData`.

**Describe the solution you'd like**
Be able to use `props.nodeId` in uniforms' component or a hook like `useCurrentNodeId()`

solution I found:
```js
const { cellIds } = useValueNode((editable) => ({
    cellIds: editable?.rows?.map((c) => c.cells.map((cell) => cell.id)) ?? [],
  }));
```

**Comment by macrozone** [comment]
@jink-e i see you found a solution. but i am curious what you wanted to achieve.

**Comment by jink-e** [comment]
> @jink-e i see you found a solution. but i am curious what you wanted to achieve.

I tried to implement a feature that allows user upload a excel to fill out the translation, so user don't need to click each language and edit the text.

for example:
user click a button to upload a excel as follow:

data.xlsx
|lang|value|
|-|-|
|en_US|english|
|zh_CN|简体中文|

got this:
```js
// xxx is the property name
dataI18n = {
en_US: { xxx: 'english'},
zh_CN: { xxx: '简体中文'}
}
```

**Comment by macrozone** [comment]
@jink-e I will push some changes that might help.

I assume:

- you want to add this import function to a custom CellPlugin
- this CellPlugin may have a form
- this CellPlugin should have an import button to import a csv

So i checked and i am unsure how you solved it, but i would do it like this:

- if you use the `uniforms`-controls on a cell-plugin, you can customize it to add custom code
- you can override `Content` on the controls, which receives a Component. in this component you now add custom functionality, without losing the default uniforms form

I added some changes and an example how to use this: https://github.com/react-page/react-page/blob/master/examples/pages/examples/customuniformsexperiments.tsx#L37

you see, you not only receive the nodeId (if you want to use the low-level hooks), but also an onChange function where you can also update the data in another language (for convenience)

There will be a new version in a few minutes where you can use this improvement.
