### ISSUE TITLE
Allow Customization of Plugin Drawer

### ISSUE THREAD

**Issue by JoaoCampos89** [react-page/react-page#1248]
**Is your feature request related to a problem? Please describe.**

I am looking to group blocks by type on the Plugin Drawer UI component, for instance, I have layout related blocks and components relatedo to crypto, I wanted to customize the way the plugin list is displayed and also add checkboxes to filter by type on the search bar.

**Describe the solution you'd like**

The best way it would be allow to costumize the plugin drawer component with a custom render component for search and another to list the plugins,

**Describe alternatives you've considered**

The easy way just allow to override the plugin drawer component.

**Comment by macrozone** [comment]
oh yeah, its also something I wanted to do for a long time...
