### ISSUE TITLE
Does not work with vite

### ISSUE THREAD

**Issue by SebastianStehle** [react-page/react-page#1256]
**Describe the bug**
I wanted to build a sample project with vite and react-page, but as soon as I integrate the editor component it fails with:

```
Uncaught SyntaxError: Export 'import_react3' is not defined in module (at chunk-MDNT3GH3.js?v=c8b68aaf:17613:3)
```

**To Reproduce**
1. Check out this sample: https://github.com/Squidex/squidex-samples/tree/compose-sample/jscript/react/sample-compose
2. Start it with `npm i && npm run dev`
3. Goto http://127.0.0.1:5173/editor

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome

Vite 3.2.3 and React 17.0.1, React-Page Editor: 5.2.0

**Comment by macrozone** [comment]
Hi @SebastianStehle 

Best check with vite's support and community what's wrong. Unfortunatly, we cannot help with that as no one uses vite currently in our team.   

Is there a particular reason, why you want to use vite? I in general recommend to use nextjs when building a webapp with react as it seems to become the defacto standard for building react apps.

**Comment by SebastianStehle** [comment]
Thanks for your feedback. I just wanted to build a very small sample for my CMS and use stuff that I am familiar with. I heard that CRA is basically dead and I was not in the mood to dig into next.js ;) 

But I moved back to create-react-app and it is working fine. 

Only the vertical alignment inside some buttons drives me crazy :D 

![image](https://user-images.githubusercontent.com/1236435/204273250-660c7a30-e8aa-47ae-9a3b-b073aeb567c5.png)

**Comment by macrozone** [comment]
> Only the vertical alignment inside some buttons drives me crazy :D
> 
> ![image](https://user-images.githubusercontent.com/1236435/204273250-660c7a30-e8aa-47ae-9a3b-b073aeb567c5.png)

yeah, that alignment looks odd, which brower is that?

**Comment by SebastianStehle** [comment]
Chrome under Windows. Same with firefox and Windows.

**Comment by macrozone** [comment]
i think the underlying issue is fixed as well as the plus icon
