### ISSUE TITLE
ReferenceError: global is not defined

### ISSUE THREAD

**Issue by Aikain** [react-page/react-page#1262]
**Describe the bug**
`global` is assumed to be defined. Vite doesn't define it by default like webpack.

```
Uncaught ReferenceError: global is not defined
    at StickyWrapper.tsx:108:5
    ...
```

**To Reproduce**
There is example in codesandbox:
https://codesandbox.io/p/sandbox/frosty-microservice-cgvq4k

**Expected behavior**
There should be better check if `global` is defined or use correct "global" (`window`).
https://github.com/react-page/react-page/blob/master/packages/editor/src/editor/StickyWrapper.tsx#L108

Please correct me if I'm wrong, but isn't `global` for nodejs and `window` for browsers? If want use something that work regardless of environment, should use `globalThis`?
https://developer.mozilla.org/en-US/docs/Glossary/Global_object

There is workaround for this for now, but I think there should be no need to set up this in every project which use react-page and vite.
```ts
// https://stackoverflow.com/a/73208485/8380119
window.global ||= window;

// For TypeScript
declare global {
    interface Window {
        global: Window;
    }
}
````

**Comment by macrozone** [comment]
@Aikain thanks for reporting! Can you create a pull request for that? i think in that line `global` can just be replaced with `window`. I probably copied that from another project

global as mostly an alias for the window object in browser. I had the impression that most (all) bundlers would do that.
