### ISSUE TITLE
OnChange no longer assigns to existing data

### ISSUE THREAD

**Issue by PeterKottas** [react-page/react-page#1278]
**Describe the bug**
When updating to the latest version (v5.4.1) I noticed that calling OnChange inside a plugin no longer assigns to existing data, it replaces them. This breaks some of the existing plugins. Not sure when this was introduced though.

**To Reproduce**
Go to https://react-page.github.io/ and play with the background plugin. Once you change anything, the data disappears and it only holds the latest change. 

**Expected behavior**
I believe it should map onto existing data, if anything changed and is documented, we should probably at least fix the demo.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: ALL
 - Browser ALL
 - Version v5.4.1

**Comment by PeterKottas** [comment]
@macrozone I think you made [some changes](https://github.com/react-page/react-page/commits/3ef3395d96159c3b9b6fd8095f45b8a2ce8ffcef/packages/editor/src/core/components/hooks/node.ts) around these parts recently, I think you'll have some extra info as to what happened there. I believe it's [this code](https://github.com/react-page/react-page/blob/b09b551d1469ad0db4c2ef9a299be886251c554a/packages/editor/src/core/components/hooks/node.ts#L352) that's the hook that creates the onChange method. I am thinking this might have been an unintended sideffect of adding some language functionality?

**Comment by daniel-minchev** [comment]
I can confirm the bug, we also experience this.

**Comment by macrozone** [comment]
ok, that was not intentional. Will fix it asap

**Comment by PeterKottas** [comment]
I can confirm it works. Well done, thanks!
