### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by confettidc** [react-page/react-page#1283]
**Describe the bug**
Don't know why the editor sometimes disappears with above error when embed to browser using webpack.

**To Reproduce**
Use webpack to complie reactjs version, embed to website.

**Expected behavior**
The editor should load normally

**Screenshots**
![圖片](https://user-images.githubusercontent.com/5524183/220821946-49b18b73-2fc9-4d68-a18a-0530104a8bc0.png)

**Desktop (please complete the following information):**
 - OS: macOS Ventura (version 13.2.1)
 - Browser: Chrome
 - Version: 110.0.5481.100

**Comment by macrozone** [comment]
@confettidc without code its not possible to help, but if I could make a guess, you probably pass a new instance of some props every new render

**Comment by confettidc** [comment]
Hi,

Maybe attach below source for reference (js):

`import React, { useState, useEffect, useRef, useCallback } from 'react';
import uuid from 'react-uuid';
import axios from 'axios';
import FormData from 'form-data';

import Editor, { Value } from '@react-page/editor';
//import '@react-page/editor/lib/index.css';

// The rich text area plugin
import slate from '@react-page/plugins-slate';
//import '@react-page/plugins-slate/lib/index.css';
// image
import { imagePlugin } from '@react-page/plugins-image';
//import '@react-page/plugins-image/lib/index.css';

import spacer from '@react-page/plugins-spacer';
import divider from '@react-page/plugins-divider';
import background, { ModeEnum } from '@react-page/plugins-background';
import html5video from '@react-page/plugins-html5-video';
import video from '@react-page/plugins-video';

import LeftImageRightText from './Components/LeftImageRightText';
import ColorPicker from './Components/ColorPicker';
import FontSize from './Components/FontSize';
import TRANSLATIONS from './translations';

const App = (props) => {
	useEffect(() => { // to be updated after render
		axios.get(`/admin/sys-screenplay-pages/ajax-get-page-data/${props.sys_screenplay_page_id}`).then(response => {
			//console.log(response.data);
			setValue(response.data);
		});
	}, []);

	function uploadImage() {
		return function (file, reportProgress) {
		    return new Promise(resolve => {
		    	const formData = new FormData();
		    	formData.append('_csrfToken', props.csrf_token);
		    	formData.append('image', file);

		    	axios.post(`/admin/sys-screenplay-pages/ajax-upload-image/${props.sys_screenplay_page_id}`, formData).then(response => {
		    		console.log(response);
		    		resolve({ url: response.data.url });
		    	});
		    });

		};
	}

	const uiTranslator = useCallback((label) => {
	    if (label && TRANSLATIONS[label] !== undefined) {
	      return TRANSLATIONS[label];
	    }
	    return `${label}(to translate)`;
	  }, []);

	const slatePlugin = slate(slateDef => ({
		...slateDef,
		plugins: {
			...slateDef.plugins,
			yourCustomNamespace: {
				color: ColorPicker,
				font_size: FontSize
			},
		}
	}));

	const cellSpacing = {
	  x: 15, // horizontal cell spacing
	  y: 20, // vertical cell spacing
	};
	
	// Define which plugins we want to use.
	const cellPlugins = [
		slatePlugin,
		imagePlugin({
			 imageUpload: uploadImage()
		}),
		divider,
		spacer,
		video,
		html5video,
		background({
		    imageUpload: uploadImage(),
		    enabledModes:
		      ModeEnum.COLOR_MODE_FLAG |
		      ModeEnum.IMAGE_MODE_FLAG |
		      ModeEnum.GRADIENT_MODE_FLAG,
		  }),
	];

	const [value, setValue] = useState(null);

	const onChange = (newValue) => {
		//console.log("onChange");
		//setValue(newValue);

		//console.log(newValue);

		const formData = new FormData();
		formData.append('_csrfToken', props.csrf_token);
		formData.append('page_data', JSON.stringify(newValue));

		axios.post(`/admin/sys-screenplay-pages/ajax-save-page-data/${props.sys_screenplay_page_id}`, formData).then(response => {

		});
	}

	return (
		<>
		<Editor
			cellPlugins={[LeftImageRightText, ...cellPlugins]}
			value={value}
			onChange={onChange}
			uiTranslator={uiTranslator}
			cellSpacing={cellSpacing}
		/>
		</>
	);
}

export default App;`


webpack:
`const path = require('path');
module.exports = {
    //mode: 'production',
    mode: 'development',
    entry: {
        index: './src/index.js'
    },
    devtool: 'inline-source-map',
    output: {
        filename: 'bundle.js',
        path: path.resolve(__dirname, './'),
    },
    module: {
        rules: [
            {
                test: /.js$/,
                exclude: /node_modules/,
                use: {
                    loader: 'babel-loader',
                    options: {
                        presets: ['@babel/preset-react']
                    }
                } 
            },
            {
                test: /\.css$/i,
                include: '/node_modules/',
                use: [
                    {
                        loader: 'css-loader',
                        options: {
                            modules: true
                        }
                    },
                    {
                        loader: 'style-loader',
                    }
                ],
            },
            {
                test: /\.s[ac]ss$/i,
                use: ['style-loader', 'css-loader', "sass-loader"],
            }
        ]
    },
    performance: {
        hints: false,
        maxEntrypointSize: 512000,
        maxAssetSize: 512000
    }
};
`

**Comment by macrozone** [comment]
@confettidc you need to memoize the properties you send to react-page. On each change, they are not referentially equal, so we assume the props are new.
