### ISSUE TITLE
Dependency Conflict with @react-page/react-admin and react-admin

### ISSUE THREAD

**Issue by oleksiisurnin** [react-page/react-page#1323]
### Description
I am encountering a dependency resolution issue when attempting to install `@react-page/react-admin` in a project that already includes `react-admin`.

### Steps to Reproduce
1. Include `react-admin` version `4.16.2` in the project.
2. Run `npm i @react-page/react-admin`.

### Expected Behavior
`@react-page/react-admin` should install successfully, ideally being compatible with `react-admin` version `4.16.2`.

### Actual Behavior
The installation fails with an ERESOLVE dependency resolution error. The error log indicates a conflict between the required version of `react-admin` for `@react-page/react-admin` and the installed version of `react-admin`. `@react-page/react-admin` seems to require a `react-admin` version in the `^3.0.0` range, which conflicts with the installed version `4.16.2`.

### Possible Solution
A potential solution might be updating `@react-page/react-admin` to support `react-admin` version `4.x`, or providing guidance on how to manage this dependency conflict.

### Additional Context
Here is the error log for reference:
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! While resolving: admin@0.1.0
npm ERR! Found: react-admin@4.16.2
npm ERR! node_modules/react-admin
npm ERR!   react-admin@"^4.15.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react-admin@"^3.0.0" from @react-page/react-admin@5.4.4
npm ERR! node_modules/@react-page/react-admin
npm ERR!   @react-page/react-admin@"*" from the root project
npm ERR!
```

Thank you for any assistance or guidance you can provide on this issue.

**Comment by macrozone** [comment]
ah the version in `@react-page/react-admin` is old and not compatible with react-admin4. i reopened a staled issue about that: https://github.com/react-page/react-page/issues/1292
