### ISSUE TITLE
core: DOM changes cause page jumping

### ISSUE THREAD

**Issue by aeneasr** [react-page/react-page#221]
this is probably upstream, build reproducible case and post in react repository

**Comment by inyono** [comment]
You did remove merge/split, did you? Before that, I thought that merge/split is causing this issues because I merge multiple div's into one (and therefore replace old DOM nodes with a single new one) and I'm pretty sure that React can't understand this w/o providing the same key to those nodes.

**Comment by arekkas** [comment]
ah, so keeping the same id's could solve this?

**Comment by inyono** [comment]
Yeah, maybe. We would also need to pass down the id as key
