### ISSUE TITLE
plugins/slate: move serialize / unserialize to plugins

### ISSUE THREAD

**Issue by inyono** [react-page/react-page#243]
* [x] Move serialize/unserialize to slate plugins
* [ ] Also refactor plugin system (don't use classes)

**Comment by arekkas** [comment]
what is this about again?

**Comment by arekkas** [comment]
I resolved #1

**Comment by macrozone** [comment]
Plugin system is a bit improved (but not yet perfect), i'll close that here. Feel free to reopen
