### ISSUE TITLE
layout: make grid customizable

### ISSUE THREAD

**Issue by aeneasr** [react-page/react-page#310]
Bootstrap 4.0 will no longer support float-based layout grids. I think we can do the same and move completely to flexbox grid. While doing so, we should make the grid customizable. I have a few ideas here and would love to hear your ideas on it (ping @inyono )

First I think it should be possible to have a global override for cell and row name-generators. Currently, we have a hard-coded name-generator in each cell:

```jsx
const gridClass = ({ node: { size }, isPreviewMode, isEditMode }: ComponentizedCell): string => `cell-${isPreviewMode || isEditMode ? 'md' : 'xs'}-${size || 12}`
```

One of the ideas is to make this customizable through the editor instance:

```jsx
const editor = new Editor({
  generateCellClassName: (props) => ...
  generateRowClassName: (props) => ...
})
```

Another idea is to have the same feature for plugins. For example, I'd like to hide spacers on mobile devices:

```jsx
export default {
  Component,
  name: 'ory/editor/core/content/spacer',
  version: '0.0.1',
  IconComponent: <AspectRatio />,
  text: 'Spacer',

  
  generateCellClassName: ({size}) => `cell-md-${size || 12} cell-hidden-xs`
}
```

**Comment by arekkas** [comment]
However, I have not figured out yet how we would deal with conflicts, more specifically: what happens if both plugin and editor config have overrides? Also the question remains if we want authors to be able to dictate mobile behaviour or not, and if we do how to make it as easy and seamless as possible
