### ISSUE TITLE
ux: hotjar observations

### ISSUE THREAD

**Issue by aeneasr** [react-page/react-page#312]
This is a list of observations made via the hotjar recordings feature during our initial testing phase:

* Some testers did not understand that they need to drag the elements from the drawer into the content, or it happened by accident
* People understood much quicker what they need to do once they had to explicitly launch the editor
* Having the toolbar active from the start resulted in people trying to edit / move stuff right away, before (sometimes) resorting to the toolbar on the right
* Mobile experience needs much improvement
* Some users tried to move layout cells as well
* Some users double clicked on content to make it editable before noticing the edit thing

Resulting tasks:

* [ ] Instead of starting in preview mode, start with edit mode
* [ ] Improve the drawer drag & drop. Maybe have insert toggles instead (like on squarespace)?

**Comment by macrozone** [comment]
**Instead of starting in preview mode, start with edit mode** --> is implemented in 0.15.0

**Improve the drawer drag & drop. Maybe have insert toggles instead (like on squarespace)?** --> would be nice, but i close for now to keep issue count low.
