### ISSUE TITLE
plugins/default: remove default cell when it's empty and the only one

### ISSUE THREAD

**Issue by aeneasr** [react-page/react-page#326]

**Comment by mrtysn** [comment]
+1 for this request. When you press backspace once more after everything you've typed is erased, you are stuck with the default cell. It overrides the editable text cell and the only way to remove it is via 'move things' interface

**Comment by arekkas** [comment]
Yes, one possibility would be to set a different default cell (e.g. text). But it also makes sense to not remove the last cell when pressing backspace.

**Comment by macrozone** [comment]
did not observe this anymore
