### ISSUE TITLE
Non-responsive layout in subscription section at the demo page

### ISSUE THREAD

**Issue by kirillDanshin** [react-page/react-page#341]
![2017-03-20 00 50 54](https://cloud.githubusercontent.com/assets/9026581/24085145/4babf9a8-0d07-11e7-9bfb-4ea789ea5be4.png)

**Comment by arekkas** [comment]
Thanks!

**Comment by kirillDanshin** [comment]
<img width="325" alt="Снимок экрана 2019-07-12 в 10 42 06 ПП" src="https://user-images.githubusercontent.com/9026581/61154262-5070f180-a4f6-11e9-859c-a5bbcd2a2618.png">

actually, it still broken on 320px
