### ISSUE TITLE
landing page: clicking on github removes trashed layout

### ISSUE THREAD

**Issue by d70-t** [react-page/react-page#344]
When the layout on the landing page (http://editor.ory.am/) has been trashed and the user clicks on the GitHub link to report an issue, the layout is lost. This potentially leads to less descriptive bug reports.

**Comment by arekkas** [comment]
Hey good point, currently there is no way to store the state of the page because it's all running in the browser. In the future we might add some localstorage or something. Another idea would be to simply open a new tab instead - what do you think?
