### ISSUE TITLE
plugins/slate: add anchor to headings

### ISSUE THREAD

**Issue by aeneasr** [react-page/react-page#381]

**Comment by mrtysn** [comment]
A common use case of editors is generating lengthy content. In order to provide a good user experience, I was looking for a way to anchor my headings in ory. 

How is the progress of this issue? I am willing to participate if there is an ongoing development.

**Comment by mrtysn** [comment]
An out of ory solution would also be possible, if there is a way to give 'id's to headings

**Comment by arekkas** [comment]
Yes that makes sense, I haven't really touched this as of now but it should be fairly easy to add this!

**Comment by macrozone** [comment]
With the current version, you should be able to add custom data to headings. So you could show a dialog where you prompt the user to give you an id. 

If you still need this @mrtysn and need some help, feel free to reopen or visit us on slack!
