### ISSUE TITLE
When copy/pasting from Microsoft Word, newlines are missing

### ISSUE THREAD

**Issue by canadaduane** [react-page/react-page#388]
We did a copy/paste test of ORY editor using MS Word for Mac. The formatting was stripped out (which is acceptable) but the newlines went missing, causing all lines of text from the Word document to be smashed together without whitespace as one long line.

**Comment by arekkas** [comment]
Hey thanks for your report. Indeed, copy paste has only very basic support at the moment, so all formating is lost when you paste things. We will work on this once our APIs are more stable :)

**Comment by canadaduane** [comment]
Keep up the good work!
