### ISSUE TITLE
General feedback from HN community member

### ISSUE THREAD

**Issue by aeneasr** [react-page/react-page#389]
> Looks pretty good and I didn't see performance issues. From a usability perspective it's simple to use. I would suggest a couple of usability improvements.
>
> 1. The right side buttons for edit, layout, etc. have tooltips (that's great) but they should be like on/off buttons e.g. clicking layout once puts the editor in layout mode, clicking it again should bring editor out of layout mode back into preview.
>
> 2. In Edit mode the buttons on the bottom work like on/off buttons (that's great) those buttons should have tooltips.
>
> 3. Editing an image I can't put an alt value or title? How accessible is the content created by the editor?
>
> Keep up the good work. I would use this for quick website/blog setup.

**Comment by arekkas** [comment]
> I wanted to walk you through my thought process regarding the right side buttons if you'll indulge me:
>
> 1. I clicked the edit button on the right to get in to edit mode. Edit button was highlighted in pink.
>
>2. Saw the buttons on the bottom appear when I clicked a Text section.
>
>3. Bolded some selected text by clicking the B button. B button got highlighted.
>
>4. Clicked the B button again and text went back to normal and the highlight on the B got turned off. (At this point I'm thinking cool buttons are on/off. On state is indicated by a highlight, Off state is indicated as normal style)
>
>5. Performed some other edits then clicked the Edit button the right since it was highlighted and based on my experience with the bottom buttons I expected clicking it again would turn off edit mode.
>
>You don't have to make the change. I just wanted to walk through the thought process of one user.
>
>Thanks for indulging me :)
