### ISSUE TITLE
Removing content from a page

### ISSUE THREAD

**Issue by yarwelp** [react-page/react-page#391]
It feels very difficult to remove content from a page quickly and some elements I can't manage to remove at all.

**Comment by arekkas** [comment]
Text cells support removing with backspace when they're empty. Other cells unfortunately currently don't have an easy way to be removed in edit mode. However, you can switch to layout mode and drag the cells onto the trash icon. That removes them.

**Comment by eriknstr** [comment]
I suggest allowing other cells to be removed with backspace in edit mode also.

Additionally I suggest that the delete key would also delete empty text cells and other cells.

**Comment by arekkas** [comment]
Yes, that makes sense! It's currently disabled for some cells due to input fields in the bottom toolbar which messed with backspaces etc. I think it's important to support fluent editing experiences, and shortcuts for removing things are definitely a part of this!
