### ISSUE TITLE
Table support?

### ISSUE THREAD

**Issue by abeq** [react-page/react-page#394]
Do you have plan to implement?

**Comment by arekkas** [comment]
Hey, yes, tables are on the roadmap!

**Comment by koneru1989** [comment]
@abeq @aeneasr I want to add table to editor. Do you have any update on table feature?

**Comment by aeneasr** [comment]
no updates atm, sorry

**Comment by SaadBazaz** [comment]
This is super necessary. Any plans on integrating?

**Comment by RogerBetter** [comment]
> This is super necessary. Any plans on integrating?

table please

**Comment by macrozone** [comment]
> > This is super necessary. Any plans on integrating?
> 
> table please

see this comment: https://github.com/react-page/react-page/issues/1100#issuecomment-996874042

tldr: its not planned, but contributions are very welcome!
