### ISSUE TITLE
Basic HTML editor/viewer

### ISSUE THREAD

**Issue by andrewmclagan** [react-page/react-page#395]
Any possibility to integrate a HTML code editor?

**Comment by arekkas** [comment]
Sure, that's possible - check out the slate.js plugin, it would probably work in a similar fashion!

https://github.com/ory/editor/tree/master/packages/plugins/content/slate

**Comment by arekkas** [comment]
Of course, the slate example is quite exhaustive. Check out the other plugins, maybe that gives you a better idea!

**Comment by macrozone** [comment]
i'll close this for the time beeing. Should be now easier to intregrate custom slate plugins like a html code editor
