### ISSUE TITLE
Document differences/relationship with Draft-js?

### ISSUE THREAD

**Issue by slorber** [react-page/react-page#400]
Hi,

I have noticed that this repo contains some older issues talking about DraftJS, and that conceptually this lib is quite similar as it backs editor state with JSON. It also accepts plugins like DraftJS-plugin-editor does to provide features like hashtags/mentions/whatever.

It seems currently this project does not depend on DraftJS however.

So, I am really wondering what are the differences between ORY and DraftJS. What reasons lead you to create a new editor that DraftJS wouldn't already handle? I think it would be great to document this for newcomers that have already been using DraftJS in the past.

**Comment by arekkas** [comment]
This project is using http://slatejs.org/ - a more modern rich text editor with a much cleaner API. The issue with both is that they work within `contenteditable`, which is known to cause issues if you want to create more complex layouts. The ORY Editor is first and foremost a layout editor, that is capable of rendering plugins with a slick API. So basically, the text editing plugin is a wrapped SlateJS react component.

Other editors don't support layout editing capabilities at all (most of the times just monolithic blob of text that you read top to bottom), or if they do with very dirty hacks based on `<table>` or other shinanigans. The ORY Editor was created specifically for handling multi-column content.

**Comment by arekkas** [comment]
Another example is including rich applets such as videos, twitter feeds, or similar things in contenteditable. It is possible to get it working for 80% of the use cases, but ending up with a production version is close to impossible. This is why the ory editor does not rely on content editable for the layouting part, and provides several default plugins (such as slate text editing) to get you started.

**Comment by slorber** [comment]
Thanks, I see. I didn't know slate but noticed the slate classnames in DOM.

**Comment by arekkas** [comment]
I should definitely add slate to the readme, it's a really cool project.

**Comment by davidfurlong** [comment]
closing as an answered old question and no longer actionable
