### ISSUE TITLE
bindActionCreators expected a function actionCreator error

### ISSUE THREAD

**Issue by Discordius** [react-page/react-page#416]
I am getting large amounts of errors that look like this: 

"bindActionCreators expected a function actionCreator for key 'CELL_INSERT_INLINE_RIGHT', instead received type 'string'."

I don't use bindActionCreators in any of my code that interacts with the ory-editor, though I do use it a few times on my own redux store. I haven't been able to make the bug not appear, so I don't really know the reason for this.

**Comment by arekkas** [comment]
Do you think you would be able to create a minimal reproducible case and upload it to github?

**Comment by tianhaoz95** [comment]
I got the same error, any update?
I am using react + redux

**Comment by arekkas** [comment]
Thanks for tracing this, I'll fix this soon!

**Comment by macrozone** [comment]
this should be fixed, i think? we are on redux 4 now
