### ISSUE TITLE
plugins/image: add alt tag and ability to wrap in h1-h6

### ISSUE THREAD

**Issue by aeneasr** [react-page/react-page#418]

**Comment by samuel-gaunt** [comment]
Why would you need to wrap an alt tag in a h tag?

**Comment by arekkas** [comment]
Good question haha, originally I thought that it could improve SEO in case a logo / header image uses an alt tag. Now that you brought it up I'm not so sure if that's really the case.

**Comment by samuel-gaunt** [comment]
Happy to take this on if you haven't already.

**Comment by arekkas** [comment]
Please do! :) If you need help don't hesitate to ask!

**Comment by macrozone** [comment]
I'll close this for now, feel free to reopen!
