### ISSUE TITLE
createFallbackCell cannot accept a layout plugin.

### ISSUE THREAD

**Issue by andrew-d-jackson** [react-page/react-page#429]
the CELL_CREATE_FALLBACK reducer only works with content plugins, not layout plugins. 

In https://github.com/ory/editor/blob/master/packages/core/src/reducer/editable/index.js#L26 line  it creates the state and plugin as a content plugin with no support for layout.

It would be good to be able to set the fallback to a layout plugin with its default state & children.

**Comment by arekkas** [comment]
Sounds good, I'll be able to look at this soonest in 2-3 weeks
