### ISSUE TITLE
core: enable native drag & drop

### ISSUE THREAD

**Issue by aeneasr** [react-page/react-page#446]
Enable dragging and dropping of native elements (such as file, url, text).

### Notes

To cancel the drop indicator the developer has to execute `editor.triggers().cellDragCancel()` in order to clear the drop indicator `onDragEnd` himself.

**Comment by arekkas** [comment]
Note for BM:

```jsx
  private onDragEnd = (e) => {
    this.setState({isDragged: false});
    if (this.props.onDragEnd) {
      this.props.onDragEnd();
    }

   // ... editor.triggers().cellDragCancel()

    const mpDragEnd = new CustomEvent('mp-dragend');
    window.dispatchEvent(mpDragEnd);
  }
```
