### ISSUE TITLE
hooks: deserializing custom slatePlugins not working

### ISSUE THREAD

**Issue by Knorrke** [react-page/react-page#471]
I added a custom plugin to slate, containing `deserialize` and `serialize` methods, but they aren't called by the `hooks.unserialize` method, since it only loops through the `defaultPlugins`. How do I get my plugins into `hooks.unserialize`?

**Comment by Knorrke** [comment]
For reference, please check my project at https://github.com/Knorrke/serlo-editor-example

especially: 
 - `App.js` https://github.com/Knorrke/serlo-editor-example/blob/master/src/App.js
 - Katex Plugin: https://github.com/Knorrke/serlo-editor-example/blob/master/src/components/plugins/content/slate/src/plugins/katex/index.js

**Comment by Knorrke** [comment]
Ping @arekkas I would take a look at it, if you can confirm that this is a bug in the ory editor slate plugin itself?

**Comment by arekkas** [comment]
Yeah it definitely is, speicifcally [here](https://github.com/ory/editor/blob/master/packages/plugins/content/slate/src/index.js#L23-L26) which is also used [here](https://github.com/ory/editor/blob/master/packages/plugins/content/slate/src/Component/index.js#L12). I think we could optionally pass the serializer [here](https://github.com/ory/editor/blob/master/packages/plugins/content/slate/src/index.js#L28) instead which would allow us more control

**Comment by macrozone** [comment]
hi @Knorrke, might be late, but this should work now properly.

Now the serializer / deserializer takes the passed plugins. Before, it only used the defaultPlugins. This was solved in this PR: https://github.com/react-page/react-page/pull/695

reopen, if you have any questions
