### ISSUE TITLE
Destroy editor instance

### ISSUE THREAD

**Issue by andreastoermer** [react-page/react-page#480]
Hello,

maybe i don't see it in the documentation, but is there a method to destroy the editor instance on componentWillUnmount inside a React Component?

At the moment, when I leave the component with the ory editor, the editor instance is not destroy and when I return to the component, it create a new instance.

Thanks for the answer

Best Regards
Andreas

**Comment by KillerCodeMonkey** [comment]
yeah asked me the same question... i have a global editor instance, and in my components i add editables with `editor.trigger.editable.add(xxx)`.

But how can i remove those instances?

**Comment by aeneasr** [comment]
I think this can be done with ReactDOM methods like „umountComponentAtNode“ - no guarantees
