### ISSUE TITLE
Ctrl-Z in editor treats movement as edit

### ISSUE THREAD

**Issue by Discordius** [react-page/react-page#484]
It seems that the editor probably doesn't want to treat cursor movement as edits that get reversed with CTRL-Z. Here is a replication: 

Edit a line.
Use the arrow keys to move the cursor elsewhere.
Ctrl-Z to undo the edit.

**Expected:**
The first press of Ctrl-Z undoes the last edit.

**Actual:**
The first press of Ctrl-Z moves the cursor to a previous position. Repeatedly pressing it eventually undoes the edit.

**Comment by arekkas** [comment]
Yes, that makes sense! I think we should transition to the new slate version which supports transforms before doing that though. I have not really looked at it yet in detail though.

**Comment by macrozone** [comment]
not sure if this still applies?

There are still some problems with ctrl+z, e.g. there are some "empty" changes in the undo stack that do nothing
