### ISSUE TITLE
Move plugin into trash

### ISSUE THREAD

**Issue by nqthuan303** [react-page/react-page#488]
can someone help me.
i want to get plugin's name after i move any plugin into trash. Thanks all

**Comment by nqthuan303** [comment]
help me please!

**Comment by fearhat** [comment]
Take a look into packages/ui/src/Trash/index.js :
https://github.com/ory/editor/blob/master/packages/ui/src/Trash/index.js#L34

**Comment by nqthuan303** [comment]
sorry, i dont understand your meaning

**Comment by nqthuan303** [comment]
do you have any examples code?

**Comment by fearhat** [comment]
The editor-ui components don't have any documentation yet, afaik.
I guess you have to reimplement your own Trash Component (which you could do by just copy-pasting the source file above) and do whatever you want to do inside the drop() function.
Not sure if that's even possible though - looks like the drop() function receives only the id of the component that was dropped over the Trash.

Another way could be modifying the reducers/actions of ory itself:
https://github.com/ory/editor/blob/master/packages/core/src/reducer/editables/index.js

So, looks like a lot of work, but maybe one of the contributors knows an easier way.
Sorry, no code examples, I've just recently started using ORY.

**Comment by nqthuan303** [comment]
thank for your help. :)

**Comment by arekkas** [comment]
Yes, that functionality does not exist currently. You could probably add a store middleware to listen to `CELL_DELETE` or something. If you have any smart ideas, feel free to propose them and/or create a PR!
