### ISSUE TITLE
getting an error and handling data 

### ISSUE THREAD

**Issue by mirik999** [react-page/react-page#494]
Hi people! 
1. When i am adding TEXT or PARALLAX BACKGROUND I am gettin an error - Warning: Received `true` for a non-boolean attribute `autoCorrect`. 
If you want to write it to the DOM, pass a string instead: autoCorrect="true" or autoCorrect={value.toString()}.

 2. When i am clicking to submit button i am checking data in console.log() and i am getting data like this (  {id: "0c753b02-2d79-4044-b928-fb04bf5081bd", inline: undefined, size: undefined, cells: Array(1)} )  and i have not idea how can i get normal data for sending to the server side. How can i serialize or deserialize ? What i must do with this data ?  i need output data in HTML.

Please if someone have any video tutorial or guide how to handle this beautiful text editor from zero ? I am beginner and i cant resolve many problems.

**Comment by arekkas** [comment]
My advice is to stay as close as possible to the example code if you are a beginner. Without context it is really hard to help you, and we try to keep the issues here primarily about bug reports and feature requests. There are different communities that help react beginners, such as reactiflux or stackoverflow.

**Comment by mirik999** [comment]
thanx

**Comment by jonas-arkulpa** [comment]
I had the same issue when I tried the editor with React 16.
(which is currently the default with create-react-app)
The errors where gone atm I switched back to React 15.4
package.json:
`"react": "^15.4.0", "react-dom": "^15.4.0", ...`

**Comment by arekkas** [comment]
Nice find, thanks! Reopening to track this

**Comment by RobinRadic** [comment]
I had this issue as well using React 16.

https://github.com/ianstormtaylor/slate/pull/1148 shows file changed `components/content.js`
```diff
-        autoCorrect={props.autoCorrect}
+        autoCorrect={props.autoCorrect ? 'on' : 'off'}
```

When i installed `ory-editor` it installed `slate@0.21.6`, which doesn't yet contain that fix.

I'm not totally sure about this but the fix should have been included in `0.25.1`, but stuff got moved around and they created `slate-react` by that point and that's not working with the `ory-editor-plugins-slate`.

As workaround i copied `slate@0.21.6` to a git repo, modified `components/content.js`, then referenced it in my package.json.

**Comment by arekkas** [comment]
@inyono is working towards upgrading the editor to latest slate, that will (hopefully) also allow us to update to latest react!

**Comment by mrmohtas** [comment]
What is the progress on this?
