### ISSUE TITLE
HTMLRenderer can't serialize type paragraph

### ISSUE THREAD

**Issue by miguel-orange** [react-page/react-page#498]
When I copy and paste plain text into `Editable`, `HTMLRenderer` gives an error `Uncaught (in promise) Error: No serializer defined for node of type "paragraph".` I'm using the same plugins and when I refresh editable it has no issue rendering this.
There is only one difference between the two objects. The pasted text version has `"type": "paragraph"` vs `"type": "PARAGRAPH/PARAGRAPH"`.

Typed
`{
    "id": "",
    "cells": [
      {
        "id": "",
        "inline": null,
        "size": 12,
        "content": {
          "plugin": {
            "name": "ory/editor/core/content/slate",
            "version": "0.0.1"
          },
          "state": {
            "serialized": {
              "nodes": [
                {
                  "kind": "block",
                  "type": "PARAGRAPH/PARAGRAPH",
                  "nodes": [
                    {
                      "kind": "text",
                      "text": "The Northwest"
                    }
                  ]
                }
              ]
            }
          }
        }
      }
    ]
  }`
Pasted
`{
    "id": "",
    "cells": [
      {
        "id": "",
        "inline": null,
        "size": 12,
        "content": {
          "plugin": {
            "name": "ory/editor/core/content/slate",
            "version": "0.0.1"
          },
          "state": {
            "serialized": {
              "nodes": [
                {
                  "kind": "block",
                  "type": "paragraph",
                  "nodes": [
                    {
                      "kind": "text",
                      "text": "The Northwest"
                    }
                  ]
                }
              ]
            }
          }
        }
      }
    ]
  }`

**Comment by developer-rakeshpaul** [comment]
@miguel-orange I also had the same problem. Where you able to solve this?. I wrote the below temporary hack to handle this. Just replaced the paragraph type with PARAGRAPH/PARAGRAPH before I save the content
```

export function replaceParagraphType(content) {
  const jsonString = JSON.stringify(content);
  const search = '"type":"paragraph"';
  const replacement = '"type":"PARAGRAPH/PARAGRAPH"';
  const newContent = jsonString.replace(new RegExp(search, 'g'), replacement);
  return newContent;
}

```

**Comment by arekkas** [comment]
Oh that might be some issue with the copy/paste handler and specifically the HTML deserializer, we have to upgrade to the new Slate version anyways soon, maybe that will resolve those issues.

**Comment by miguel-orange** [comment]
@developer-rakeshpaul, I handled it exactly how you did.

**Comment by fernandobandeira** [comment]
@aeneasr Still experiencing this issue here using `0.6.0` I'll use the proposed workaround for now.

**Comment by macrozone** [comment]
@fernandobandeira can you check if that is still the case?
