### ISSUE TITLE
"target" option for links in slate

### ISSUE THREAD

**Issue by AlexanderReiswich** [react-page/react-page#508]
There seems to be no way at the moment to add an attribute like `target="_blank"` to links created with the slate "create a link" button. Or am I missing something?

**Comment by arekkas** [comment]
That's true, feel free to PR to fix that!

**Comment by AlexanderReiswich** [comment]
@arekkas Is there documentation available on adding plugins to the slate ory component? I'm pretty sure I went through all the docs but couldn't find anything. It would be helpful.

**Comment by arekkas** [comment]
Not yet, but I'll direct you to the pieces:

* You can pass plugins to the slate factory, see [here](https://github.com/ory/editor/blob/master/packages/plugins/content/slate/src/index.js#L28)
* [This is what a plugin looks like](https://github.com/ory/editor/blob/master/packages/plugins/content/slate/src/plugins/Plugin.js)

Hope that helps

**Comment by davidfurlong** [comment]
Also dofollow/nofollow may be relevant for links

**Comment by macrozone** [comment]
@AlexanderReiswich  The slate plugin has now an "open in new tab/window" option. And its now very easy to add additional properties. Stuff like dofollow/nofollow should be now very easy to do!

Feel free to send in a Pull request for further improvement or reopen an issue if you need help!
