### ISSUE TITLE
plugins/slate: katex vs mathjax for formulas

### ISSUE THREAD

**Issue by aeneasr** [react-page/react-page#51]

**Comment by roker15** [comment]
Problem is react page has not table and slate has no katex i need both... What should I do

**Comment by roker15** [comment]
> just use Quill? that has katex suport https://quilljs.com/docs/formats/

i pasted some katex in thier live demo it did not work... only simple formulae worked... only editor so far worked for me is Suneditor
http://suneditor.com/sample/index.html , but looks like they are not very much active. When are u going to support table.?
