### ISSUE TITLE
How can I  change/translate the messages?

### ISSUE THREAD

**Issue by osdamv** [react-page/react-page#512]
For example in the file https://github.com/ory/editor/blob/master/packages/plugins/content/slate/src/plugins/link/index.js  
around the line 169 
```
<Dialog
              className="ory-prevent-blur"
              title="Create a link"
              modal={false}
              open={this.state.open}
              actions={[actions]}
>
```
I want to translate the prop title for "Crear Link" in Spanish.
I am new to react therefor my expertise with this framework is limited, however I was able to find is possible to change the properties of the the children [components](https://stackoverflow.com/questions/24939623/can-i-update-a-components-props-in-react-js), but I do not know how to implement that with the Ory editor toolkit.

Any example/documentation of how to translate would be very helpful!!!

**Comment by osdamv** [comment]
My prefer approach would be do a PR, is there any react  i18n framework
that you prefer guys ?

**Comment by arekkas** [comment]
Not really, but maybe you could post some you like and we review them together?

**Comment by sidati** [comment]
AirBnb PolyGlot was good enough for me : http://airbnb.io/polyglot.js/

**Comment by davidfurlong** [comment]
Duplicate
