### ISSUE TITLE
React-native support 

### ISSUE THREAD

**Issue by PeterKottas** [react-page/react-page#528]
Hello all and thanks for this very cool lib. It really seems like something we could use in our company, There's just one potential problem. We need to render the content on mobile devices with react-native. Theoretically, I could probably render it to a web view. But that comes with a lot of drawbacks and I would like to stay away from that. That's why I wanted to ask if there is any support for react-native (and/or react-native-web) existing or planned. If not, I might look into implementing something along the lines of the existing HTMLRenderer. But I would definitely appreciate some input on this first as chances are it can end up being a lot of work. Thanks

**Comment by arekkas** [comment]
Hi, there are currently no plans to support react-native and also no existing work. Contributing something along the lines of HTMLRenderer would probably be the best idea!

**Comment by PeterKottas** [comment]
Ok cool, good to know. I will see what the time allows. Currently we have a markdown solution which I am not very happy with. But implementing rendering for react native could take a while. I guess maybe keep this open or move to suggestions/feature requests if you have that. I will come back here if I have any progress. Probably in the following few weeks.

**Comment by inyono** [comment]
@PeterKottas We already wrote a renderer that outputs a table layout (for emails) instead. That was rather easy by forking https://github.com/ory/editor/blob/master/packages/renderer/src/index.js. You can probably do something similar by outputting React Native stuff here. Only complication I see: you probably need two plugin definitions for every plugin. One for editing (that uses HTML since I don't think that the editor will work in a React Native setup without major changes), one for rendering (that uses React Native)

**Comment by PeterKottas** [comment]
@inyono good stuff mate. It rly seems it might not be that hard after all. Good point about the plugins though. To be fair, I have no idea right now what plugins I will want to support. I only looked at this lib recently so I will need to get working knowledge of it. By any chance, is the package you created for emails open sourced? Cause we might actually use this for emails as well. Just thinking out loud tbh

**Comment by PeterKottas** [comment]
Just updating this thread with some new findings.
The layout plugin for RN would indeed be pretty straight forward.
Also the plugins in general would work imho. We would just need to find a clever way of switching between different components based on the platform. That require react-native package so we wood need some service that would return HTML be default if RN is not installed as peer-dependency. Again pretty straight forward.
However, the biggest problem and possibly a showstopper is the slate plugin. I in my naivety totally underestimated the size of it. slate.js apparently doesn't work with react-native even when there's some progress on this tracked here https://github.com/ianstormtaylor/slate/issues/1374, it still appears they will only internally wrap it in web view. That means that we are likely screwed when it comes to native support. 
The options are either switching slate for something that supports react-native (not aware of anything just yet), wrapping the whole thing in webview, or letting slate finish the work on this and wrap theirs in webview while here, we do things properly.

**Comment by arekkas** [comment]
Yeah slate will not work with native UI, it's completely different from native and wrapped around the DOM and the shitty contenteditable. Usually you're not writing rich text on mobile anyways...

**Comment by PeterKottas** [comment]
Yeah, that's right, it wouldn't have to be editable. But my understanding is (might be wrong) I still need to render the whole editor even when I am in readOnly. Right? And that will mess up RN. For reference, this is the file where <Editor /> is rendered. <Editor /> in this context is the slate.js editor which is not compatible. No matter if it's readOnly or not. The only way would be if there was something like <SlateRNRendered /> that would accept the state and only render. Hmm ... that actually might be doable.

**Comment by arekkas** [comment]
Right, the two models might not be compatible without a webview

**Comment by PeterKottas** [comment]
Forgot to send the link to the file before but it's hardly necessary, just for completeness sake : https://github.com/ory/editor/blob/master/packages/plugins/content/slate/src/Component/index.js
Anyways I'll keep this in mind and check how hard would it be to create a light-weight standalone react-native renderer for slate. That would fix most of the problems.
