### ISSUE TITLE
Installing Ory-Editor monorepo postinstall error

### ISSUE THREAD

**Issue by NunoFl** [react-page/react-page#536]
ory editor is giving me this problem when doing "npm i" command

npm ERR! undefined postinstall: npm-run-all clean clean:lerna bootstrap build:lib

https://github.com/ory/editor/blob/master/README.md#install-dependencies

**Comment by arekkas** [comment]
Please give a bit more information, for example, which node version are you using, which npm version, what is the error log, and so on.

Otherwise it is impossible to help.
