### ISSUE TITLE
Change toolbar style & how to make a container plugin

### ISSUE THREAD

**Issue by abel-olguin** [react-page/react-page#540]
The first question is; how can i make a container plugin with droppable? ej:
I have two plugins a input text plugin and form plugin (container);

when i drag the input plugin to the form, i need the input inside of form container.

I found this example: https://ory.gitbooks.io/editor/content/tutorials.html#writing-plugins
but when try to drag and drop the input plugin is not work, input is outside of container

The second question is; how can i change toolbar and actions styles?

**Comment by arekkas** [comment]
The first question is incredibly hard to answer without context. As you can see in the live demo, dragging container plugins works fine, so it's most likely related to your code.

The idea for changing the styles is currently for you to write your own modules that implement these. The idea here is to provide a quick way to get it working with our default modules, but if you need something customized, you should write your own.

**Comment by abel-olguin** [comment]
Hi @arekkas yep i did the drag and drop functionality, that's works fine because ory editor it's very open on this cases but, the second question is that I want to change the toolbar and put the float button in another position, as well as change the texts (translate them), how to make your own toolbar and your own float button? I have not seen documentation about it. sorry for my bad english :)
