### ISSUE TITLE
Custom data in serialised content

### ISSUE THREAD

**Issue by boyandimitrov** [react-page/react-page#543]
I want to render part of the serialised content. For this purpose I want to provide some custom data as a mark up. Here is an example: This is an layout that I can load. I tried to put some custom ids, that I can find after layout modifications. The problem is that when I modify and save the new layout there is a big chance my ids to be replaced by autogenerated ones. My final goal is to render only a small part of the final page (as preview). What can I do?

    `{
    "id":"d3b34c47-1aab-439f-a9df-3c275fed0511",
    "cells": [
      {
        "id":"0543f702-b34e-4656-bed3-3038ffa9e772",
        "inline":null,
        "size":12,
        "rows": [
          {
            "id":"row_1",
            "cells": [
              {
                "id":"header_title",
                "inline":null,
                "size":12,
                "content": {
                  "plugin": {
                    "name":"ory/editor/core/content/slate",
                    "version":"0.0.1"
                  },
                  "state": {
                    "serialized": {
                      "nodes": [
                        {
                          "kind":"block",
                          "type":"HEADINGS/HEADING-ONE",
                          "nodes": [
                            {
                              "kind":"text",
                              "text":"TITLE",
                              "bs_id" : "header_title_id"
                            }
                          ],
                          "data": {
                            "align":"center"
                          }
                        }
                      ]
                    }
                  }
                }
              }
            ]
          }
        ]
      }
     ]
    }
    `

**Comment by arekkas** [comment]
The IDs are updated as the content changes, there's currently not a good way around that. You might be able to add some metadata to the cells that helps you identify them based on properties you choose.

**Comment by boyandimitrov** [comment]
Did you mean that the author has to supply additional data ?  If this is the only solution I would more likely make a form with required fields to generate the preview.

I wonder can I use description or another unexpected property?

**Comment by arekkas** [comment]
> Did you mean that the author has to supply additional data ? If this is the only solution I would more likely make a form with required fields to generate the preview.

I was suggesting to write/modify plugin(s) that handles some type of persistent ID. The editor has to update the ID of these cells in order for reordering/layout modifications to work.
