### ISSUE TITLE
Improve theme handling

### ISSUE THREAD

**Issue by PeterKottas** [react-page/react-page#551]
The themes at the moment are done in a totally weird random way (theme provider is nested number of times in some occasions with no option to override easily, this is especially true for the way we have to have 2 themes, one light for toolbar when adding plugins, one dark for bottom toolbar and few other places). 
It's a real shame cause it's a strong feature of material ui that could definitely be used better. 
I would like to see something like this:
```
<UiThemeOverrides lightTheme={lightTheme} darkTheme={darkTheme}>
    <Trash editor={editor} />
    <DisplayModeToggle editor={editor} />
    <Toolbar editor={editor} />
</UiThemeOverrides>
```
Where UiThemeOverrides is an optional (no breaking change) component that would inject these 2 theme variants down the line. It might however open a few cans of worms as I explore how this is done at the moment across the whole lib. Ideas, preferences, existing work on this?

**Comment by arekkas** [comment]
Yeah I saw this in the PR but it was so huge it was difficult to spot all the places. The main problem is that we're using two themes - light and dark - in the UI right now. I think the bottom toolbar uses all dark while all other elements use white. Optimally, this would be the same theme everywhere.

It would be also cool if the editor didn't override an existing MuiThemeProvider:

```
<MuiThemeProvider>
  <Toolbar>
</MuiThemeProvider>
```

Here, `Toolbar` doesn't use its own styling but the provider given by the top component. If no MuiThemeProvider has been set (this can be checked from the context iirc), then it should use a default one. This would make things much easier and cleaner in the integration.

**Comment by PeterKottas** [comment]
Yeah one theme would make much more sense. I think I'll have to look into this as we have corporate theme that we need to adhere to. And it would be crazy to override every part of this with some custom css.
Initially I was dreaming about implementing whole new UI layer not relying on material ui ... but I was young and stupid then. Now that I've seen this size of this, I am pretty happy to just port out theme to material-ui, fix the problems with 2 themes here and make it overridable.

**Comment by arekkas** [comment]
> Now that I've seen this size of this, I am pretty happy to just port out theme to material-ui, fix the problems with 2 themes here and make it overridable.

That sounds do-able to me!

**Comment by PeterKottas** [comment]
Yep, I have few more PRs and ideas for 1 or 2 more, then I'll do this when everything is stable.

**Comment by PeterKottas** [comment]
Ok I've got some progress on this. Right now, we are almost able to achieve theme overriding. There are 2 things missing.

1. Provider in UI package needs to get theme from props and pass it to theme provider. No brainer
2. Plugins themes should also be over-ridable. And this is more complicated. We shouldn't make assumptions about plugins so obviously the public api shouldn't assume people use material-ui. Yet it's used in most builtin plugins. And it's locked down. The plugins wrapped in Provider which injects the theme. Of the top of my head, we could maybe add "extraComponentProps" to plugin api (type would be Object and of course it's optional). These props should be then passed into the component. In these plugins we could then just provide theme here and pass it along in the component. If you like this approach, I should be able to code it up in no time.

**Comment by arekkas** [comment]
> Plugins themes should also be over-ridable. And this is more complicated

You can detect if a theme provider exists by checking the react context. If it doesn't exist we can set it. If it does, we skip it.

**Comment by PeterKottas** [comment]
Okay that makes sense. I'll check how it's done then. Fingers crossed it will be just an easy change in the themeProvider.

**Comment by macrozone** [comment]
i managed to refactor themeProviders at some point, but i still get sometimes some unexpected results. 

Nevertheless, i close that for now
