### ISSUE TITLE
New plugins ideas

### ISSUE THREAD

**Issue by PeterKottas** [react-page/react-page#555]
I will be adding a few new plugins in the near future, I though this might be a good place to share ideas about it and possibly come up with some inspiration for features that would be appreciated by users. 
Let me first start with a question to @arekkas though.
Given the structure of the library (each plugin is a new package), is it reasonable to keep the growing number of plugins in this github repo? My fear is that build (and npm install) time will grow as we keep adding those. I know that you are open to 3rd parties but there are already a few plugins in this repo. Where do we draw the limit?

Anyways, here are the plugin ideas:

- colored-background (might also include gradients), this would obviously be layout plugin
- colored text - this is in fact a slate plugin that would be added so no big work necessary
- image background - again layout, simmilar to parallax background but without parallax effect (tbh, I would prefer to see a image-background plugin where you can turn on parallax rather than just parallax) also while improving, my colored-background might be stupid as well as this could be included here along with gradients
- image upload - unbelievable nobody shared this yet cause I am sure there's something out there (obviously there's some inherent complexity to this as it needs to be generic to allow for different providers/apis to work but it should be doable)
- divider with text - once again, either the old divider could be improved or new one can be implemented, expected end result to look something like this https://codepen.io/ericrasch/pen/Irlpm

**Comment by PeterKottas** [comment]
Also one extra question, I would prefer writing new packages in typescript. The way flow is setup currently appears to have lot of problems and I am spending lot of time fighting those. Would this be a problem? I can obviously modify the build to work just fine.

**Comment by arekkas** [comment]
I like all of those plugin ideas. They should definitely be in separate PRs. I think it's fine to have them in the main repository.

One issue with the repository set up is how watch mode works. It's painfully slow and resource intense as we're watching several directories independently. Adding another typesystem to the mix won't make it faster/easier to set up. I think we need to solve the flow issue first before we introduce typescript to this ecosystem.

**Comment by PeterKottas** [comment]
Ok fair enough, in the meantime I am making all my efforts for new code in flow anyways. I guess it's just easier for the time being.
