### ISSUE TITLE
Having problems with drag and drop

### ISSUE THREAD

**Issue by richtera** [react-page/react-page#558]
When dragging an image it goes through drag and drop, creates the native plugin but then when calling the final drop call "this.component" is null causing a failure and throwing an exception:
![image](https://user-images.githubusercontent.com/708186/44045966-2bb2ac6c-9ef8-11e8-9616-f36e9096b7f1.png)
The error is because component is null and therefore ```component.props.config.plugins``` cannot be resolved. The final result is the native plugin default showing without the file drag which is still available within this call.
![image](https://user-images.githubusercontent.com/708186/44046055-5e46de64-9ef8-11e8-8f4e-dd0c44b6854b.png)
So all I get is:
![image](https://user-images.githubusercontent.com/708186/44046085-73d25dc6-9ef8-11e8-9345-fb709e0f1935.png)
I am using the plain example implementation from your repo.

**Comment by davidfurlong** [comment]
sorry can't help out
