### ISSUE TITLE
Copy paste text in slate

### ISSUE THREAD

**Issue by PeterKottas** [react-page/react-page#563]
Right now if you select text inside slate editor, then copy and paste, it will insert some extra line-endings. I might be able to fix this but if you have any input, please share before I start working. Please note this problem goes away if you past it to html-less editor (e.g. notepad) I think it has something to do with the editor trying to treat the paste content as html. It deserializes and messed up somehow maybe?

**Comment by arekkas** [comment]
Actually, the content is completely sanitized and stripped from HTML. This could probably be fixed by simply stripping trailing newlines.

**Comment by PeterKottas** [comment]
Ok sounds reasonable, I might get to this once we merge in all of the current work.

**Comment by macrozone** [comment]
is this sill an issue? Can you recheck and reopen if so?
