### ISSUE TITLE
Tutorial not working

### ISSUE THREAD

**Issue by kristapsstrals** [react-page/react-page#573]
Following the tutorial at https://ory.gitbooks.io/editor/content/tutorials.html#reactjs-example I get the following issue:
`./node_modules/ory-editor-plugins-slate/node_modules/@material-ui/icons/Code.js`
Module not found: Can't resolve '@babel/runtime/helpers/builtin/interopRequireDefault' in '\node_modules\ory-editor-plugins-parallax-background\node_modules\@material-ui\icons'

Issue found with `"ory-editor": "0.3.1"`
Seems like an issue with updating to `@material-ui`. Downgrading to version `0.2.27` seems to work.

**Comment by kfern** [comment]
This is a material-ui bug: https://github.com/mui-org/material-ui/issues/12408


"As a quick workaround for anyone affected, you can run npm install --save-exact @babel/runtime@7.0.0-beta.55 if using npm or yarn add @babel/runtime@7.0.0-beta.55 --exact if using Yarn to revert back to the previous version of @babel/runtime compatible with Material-UI."

**Comment by aeneasr** [comment]
Ah yeah, I hope this stabilizes once babel is in stable 7.0.0 (I think this or next week) and we can upgrade react-scripts.

**Comment by aheissenberger** [comment]
using create-react-app version 2.1.1  and setting back babel to 7.0.0-beta.55 still gets me this error:
```
Failed to compile
./node_modules/ory-editor-ui/lib/Toolbar/Item/index.js
Module not found: Can't resolve '@material-ui/core/Avatar' in './TST/ory-page-builder/node_modules/ory-editor-ui/lib/Toolbar/Item'
```

**Comment by aksanoble** [comment]
You will have to explicitly install the peer dependencies. 
Based on your application you can try the following

`npm i @material-ui/core@^3.0.0 @material-ui/icons@^3.0.0 react-jss@^8.6.1 --save`

**Comment by BatuhanW** [comment]
Why are they peer dependencies anyway? Not everyone is using MUI or `react-jss` anyway.
