### ISSUE TITLE
print plugin

### ISSUE THREAD

**Issue by koneru1989** [react-page/react-page#576]
How about having print plugin?

**Comment by aeneasr** [comment]
Printing works for the presentation layer. So you simply take the webpage and call `window.print()`. Not sure what else we can offer here.

**Comment by koneru1989** [comment]
I went to https://editor.ory.am/ to check how window.print() prints. I have saved in pdf and attached the window.print() content. 
These issues are coming in the print like page breaks in the image, ory's icons like edit & Add things, images details like image location, link,.. .
[Ory.am Editor.pdf](https://github.com/ory/editor/files/2325186/Ory.am.Editor.pdf)
I think we need to have a print plugin which can take care of page breaks, alignment, formatting,...What do you say?

**Comment by aeneasr** [comment]
This is a css issue: https://www.w3.org/TR/css-print/

**Comment by aeneasr** [comment]
Converting the document to PDF is a ton of work, it's much easier to define a proper stylesheet for your webpage and let that print.
