### ISSUE TITLE
Consider adding code highlight？

### ISSUE THREAD

**Issue by An0nymous0** [react-page/react-page#589]
Such as prismjs

**Comment by Knorrke** [comment]
Hey @An0nymous0 we've build a plugin for that, maybe this matches your usecase? https://github.com/serlo-org/ory-editor-plugins/tree/62b3c509b140538b15499d7228efc95e29024ba8/plugins/content/highlight  We didn't deploy it yet, so you will probably have to download the code.

**Comment by An0nymous0** [comment]
@Knorrke  Thank you, I have encountered some problems downloading to the local, will this plugin be deployed?

**Comment by Knorrke** [comment]
@An0nymous0 I think we will do in a week or so, but we're currently running a fork of ory editor, so the plugin might change before we deploy it and then might not be compatible with the ory editor...
That being said, I think you should be able to include the linked version, which we use directly in the ory editor as well. Make sure to include the dependency `"react-syntax-highlighter": "^6.1.1",`. Let me know if I can help you with anything,

**Comment by macrozone** [comment]
@An0nymous0 shoudl probably be possible with custom slate plugins, watch this PR: https://github.com/react-page/react-page/pull/695

**Comment by PeterKottas** [comment]
This should definitely be done via slate and there should be a fair deal of available plugins for slate to do this. Closing for now.
