### ISSUE TITLE
tabs / carousel content plugin

### ISSUE THREAD

**Issue by jauco** [react-page/react-page#590]
I was thinking of writing a tabs plugin (tabs as in https://getbootstrap.com/docs/4.0/components/navs/#tabs ). For this I would have to be able to somehow split the client rows so that it is clear what cells end up on what tab page.

What would you suggest as an approach here?

**Comment by aeneasr** [comment]
Tabs are difficult if you want to create and delete them with drag and drop offered by this editor - but you can obviously write a dialogue that allows creating/deleting tabs.

**Comment by PeterKottas** [comment]
Tabs in general is a good idea in my opinion! You can get some inspiration of how it could be done in https://github.com/ory/editor/tree/master/packages/plugins/layout/background . That plugin, (especially the gradient part) has some complex UI that I could easily imagine powering tabs.

However one side-note. We are likely going to improve the way plugins controls and rendering work in the upcoming weeks/months. If you want, you can check our this PR https://github.com/ory/editor/pull/587 . It will be a good change, but definitely a big change. So you might want to take that into consideration ;)

**Comment by macrozone** [comment]
The new `@react-page/create-plugin-materialui"`package should make it easer to add a component with a custom dialog.

For this usecase i would probably create a layout plugin, where every tab contains a row. But we probably need some api to help creating new tabs.

I'll close this for now. @jauco if you still need help, feel free to reopen!
