### ISSUE TITLE
removeCell callback for plugins

### ISSUE THREAD

**Issue by colepacak** [react-page/react-page#592]
Thanks for the great library! I'm working on a custom image plugin that uploads an image to a backend and was wondering if there is a way to set a callback when a cell of a plugin type is removed. I didn't see one in the API docs but am curious if there are plans to add one or if there's another approach.

**Comment by aeneasr** [comment]
I’m not sure if a callback exists for that yet but if not it should!

**Comment by aeneasr** [comment]
I checked, it does indeed not exist yet but is a sensible feature request. Feel free to take this on and submit a PR!
