### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by PeterKottas** [react-page/react-page#593]
Hey @aeneasr hope you are enjoying your holidays! I've encountered some problems with ory performance lately and was hoping you could shine some light on these. I've summed it up in a video: https://screencast-o-matic.com/watch/cFQl6BqH09 

Also one extra thing, when in edit mode, clicking in different plugins comes with a lag as well. Not so noticeable as this one, but it's definitely there (maybe 1 second). I feel like it might be the same thing. In fact, when you turn on update highlight, you can clearly see that CELL_BLUR (not sure about the exact name but I think you know which action I mean) is triggered on focus, the whole editor re-renders. I feel like all these problems might have something to do with this. 

Do you have anything to share about this so that I can start looking in the right places?

**Comment by PeterKottas** [comment]
Also, running production react build doesn't help. Tried that while hoping for an easy solution :(

**Comment by aeneasr** [comment]
It's quite possible that `shouldComponentRender` is not working properly. There's a npm module [`whydidyouupdate`](https://github.com/maicki/why-did-you-update) which can shed some light on this

**Comment by PeterKottas** [comment]
I am thinking maybe resupplying and rechecking the ids for each leaf might be slow as well. Looking at this now, it seems the whole UI thread actually get stuck for the whole lag. That suggests (possibly) some intense computations. 

I can't look into this right away. But this is definitely highest priority for me right now.

**Comment by PeterKottas** [comment]
Ok, big benefiting factor seems to be the face that the editor renders the UI for all cells right away. Instead it should (IMHO) only render it when necessary, in other words, when you click on the cell. I'll take this into consideration when rewriting how the plugins work (the separation of concerns we discussed previously)

**Comment by macrozone** [comment]
@PeterKottas can we close this? I did not notice yet big performance problem, but i still have small editables. i will observe this

**Comment by macrozone** [comment]
@PeterKottas i constantly reduced unnsessary rerenders. The slate update and other changes in v0.17.0-beta.8 in particular should significantly improve performance. E.g. when clicking on a cell, the other cells no longer rerender.

**Comment by PeterKottas** [comment]
I am pretty sure this is now working much better, cheers!
