### ISSUE TITLE
Edit and delete buttons on component

### ISSUE THREAD

**Issue by PeterKottas** [react-page/react-page#595]
I was thinking that it would make sense to add edit (gear icon) button and delete (recycle bin) icon to the plugins controls when in edit mode.

Reason for edit button:
Sometimes, especially with background plugin, the component area is so small that it's hard to know where exactly should one click to edit plugin.

Reason for delete button:
I think it's weird you have to go to move and manually drag it to trash, we should be able to do this with a click in edit mode. Maybe with a prompt though.

I think if we like these, maybe it could be added to core, with some overrides to disabled or style this.

**Comment by aeneasr** [comment]
I think this should be handled on a per-plugin base. If the plugin is "known" to be difficult to focus, the author should implement a way to select and/or delete it. I don't think it should be the responsibility of the core.

**Comment by PeterKottas** [comment]
That sort of makes sense, but I still think it would be user friendlier to add some common way to have more consistent experience. In fact, it might be interesting to add "commonPlugins" that could add functionality like this to all plugins at the same time. No idea right now how that would be implemented. But I can see something along the way of how slate implements editorPlugins.

**Comment by aeneasr** [comment]
Ok, let's tackle the other things first - performance and separation of duties ( #587 ) are the most important issues right now IMO - and give this some thought once those are done!

**Comment by PeterKottas** [comment]
Yeah totally, right now I see priorities as:

1. Performance
2. Separation
3. Typescript
4. Then the rest of these

I am traveling till 8th of Oct I'll be online till then but not coding.

**Comment by aeneasr** [comment]
Ok! Enjoy your time off! I don't think I have time to address any of those as well, my schedule is completely stacked until end of Oct

**Comment by PeterKottas** [comment]
Thanks man. Yeah same here, we are now in public beta so lot of crap flying around. Major thing for me is the performance. I'll get to the rest then.

**Comment by macrozone** [comment]
Also noticed that and i think that is a good idea. We could also reveal these buttons when a button is pressed, so that it does not distract when not needed. When you are in rearrange-mode, it also shows some hints where the cells are. Something similar could be used in editMode

**Comment by macrozone** [comment]
@PeterKottas in current version, there is a trash icon on the bottom toolbar!  

It does note solve your first point, but the second. I close this for now, feel free to reopen!
