### ISSUE TITLE
Applying Theme

### ISSUE THREAD

**Issue by danielrea** [react-page/react-page#597]
Hey, Don't know if this is just user error on my part but I can't seem to get the ThemeProvider to work.

I have wrapped my editor and Ory UI components in

```
import { ThemeProvider } from 'ory-editor-ui'

const theme = createMuiTheme({
  palette: {
    type: 'dark',
  },
});

<ThemeProvider theme={theme}>
```

But they still have the default theme applied to them and the dynamic naming of the CSS classes means I can't override them. 

As a secondary question, does anyone know how I can find the class name of the black indicator line to show where your plugin is being added. We are using a dark background and so it is very difficult to see but I am also unable to inspect it due to the nature of it appearing.

Thanks, sorry if this has been covered before but couldn't find anything similar.

**Comment by aeneasr** [comment]
Good question, @PeterKottas you worked on this iirc, do you have an idea?

**Comment by PeterKottas** [comment]
Hi there, this is tracked in #551 It's on my list but I have quite a few things there now. If you wanted to pick that up with a PR that would be swell. The idea is if you look at ThemeProvider in ui package, you would just need to check context to see if theme already exists. If so, pass it along, if not, use our default.

**Comment by colepacak** [comment]
This was actually more straightforward than I thought, at least for UI elements like DisplayModeToggle. Feel free to weigh in, and I'll submit a PR if I'm on the right track.

After forking the repo, I added the following to /examples/src/index.js:

```
import { createMuiTheme } from '@material-ui/core/styles';
import purple from '@material-ui/core/colors/purple';
import green from '@material-ui/core/colors/green';
const theme = createMuiTheme({
  palette: {
    primary: green,
    secondary: purple,
  }
});
```

Then, I passed in `theme` as a prop to the DisplayModeToggle component:

```
ReactDOM.render((
  <div>
    <Trash editor={editor} />
    <DisplayModeToggle editor={editor} theme={theme} />
    <Toolbar editor={editor} />
  </div>
), document.getElementById('controls'))
```

DisplayModeToggle already passes all of its props down to the Provider UI component, so - finally - Provider just needed to pass its theme prop to ThemeProvider:

```
render() {
    const { editor, children = [], theme } = this.props
    const DragDropContext = this.DragDropContext
    return (
      <ReduxProvider store={editor.store}>
        <DragDropContext>
          <ThemeProvider theme={theme}>{children}</ThemeProvider>
        </DragDropContext>
      </ReduxProvider>
    )
  }
```

**Comment by PeterKottas** [comment]
Yeah I've put in a similar solution into a few places. But I don't like it. What I'd suggest instead is to check context in ThemeProvider to see if there is already a MUI theme provider present upstream. If so, use that theme, if not, use default or whatever is passed to it. I think that's the way to go. Hope it makes sense, plus it's actually even simpler imho

**Comment by colepacak** [comment]
How would you handle overrides when a ThemeProvider is already present? To be honest, I don't know how often that might happen throughout the entire system, but it seems reasonable that a system-wide theme is used but an individual component would want an override.

**Comment by PeterKottas** [comment]
Well right now you can't override anything at all. What you are suggesting would force people to inject theme via props to each ui component. That can get annoying rly quickly. The way I described would allow people to wrap whole app in one theme provider, the ThemeProvider implemented by ory ui, would then check context and use the global theme. We could configure this behavior further via a boolean property in case we want to disable it.

**Comment by colepacak** [comment]
I understand now. I had assumed that the MUI theme declared in ThemeProvider was the default theme since most things use that unless explicitly receiving the dark theme.

**Comment by aeneasr** [comment]
#600 sheds some light on issues with JSS providers, I think that's very valid as well.

**Comment by PeterKottas** [comment]
This has changed a lot over the years, closing now. If you still have a problem with this, please reopen with the latest version. Ty
