### ISSUE TITLE
Plugin instances receive isLayoutMode that returns a function rather than a boolean

### ISSUE THREAD

**Issue by colepacak** [react-page/react-page#607]
There's a good chance that I'm just missing something in the larger context, but I noticed that plugin instances receive a function for the prop `isLayoutMode` rather than a boolean like the other props that check the display mode. I tracked it down to the cell content component in the core package and am wondering if this was a mistake, because as a result there isn't a quick way to determine if the app is in layout mode from within a plugin.

Could you let me know if this was an intentional choice or a bug? Thanks!

**Comment by davidfurlong** [comment]
Where are you seeing this?

```
export const isLayoutMode = ({
  ory: {
    display: { mode },
  },
}: RootState): boolean => mode === DISPLAY_MODE_LAYOUT;
```

isLayoutMode is a selector function, which when connected to a react component via `createStructuredSelection` binds in a prop called `isLayoutMode` which is a boolean

**Comment by davidfurlong** [comment]
perhaps to reduce confusion these functions should be called `getIsLayoutMode` `getIsEditMode`...
