### ISSUE TITLE
Paste Function Fails in Text Field

### ISSUE THREAD

**Issue by RobertLbebber** [react-page/react-page#615]
Failure to paste on Chrome for React 16.5.2 

Also the entire page will crash if Cut and followed by Undo.

Provided Error  Snippet for paste:
 `Uncaught TypeError: n.getFirstInvalidDescendant is not a function
    at slate.es.js:5852
    at immutable.js:4492
    at List.__iterate (immutable.js:2206)
    at List.findEntry (immutable.js:4491)
    at List.find (immutable.js:4375)
    at Document.getFirstInvalidDescendant (slate.es.js:5851)
    at Document.object.(anonymous function) [as getFirstInvalidDescendant] 
...
`

**Comment by PeterKottas** [comment]
Same thing happening to me, investigating now.

**Comment by PeterKottas** [comment]
Ok solved it. In my case, I was using a lib that has slate as dependency, yet I was pulling in my own with a different version. The version mismatch was causing this issue. Do 
```
yarn why slate
```
or
```
yarn why slate-react
```
To figure out what's going on. 

This can be closed I guess.
