### ISSUE TITLE
New plugin idea: padding

### ISSUE THREAD

**Issue by fernandobandeira** [react-page/react-page#622]
I think we could have another default plugin, for padding.

Basically, it'd work similar to the background and spacer that we have right now, you'd be able to put other plugins inside it and you'd have a spacer like UI to drag the padding on the sides, this way we could achieve more complex layouts, for example:

![screen shot 2018-11-14 at 22 05 00](https://user-images.githubusercontent.com/8373980/48520857-617b3d00-e859-11e8-8d07-53bfec271aa7.png)

With this component we could add paddings to the images and the text, making it look way better, we could even add the image inside a padding plugin and the text inside another padding plugin to have different sizes in there, making it a plugin instead of a property on other component allow us to add paddings to anything.

The only thing is how we'd customize these paddings on mobile views, I think that we could add some fields (maybe add these to the spacer too), that'd allow us to set a different value to different screens.

![screen shot 2018-11-14 at 22 08 23](https://user-images.githubusercontent.com/8373980/48521009-ef572800-e859-11e8-83d1-571a2729086e.png)

Let me know if you have any feedback, I'm planning on working on it and sending a PR when I get some time to build it, nice work so far, I'm using it on an app that allows non profits to create donation pages.

**Comment by aeneasr** [comment]
> The only thing is how we'd customize these paddings on mobile views, I think that we could add some fields (maybe add these to the spacer too), that'd allow us to set a different value to different screens.

This is the biggest challenge. IMO, design padding should always be done in CSS and defined by ui folks and implemented by dev, not by the authors that create the content because they will mess up at some point. devs too, but they have a QA and test pipeline to go through.

**Comment by davidfurlong** [comment]
Yes - but certain use cases want end uses to control the theme/design.

I think a better change may be making the background plugin a 'container' plugin and then allowing padding/background/parallax as options on it

**Comment by PeterKottas** [comment]
#806 seems to be an iteration of this. I personally like the general idea of padding being included. I think given there was no update here, I'll close this for now. We can either continue on that other issue or reopen if there is some new stuff here.
