### ISSUE TITLE
Placeholder text overflow when align to right

### ISSUE THREAD

**Issue by kevinlaw91** [react-page/react-page#625]
Without entering any text, while empty, aligning to right will cause placeholder text to overflow
![capture](https://user-images.githubusercontent.com/4179182/49375117-5cb1f680-f73e-11e8-8147-37763e7bbc94.PNG)

**Comment by davidfurlong** [comment]
Yep seems like a bug, I've experienced this one before as well

**Comment by Z-web747** [comment]
对对对对对对

**Comment by PeterKottas** [comment]
This doesn't seem to be happening on the current version.
