### ISSUE TITLE
Add Source maps

### ISSUE THREAD

**Issue by PeterKottas** [react-page/react-page#627]
Hi @aeneasr , working on editor once again after a while. I was wondering if source maps work for you in the demo tool-chain. I am working on updating dependencies plus some performance fixes and not having source maps is rly annoying.

Ty

**Comment by aeneasr** [comment]
I'll have to check, they definitely worked at some point but the toolchain is (as you know) a bit messy.

**Comment by PeterKottas** [comment]
Thanks man, I've tried for a bit but no luck so far.
