### ISSUE TITLE
Why peerDependencies for your Toolbar components and others in your ory-editor-ui package

### ISSUE THREAD

**Issue by Metrakit** [react-page/react-page#636]
Hi,

I'm fighting for a while to follow your guide here : https://ory.gitbooks.io/editor/content/tutorials.html#reactjs-example then I understood that i need to install the peerDependencies listed here : https://github.com/aeneasr/ory-editor/blob/master/packages/ui/package.json for can compile my app. Why you put this required librairies (for use the component Toolbar and some others from your package) in the peerDependencies instead dependencies ? These components cant be compiled without theses required dependencies.. Or maybe I have missed a step ?

**Comment by davidfurlong** [comment]
I think thats how peer dependencies work, please read up about them. Sorry we don't have the capacity to address this
