### ISSUE TITLE
Problem with react-tap-event-plugin

### ISSUE THREAD

**Issue by matfire** [react-page/react-page#647]
Hi,

following the react js tutorial, after installing all the dependencies required (MUI etc.) I run the project one last time and I get an error coming from react-tap-event-plugin. I am using the latest version of react (16.8.1) and I read that react-tap-event is no longer supported. Any idea on how I might get this package to work nonetheless?

**Comment by BatuhanW** [comment]
I had the same issue, I completely removed `react-tap-even-plugin` and update MUI to alpha release. It somewhat works but not ready for production I guess. @aeneasr If you can point where we should do changes to drop `react-tap-event` dependency, I'd like to send a PR, work on this issue.

Wanted to know if you are cool with these?
- Drop react-tap-event-plugin dependency
- Upgrade MUI to latest alpha release

This way ory editor would have latest React version compatibility.

**Comment by Patrick-Spiegel** [comment]
Is this issue about this? 
![image](https://user-images.githubusercontent.com/35311793/52955992-5b33ba00-338e-11e9-9a58-42d463f9bb1f.png)

**Comment by matfire** [comment]
Yes

**Comment by souzaramon** [comment]
Any updates about this issue?

**Comment by arimus** [comment]
Some guidance as to the correct way to solve this for now would be great. The @react-page/core package specifies:

```
  "peerDependencies": {
    "react": "^16.8.6",
    "react-dom": "^16.8.6"
  },
```

However, these newer versions don't play nice with react-tap-event-plugin (support is only through react 16.4.x), but that is required and specifically included in the documentation. So either we should have deps at a lower react version (if that works) or something else needs to be adjusted. Not 100% on what though.

Can we please get an official fix or workaround documented by someone that works on the project and has a good idea of how to resolve this? Pretty please :D

**Comment by macrozone** [comment]
I did not notice any problem with that. Just don't install react-tap-even-plugin. I will remove it from the documentation, its no longer used or supported
