### ISSUE TITLE
IME input is interrupted when typing

### ISSUE THREAD

**Issue by tranvansang** [react-page/react-page#649]
The editor frequently interrupts IME input and prevents the text to be converted.

I guest that the automatic saving feature causes this bug. Is there any work around? Otherwise, I have to go with another options (rather than ory).

This is screen capture
![chrome-capture2](https://user-images.githubusercontent.com/13043196/53286418-7ef16880-37b1-11e9-856a-4e4b33e2d907.gif)

This screenshot of what should happen.
![chrome-capture 1](https://user-images.githubusercontent.com/13043196/53286371-d8a56300-37b0-11e9-866e-874808ab24d4.gif)

**Comment by davidfurlong** [comment]
Thanks for contributing your detailed report. I don't think there is a "I guest that the automatic saving feature" and we are happy to accept PRs to fix this issue. It looks a lot like a common React pattern issue where cursor positions are lost on controlled inputs.

**Comment by macrozone** [comment]
@tranvansang which browser is affected?

**Comment by tranvansang** [comment]
Chrome latest version at the time of submitting the issue, in unbuntu 18.04

**Comment by macrozone** [comment]
@tranvansang sorry for the late responsed.  The current beta v0.17.0-beta.8 incudes a major update from slate, which is responsible for the text-editing. It probably has fixed your issue, so it would be cool if you could try it out and give us feedback here! thank you!
