### ISSUE TITLE
Push new versions to npm 

### ISSUE THREAD

**Issue by tonynguyen88** [react-page/react-page#650]
Just a reminder to publish the new versions to npm, currently the latest version available is 0.6.0 while we're on 0.6.2 here on Github.

**Comment by fernandobandeira** [comment]
@aeneasr should be able to release a new version now that the tests are passing.

**Comment by isvaljek** [comment]
Will there be an update? Is it viable to use this git repo as an external dependency using npm-link? Or is there a better way to stay up to date with this lib?

**Comment by davidfurlong** [comment]
I will look to publish a new version soon
