### ISSUE TITLE
Extend editor - add another ory-controls-mode-toggle-control button (settings)

### ISSUE THREAD

**Issue by isvaljek** [react-page/react-page#661]
I've added another Toolbar (ToolbarSettings), and an another button to DisplayModeToggle. 
I'm tying to create settings section for this project, but I'm not sure whether we can use the RootState.settings for the storage part or is it advisable to create a separate store on the App level, above the Editor level? In that case I'm having problem passing down store actions to ToolbarSettings.

**Comment by macrozone** [comment]
@isvaljek can you show an example how that could look like and what settings you want to control with that? If its something that is worth to support directly in react-page, we can think about how to hook it into the editor.

if its something for your app specifically, i would just create another store. In general, i would treat the react-page store as an implementation detail. This makes it easier for us to adjust it to our needs. At some point we might lazy load and initialize the store only when we really need it (in edit mode) to reduce the bundle size more

**Comment by Fivedark** [comment]
We have simular requirements: We need to add another DisplayModeToggle button to open a toolbar (like insert mode) with inputs for a version name and a comment field and a save button. 

How is it possible to add another mode state to toggle this extra button?

**Comment by Fivedark** [comment]
Is there really no solution to add a new display mode?

**Comment by macrozone** [comment]
@Fivedark you could just do it outside of react-page

**Comment by Fivedark** [comment]
Is this the way to go?

ToggleSave-Button:
```
import React, { FunctionComponent } from 'react';
import { connect } from 'react-redux';
import ContentSave from '@material-ui/icons/Save';
import Button from '@react-page/ui/lib/DisplayModeToggle/Button';
import { RootState } from '@react-page/core';
import { createStructuredSelector } from 'reselect';
import { SET_DISPLAY_MODE } from '@react-page/core/lib/actions/display';

interface InnerReduxProps {
  isSaveMode?: boolean;
}

interface InnerActionProps {
  saveMode?: React.MouseEventHandler<HTMLElement>;
}

interface OwnProps {
  label: string;
}

type InnerProps = InnerReduxProps & InnerActionProps & OwnProps;

const DISPLAY_MODE_SAVING = 'saving';

export const isSaveMode = ({
  reactPage: {
    display: { mode },
  },
}: RootState): boolean => mode === DISPLAY_MODE_SAVING;

const saveMode = () => ({
  type: SET_DISPLAY_MODE,
  ts: new Date(),
  mode: DISPLAY_MODE_SAVING,
  remember: false,
});

const Inner: FunctionComponent<InnerProps> = props => (
  <Button
    icon={<ContentSave />}
    description={props.label}
    active={props.isSaveMode}
    onClick={props.saveMode}
  />
);

const mapStateToProps = createStructuredSelector<RootState, typeof isSaveMode>({
  isSaveMode,
});
const mapDispatchToProps = { saveMode };

export default connect(
  mapStateToProps,
  mapDispatchToProps,
)(Inner);

```

**Comment by macrozone** [comment]
@Fivedark sorry for the late response.

I would strongly suggest to do it outside of react-page.  For example, we have just a sticky toolbar at the end:

<img width="1318" alt="Bildschirmfoto 2020-01-28 um 15 02 15" src="https://user-images.githubusercontent.com/1972353/73270780-ac277180-41df-11ea-8905-8bca62b363f1.png">
 
(sorry for cencoring)

**Comment by Fivedark** [comment]
Ok, thanks. You can close this issue.

**Comment by macrozone** [comment]
@Fivedark 👍
