### ISSUE TITLE
Request to become maintainer

### ISSUE THREAD

**Issue by fernandobandeira** [react-page/react-page#662]
Hello @aeneasr,

I've seen that you've been busy lately and since me and my team are using this library quite a lot I'd like to help you maintaining it, reviewing some PR's with bug fixes, issues, release patches and so on, let me know if you're okay with that.

**Comment by aeneasr** [comment]
Hi @fernandobandeira ! Thank you for becoming involved here. I definitely do not have time any more to maintain this project and thought about archiving it soon. I don't feel comfortable with running a repo under my username via other maintainers but I would be open to update the readme with a link to your maintained fork. What do you think about that?

**Comment by fernandobandeira** [comment]
Sure, I'll start a fork this week, push some fixes and ping you with the link then, if you want to dearchive it later we can just PR back into your repo then =)

**Comment by macrozone** [comment]
hi! i just stumbled across this repo and i think its awesome!

@aeneasr, @fernandobandeira 

~7500 Stars is quite an achievement. Maybe its better to [transfer](https://help.github.com/en/articles/transferring-a-repository) the repo to a new organisation and keep the stars? I think if you just link to a fork, it might lose some momentum.

**Comment by aeneasr** [comment]
No, this repository will not be transferred to another org unless I know the maintainers personally for a long period of time. This healthy scepticism is based on the recent [event-stream incident](https://blog.npmjs.org/post/180565383195/details-about-the-event-stream-incident).

**Comment by macrozone** [comment]
@aeneasr the npm-publish problem is another topic where your sceptism is justified.

What about creating an organisation on github for the editor (ory-editor) and transfer the repo there so that your username no longer appears?

It would just be sad if the repo would lose momentum.

**Comment by davidfurlong** [comment]
> No, this repository will not be transferred to another org unless I know the maintainers personally for a long period of time. This healthy scepticism is based on the recent [event-stream incident](https://blog.npmjs.org/post/180565383195/details-about-the-event-stream-incident).

We're considering forking as well, but likely with the added intention to move away from `material-ui` as we don't use it internally

A suggestion: its possible to transfer the github/give maintainer to repository without transferring the `npm publish` rights, hence reducing the risks of a malicious takeover of an npm package

**Comment by macrozone** [comment]
> > No, this repository will not be transferred to another org unless I know the maintainers personally for a long period of time. This healthy scepticism is based on the recent [event-stream incident](https://blog.npmjs.org/post/180565383195/details-about-the-event-stream-incident).
> 
> We've decided to fork and we have some urgency on our side so we have decided to just go for it: https://github.com/DeedMob/ory-editor
> 
> We do want to decrease fragmentation of the community around this library, as that will make the death of it more likely, so we want to collaborate around a fork ideally rather than maintain it by ourselves.

what about moving it to a comunity-organisation? something like https://github.com/ory-editor-community/ory-editor 

that would make it more clear, that this would be the "official" repo and we could try to get more contributors on it (my team would also like to contribute).

(We might also consider rebranding to something neutral, as ory is a company and they no longer support it.)

**Comment by aeneasr** [comment]
Moving it to a community-org with a new npm package is something worth discussing IMO. I'm also happy to rebrand it (open for suggestions). I'd also definitely spend time to do community/maintainership management (wrt maintainership etc) to keep things flowing.

**Comment by davidfurlong** [comment]
We're happy to do whatever is best for the survival of this library - our main priorities are improving the editing user experience (Spacers are buggy and slow to use, improvements to modes UX, Editing render differs from displayed render). 

We are also to in the future potentially decouple / remove material-ui as using this library without using material-ui in your main project (as we do) is not the best developer experience and adds a big package size

**Comment by aeneasr** [comment]
Cool! Ok, as next steps I'd:

1. Move this repo to a new org (e.g. editor-community - please add your name suggestions)
2. Rename this repo to the new name (e.g. editor)
3. Set up a CI pipeline under a new npm org
4. Figure out a process to name maintainers and also a way to have discussions about how the package(s) should move forward as each company/contributor has probably a different idea/vision.
5. Add maintainers to the repo
6. ???
7. profit :D

What do you think about that? Please add your suggestions for (1), (2) and (4).

**Comment by macrozone** [comment]
ok will also brainstorm about a name ;-)

thank you @aeneasr (hackerman) for everything!

**Comment by davidfurlong** [comment]
I will brainstorm names too (1 & 2) - I would suggest a three party coalition for 4 (@macrozone, @fernandobandeira, @davidfurlong)

**Comment by davidfurlong** [comment]
I suggest `react-pages` - I think a declarative name would be useful, and the that name is the most package relevant one that I could find which was available on npm

**Comment by macrozone** [comment]
> I suggest `react-pages` - I think a self descriptive name would be useful, and that name is the most package relevant one that I could find which was available on npm

simple, yet descriptive. I like

**Comment by aeneasr** [comment]
Yeah that's awesome! And what about the org name?

**Comment by aeneasr** [comment]
Or what about `react-editable`?

**Comment by macrozone** [comment]
> Yeah that's awesome! And what about the org name?

probably just react-pages and then just 

react-pages/react-pages

;-)

**Comment by macrozone** [comment]
> Or what about `react-editable`?

i think that makes people think of content editable. I think the ory-editor or "react-pages" is more than that ;-)

**Comment by macrozone** [comment]
I asked my collegues for a name and i just got the mandatory "Editor McEditorFace" ;-)

**Comment by aeneasr** [comment]
https://github.com/react-pages is already taken unfortunately

**Comment by fernandobandeira** [comment]
Maybe `react-pages-community/react-pages` then? Great idea btw. 😄

**Comment by kfern** [comment]
My two cents: react-easy-editor

**Comment by RrredHead** [comment]
@fernandobandeira @macrozone @davidfurlong @aeneasr 
Do you have some progress?

**Comment by davidfurlong** [comment]
I got a bit tired of waiting for anyone else to do it so I made a start.
https://github.com/react-pages-community/react-pages

I ran into this issue:
@react-pages/core (npm organization scoped packages) had slashes that seemed to cause issues with imports such as `@react-pages/core/lib/content` (where the slash is treated as a file system slash)
and if we do the package names without an organization scoped package `react-pages-core` is taken, but the other package names aren't. If we could fix the prior that would be ideal. Haven't sent out invites to other people as I was waiting for setup to complete/work but I probably need consensus to either change the `core` package name to something else (engine?) / or help on the previous issue (google didn't seem to have much on this)

**Comment by aeneasr** [comment]
I think that should work with lerna or maybe aliases

**Comment by macrozone** [comment]
@davidfurlong thx for making the first step!

i am on hold atm, will use the package soon.

Scoped packages should work without lerna. What is the error that you are getting?

**Comment by davidfurlong** [comment]
well it seemed to be resolving `@react-pages/core/lib/content` to "in package "@react-pages" find file path "core/lib/content" within it rather than "@react-pages/core" package "lib/content" path within it. I'm still familiarising myself with lerna so I don't know whether this is a lerna feature or to do with the typescript resolver. I know we can probably alias typescript imports to fix this behaviour but that is probably bypassing the root issue. I think the specific error message was along the lines of 'file not found at path ....'

**Comment by macrozone** [comment]
@davidfurlong maybe this helps: https://github.com/Microsoft/TypeScript/issues/27126 ?

**Comment by davidfurlong** [comment]
> @davidfurlong maybe this helps: [Microsoft/TypeScript#27126](https://github.com/Microsoft/TypeScript/issues/27126) ?

It seems module resolution is already set to node in https://github.com/aeneasr/ory-editor/blob/master/packages/tsconfig.settings.json

**Comment by agustin107** [comment]
Finally this repo didn't move. Just was forked :/

**Comment by fernandobandeira** [comment]
I've released a version of my fork since I needed the video fixes, but I'll remove it after react-pages-community is properly setup.

@davidfurlong feel free to invite me and @DouglasGabr if you need help setting up it...

**Comment by aeneasr** [comment]
Hey! Sorry for my absence - I'd be moving it now! Even though `react-pages-community` has already been established, how about using the singular `react-page` instead? It's free (well actually I've registered it already :) )

**Comment by aeneasr** [comment]
https://github.com/react-page

**Comment by fernandobandeira** [comment]
@aeneasr sure, agreed, and the name is great too.

**Comment by aeneasr** [comment]
It's done - I've invited @davidfurlong and @fernandobandeira to it as collaborators with write permission. I will be available and responsive to all maintainers via discord ( https://www.ory.sh/chat ) via PN :)

We can discuss access to the npm org react-page there as well :)

**Comment by aeneasr** [comment]
If anyone else wants write permission let me know in this issue - it will obviously need approval of all maintainers :)

**Comment by fernandobandeira** [comment]
@aeneasr I think we just need to give permission to travis to build the repo, apart from that we should be good to go.

**Comment by agustin107** [comment]
I wanna be part as a collaborator if they want 👍

**Comment by aeneasr** [comment]
Great to see that you're interested! I think that it would be important for collaborators to have a footprint in the repository before adding write permissions. I think it is important to the community to show (a) a good understanding of the project by making excellent contributions (b) a commitment with longevity.

I've also added @PeterKottas to the maintainers as he has done an excellent job in past PRs!

**Comment by aeneasr** [comment]
Ok so I've set up a new npm account with access to `@react-page`. Travis CI is also set up (with that account) so new release *should* be published properly once all the package.json's are updated! While I'll still be monitoring this issue, I think we can close it now :)

**Comment by macrozone** [comment]
hey @aeneasr thank you so much for everything! hope i can also contribute when i can start my next big project which will use react-page heavily

**Comment by PeterKottas** [comment]
Nice one @aeneasr, we are using ory-editor heavily in our main product now and so far been reasonably happy. There's a bunch of things I want to fix/improve/add in the future though so this will definitely help make this smoother. I'll obviously be happy to further discuss any bigger changes. I can say right away though that I problably won't have much time to look at PRs from other contributors. At some point as we'll grow, I'll be happy to have somebody from my team set up some time to look into this.

**Comment by aeneasr** [comment]
That's great to hear and totally acceptable with not being a full-time reviewer. I think it would be great to have your brains behind this and your participation in discussions about future architectures and so on. Cool to have you on board, you have significantly improved the project already! :)

**Comment by PeterKottas** [comment]
Thanks, man. As they say, I've stood on the shoulders of giants ;) I'll be sure to read up if there are any major PRs coming in.

**Comment by davidfurlong** [comment]
It seems we/I can't label issues/ triage them with my current access level. I'd like to respond to and organize things so that put the effort to contribute feedback/bugs/PRs get a response and that we organize issues

**Comment by aeneasr** [comment]
That is because you haven't accepted the invite yet.

**Comment by davidfurlong** [comment]
Ah yes it seems github sends an email (which got lost) and has no on site notification/UI on repo for this flow... thanks I got it now

**Comment by aeneasr** [comment]
Great! You’re cleaning out the repo - good. But please provide a reason for closing issues so its transparent to everyone!

**Comment by aeneasr** [comment]
cc @davidfurlong

**Comment by davidfurlong** [comment]
will do for non-obvious closed issues. But for instance the flowtype ones that are internal facing are fairly clear without explanation I think

**Comment by davidfurlong** [comment]
Unfortunately my team pivoted our product resulting in us no longer using ory-editor. I haven't been active on this project since this pivot, and therefore ask to lose all maintainer access. Best wishes to the project, and my apologies for this change

**Comment by macrozone** [comment]
@davidfurlong  sad to hear that. May i asked what you use instead?

I would like to get maintainer access and would also like to publish to npm if that is possible.

Who else is maintainer on the project (npm and git) ?

**Comment by aeneasr** [comment]
Thank you for your contributions so far @davidfurlong :)

@macrozone thank you for requesting to become a maintainer! Other maintainers are @PeterKottas and @fernandobandeira . Seeing that you've made a bunch of PRs I'd have no problem with adding you to the maintainerlist. However, I'd like to get at least one +1 from those two.

NPM is fully automated, so you only need access to git.

**Comment by macrozone** [comment]
@aeneasr thx! speaking about npm, is it possible to release pre-releases (with @next tag or @beta tag) ? 

I would like to let users test my bigger pull request which lazy loads/code splits controls to reduce bundle size, but i don't know how it behaves in different environments and would be cool to get feedback

**Comment by aeneasr** [comment]
Yes, the npm release simply uses the git tag

**Comment by davidfurlong** [comment]
@macrozone We're building a structured system which has different blocks which each take the entire width of the page and can be stacked on top of each other. Each block can have a certain type and the types are built around a purpose (like an image grid, title section, downloads section, ...) with an opinionated design.

**Comment by fernandobandeira** [comment]
Sure, it'd be great to have your help @macrozone, our team is still using the editor and will be relying more on it from now on so I'll be assigning some of our engineers to help maintain the project, the idea is to keep the project as generic as possible in a way that anyone can extend with plugins and it's own UI (even though we provide plugins and an UI by default for quick setup), I think this was one of the core concepts of the package so we'll keep heading in that direction, just fixing bugs that come up, improving the code and allowing more features to be built on top of it 😄.

**Comment by aeneasr** [comment]
@macrozone write access is all yours :)

**Comment by macrozone** [comment]
@aeneasr thanks for your trust!

**Comment by aeneasr** [comment]
Thank you for your existing and future contributions :)

**Comment by PeterKottas** [comment]
Just picking up on my "correspondence", sorry yo see you go @davidfurlong but at the same time, welcome @macrozone . Looking forward to seeing more of your work land in this great project.
