### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by xeptore** [react-page/react-page#665]
Hi. is there any RTL (right-to-left) support?

**Comment by xeptore** [comment]
auto detection?!
closing issue...

**Comment by xeptore** [comment]
what about ordered/unordered lists? their contents (inner `<p></p>` tags) get the `dir="rtl"` attribute, but it is useless unless their original `<ul>` / `<ol>` tags become _rtl_.

**Comment by davidfurlong** [comment]
PRs are welcome, but I don't think its a part of the short term roadmap/priorities

**Comment by macrozone** [comment]
@xeptore  https://github.com/react-page/react-page/pull/695 allow to customize the slate plugins and you could create custom plugins that render the attribute `dir="rtl"` to the html elements

**Comment by macrozone** [comment]
would be a good case for an example in the docs
