### ISSUE TITLE
Parallax background is gray on mobile safari (iOS) instead of including the image 

### ISSUE THREAD

**Issue by davidfurlong** [react-page/react-page#671]
Hard to debug as it doesn't occur on web safari (or with mobile view size debugging mode active)

**Comment by davidfurlong** [comment]
Was able to use the IOs simulator to detect the problem:
It's the `background-attachment: fixed`. Apparently it costs much for mobile browsers to render them and it harms a lot scrolling performance, so it was disabled by Apple on safari on IOs.
Looking for a solution to disable the fixed image effect, just on IOs.

**Comment by macrozone** [comment]
i close that for now!
