### ISSUE TITLE
TypeError: styles_1.createGenerateClassName is not a function

### ISSUE THREAD

**Issue by jairusd** [react-page/react-page#682]
getting error: `TypeError: styles_1.createGenerateClassName is not a function`

`ory-editor-ui/lib/ThemeProvider/index.js`
 ```
   72 | var index_1 = __importDefault(require("./DarkTheme/index"));
   73 | 
   74 | exports.darkTheme = index_1.default;
  > 75 | var generateClassName = styles_1.createGenerateClassName({
   76 |   productionPrefix: 'ory'
   77 | });
   78 | exports.themeOptions = {
```

```
import React from 'react'
import Editor, { Editable, createEmptyState } from 'ory-editor-core'
import image from 'ory-editor-plugins-image'
import 'ory-editor-plugins-image/lib/index.css'

const editable = createEmptyState()

const editor = new Editor({
  editables: [editable],
  plugins: {
    content: [image]
  },
})

function BaseEditor() {
  return (
    <Editable editor={editor} />
  )
}

export default BaseEditor

```

**Comment by andreastoermer** [comment]
This error happens in connection with material 4.x

Revert to 3.x and you can work again. I've got the same problem, before i revert my material version.

**Comment by agustin107** [comment]
Seem it was resolved.
If this didn't resolve, you can open a new issue with more information (`node version, package manager, etc.`).

Please close this issue @fernandobandeira @davidfurlong

**Comment by fernandobandeira** [comment]
@jairusd ping me if you're able to reproduce this with material 3.x
