### ISSUE TITLE
Version 0.7 by npm

### ISSUE THREAD

**Issue by andreastoermer** [react-page/react-page#684]
Hi,

I see, that you publish Version 0.7.0 and 0.7.1, but on npm I can only find the 0.6 version. Did you rename the package on npm too, and if yes, which is the new name?

**Comment by agustin107** [comment]
Hi, at the moment the new version with the new name isn't published.
I think this will available soon.
What is the status of this @davidfurlong ?

**Comment by davidfurlong** [comment]
@fernandobandeira ?

**Comment by fernandobandeira** [comment]
I've fixed the deployment process, version v0.7.6 is on npm now, will update the readme with the new package names.

**Comment by fernandobandeira** [comment]
@andreastoermer @agustin107 @davidfurlong 

Migration instructions with the new package names are available here:
https://github.com/react-page/react-page/blob/master/UPGRADE.md

I'll close this and we can keep track of the readme changes with task #680, this way new users will be using the newer packages.
