### ISSUE TITLE
Update the examples and installation instructions

### ISSUE THREAD

**Issue by fernandobandeira** [react-page/react-page#687]
We should update everything to the new library names, this way new users will be installing the new updated packages.

However, if we're updating the readme, we should mention at the top that this package used to be called ory-editor, giving an explanation that the name of the project as well as the maintainers were changed in case an existing user comes back to this repo looking for the ory-editor.

**Comment by alastairzotos** [comment]
Yes please. I'm having trouble making it work. It's throwing an error "createGenerateClassName is not a function'

**Comment by macrozone** [comment]
started it here: https://github.com/react-page/react-page/pull/694

**Comment by fernandobandeira** [comment]
Unfortunately we've had to remove the logo that @tebriz159 did, we can replace it with a new one in the future.

Readme is looking better now, we still have to update our examples and docs but it's a great starting point
