### ISSUE TITLE
Layouts cannot easily pass props down to their children

### ISSUE THREAD

**Issue by amerryma** [react-page/react-page#691]
**Is your feature request related to a problem? Please describe.**
I have a layout that allows you to add components inside it. I want the layout to act different depending on the components added, meaning the layout needs to know what components are underneath it.

**Describe the solution you'd like**
The layout plugin has the ability to either pass props down to each child component (1 level of depth). Any other solutions are good. For example, the structure would be like:

```
Editor
|- Layout
   |- Component
      |- Layout
         |- Component
```

**Describe alternatives you've considered**
Multiple nested editors (bad).
Cloning the children of the layout plugin, and add functions (can't get this to work).
Non component state architecture such as redux.

**Additional context**
The actual feature I want to support is a quiz builder. The quiz builder works like this: a layout plugin with a header and "finish" button. The middle of the layout is where "quiz questions" with various forms (multiple choice, short answer, etc) can be added, resized, moved around, etc. I want the layout button to be able to be enabled when all questions are answered, as well as drive the state for the answers themselves.

**Comment by macrozone** [comment]
@amerryma 

i would recommend to use the context api of react, which makes that very easy:

```
const QuizContext = React.createContext()
// your layout plugin mounts a context provider
// ...
<QuizContext value={someContext}>{children}</QuizContext>

// and your question-elements can pick it up:


const QuizQuestion = () => {
   const quizContext = useContext(QuizContext);
   return <...>
}
```

remember that you can add everything to the context, even functions.

**Comment by amerryma** [comment]
Hi @macrozone 

Thanks for the input!

I've played around with this idea and I like how it works. I'm currently attempting to create a hook to accomplish this for more generically.

**Comment by macrozone** [comment]
@amerryma nice! I close this for now, feel free to reopen or ask questions!
