### ISSUE TITLE
Cannot find module '@react-page/core'.ts

### ISSUE THREAD

**Issue by santoshgistto** [react-page/react-page#692]
**Describe the bug**
Cannot find module '@react-page/core'.ts

<img width="1440" alt="Screenshot 2019-07-11 at 12 38 32 AM" src="https://user-images.githubusercontent.com/12577046/60997426-68b90300-a374-11e9-955d-6a46177a9187.png">

**Comment by macrozone** [comment]
@santoshgistto how did you install react-pages? can you show us your package.json?

**Comment by santoshgistto** [comment]
@macrozone here is the dependencies 
`  "dependencies": {
    "@material-ui/core": "^3.9.2",
    "@material-ui/icons": "^3.0.2",
    "ory-editor": "^0.6.0",
    "ory-editor-plugins-image": "^0.6.0",
    "react": "^16.8.4",
    "react-dom": "^16.8.4",
    "react-jss": "^8.6.1",
    "react-scripts": "2.1.8",
    "react-tap-event-plugin": "^3.0.3"
  },`

**Comment by macrozone** [comment]
@santoshgistto ory-editor was renamed to  react-page, so you have to reinstall:

```
yarn remove ory-editor ory-editor-plugins-image
yarn add @react-page/react-page
``

**Comment by macrozone** [comment]
@santoshgistto is this solved for you?

**Comment by santoshgistto** [comment]
@macrozone  sorry for late response 
Not yet tried, i will try and update you 
seems react-sample needs to update https://ory.gitbooks.io/editor/content/tutorials.html#reactjs-example

**Comment by macrozone** [comment]
@santoshgistto yes, updating the docs and example is top prio for us now. sorry for that
