### ISSUE TITLE
Not working with material ui 4

### ISSUE THREAD

**Issue by andreastoermer** [react-page/react-page#693]
**Describe the bug**
getting error: TypeError: styles_1.createGenerateClassName is not a function

ory-editor-ui/lib/ThemeProvider/index.js

  72 | var index_1 = __importDefault(require("./DarkTheme/index"));
  73 | 
  74 | exports.darkTheme = index_1.default;
 > 75 | var generateClassName = styles_1.createGenerateClassName({
  76 |   productionPrefix: 'ory'
  77 | });
  78 | exports.themeOptions = {
import React from 'react'
import Editor, { Editable, createEmptyState } from 'ory-editor-core'
import image from 'ory-editor-plugins-image'
import 'ory-editor-plugins-image/lib/index.css'

const editable = createEmptyState()

const editor = new Editor({
  editables: [editable],
  plugins: {
    content: [image]
  },
})

function BaseEditor() {
  return (
    <Editable editor={editor} />
  )
}

export default BaseEditor

**To Reproduce**
1. Update material ui package to 4.x
2. Start application
3. Look at console output

**Expected behavior**
Works with material ui 4

**Desktop (please complete the following information):**
 - OS: every os
 - Browser every browser
 - Version every version

**Comment by Fivedark** [comment]
I can confirm this issue. We are not able to use the editor in our MaterialUI 4 based project.

**Comment by andreastoermer** [comment]
I tried to update it inside a fork of react-page, but only updating and fixed some deprecations did not work. It's more to do, than it sounds in the beginning.

**Comment by 7yp0** [comment]
I have the same problem here :(

**Comment by Fivedark** [comment]
I got it to work with MaterialUI 4. 

It was necessary to update also React to ^16.8 (required by MUI) and fix the breaking changes. A little bit tricky was the required linking of React and React-Dom in the package.json of examples. Otherwise you get an "Invalid Hook Call Warning" because of different React instances between the lib and the examples.

You can few my changes here: https://github.com/react-page/react-page/compare/master...teamshirtsde:master

if the contributors were interested, I'd open a PR.

**Comment by andreastoermer** [comment]
cool, you are my hero :D please make a pr, and @fernandobandeira please look over it

**Comment by macrozone** [comment]
i would like to merge https://github.com/react-page/react-page/pull/701 as soon as the pipeline suceeds and release as 0.8.0 as this is a breaking change.

i will also start  a 0.9.0-beta with my changes to the module system which enables lazy loading
