### ISSUE TITLE
lazy loading to reduce bundle size

### ISSUE THREAD

**Issue by macrozone** [react-page/react-page#698]
this is an alternative approach to https://github.com/react-page/react-page/issues/580, at least when it comes to bundle size.

I think it's good to have a default UI for the editor. Material-UI is solid for that. 

The Problem at the moment is, is that if you want to use react-page also to display the content statically (without editing functionality), it still bundles material-ui, controls, etc.

https://github.com/react-page/react-page/issues/580 suggests (as far as i understand), that we should change the plugin system in a way, that the developer imports both the Control and the static Renderer and a compose function that creates the plugins out of the two. Or you import only the static Renderer and an empty Control if you want to only use the html renderer. While this works and additionaly provides the ability to swap Controls and renderes, it is more complex for devs to set it up. Also if you want to have both Editor and StaticRenderer in your app, you still have to deal with code spliting and have to thing how you describe your plugin configuration in a DRY way. Also the current plugin structure would need more refactoring as it is a bit verbose and not super clean atm.

I therefore play around with a different approach of code-splitting with the soon-to-be-standard `import()` function. Here are my findings so far:

- using `import()` and `React.lazy` work sort-of out of the box in the current setup, but projects will still bundle the whole thing, because tsc compiles `import()` to `require()``
- solution is to ` "target": "es6"` with ` "module": "esNext"`, but this will output plain es6 to lib. This can only be consumed if your project-runtime supports transpiling of node_modules. 
- In `nextjs` this can be solved with https://github.com/martpie/next-transpile-modules, `meteor` also supports transpiling node_modules with a symlink-trick at the time of writing
- i did an experiment with the image-plugin and can confirm that it successfully code splits the controls! I will send a PR to show it and will do further experiments

So what i would suggest is:

- every Control or basically everything that is renderer conditionally (typically when readOnly is false) should be a `React.lazy(() => import("./path/to/control"))`-component 
- we need to add `<Suspense />` gate at some point or use react-loadable as an alternative
- To keep backward compatibility, we would keep the default es5 output in /lib for the time beeing, but additionally provide a /es output directory or publish additional packages with -es suffix. We could later swap the default, because es-npm packages will become the default in the future
- projects that would want to profit from code splitting would need to import these es-packages and would need to configure transpiling of these packages (e.g. with https://github.com/martpie/next-transpile-modules)

**Comment by macrozone** [comment]
ok, its even easier now!

- as written above, compile to target: es6 into folder lib-es
- add this to package.json: ` "module": "./lib-es/index.js",`

bam. works in webpack out-of-the-box, no https://github.com/martpie/next-transpile-modules, needed, no additional config. You get support for code-splitting out-of-the-box

I need to do additional tests, but i would push a pr that just adds this additional build-step, nothing else. On top of that, we can implement lazy loading

**Comment by macrozone** [comment]
with my open PRs i managed to reduce the bundle size in my nextjs app from 
394kb (gzip), 1.3MB (plain) to  205kb (gzip) / 762kb (plain) in the page bundle! This is nearly 50% (!), without losing any functionallity or changing the api of react-page!

**Comment by andreastoermer** [comment]
hmm ... the problem with 0.8.0 is, that i cannot use react-page anymore :(

I have a meteor appliction in the backend which don't use webpack or some bundler, so this feature don't work there and now i get error messages :(

**Comment by macrozone** [comment]
@andreastoermer

Will check with meteor. It should work, maybe without code-splitting out of the box. What is the error message?

Also i did not test the release yet, i had some problem on travis, so i hope i did not mess ir up

**Comment by andreastoermer** [comment]
Uncaught Error: Cannot find module './xhr-sync-worker.js'

it happen in node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js  
const syncWorkerFile = require.resolve ? require.resolve("./xhr-sync-worker.js") : null;

**Comment by macrozone** [comment]
I guess the error is on the client?

**Comment by andreastoermer** [comment]
yes it's a client only error, this application don't use server side rendering

**Comment by andreastoermer** [comment]
the difference seems to be, that now it required jsdom (which was not used before) and there seems to be some problem with it in meteor.

**Comment by macrozone** [comment]
@andreastoermer correct. this library uses a dom-parser to 

a) allow to paste html into the editor and parsing it (browser only)
b) to be able to deserialize content that contains html (browser and server on ssr)

all current browser have a dom-parser built-in, but on node, you need a library for that. This project used parse5, but that was not officially supported by slate. Also it was included on the client altough it was not needed there. This affected the bundle size.

We did the following change:

1.) replace parse5 with jsdom
2.) only load jsodm on the server. For that i used the "browser" field in package.json and that seems the be the problem in meteor, that it does not respect that field.  tbh. i tried different approaches, but could not make the tree-shaker to remove that dependency from the bundle. The browser field was the only solution that worked on webpack:

```
 "browser": {
    "jsdom": false
  }
```

I will try to find a solution for meteor.

**Comment by macrozone** [comment]
i track it here https://github.com/react-page/react-page/issues/708

**Comment by PeterKottas** [comment]
Looks good! Just a side note though, while this is definitely a great contribution and much-appreciated improvement, it doesn't replace #580 completely (not that it says it does). While with #580 the main focus was to allow controls and renderers to be replaceable (adding a nice side effect of making the bundle smaller), this pr is mainly focused on making the bundle smaller (by using lazy loading). What I am trying to say is we should probably get back to #580 at some point as it will definitely be useful for people out there. I am pretty sure you @macrozone understand this perfectly, I just want to make sure others who come here get this.

**Comment by macrozone** [comment]
> Looks good! Just a side note though, while this is definitely a great contribution and much-appreciated improvement, it doesn't replace #580 completely (not that it says it does). While with #580 the main focus was to allow controls and renderers to be replaceable (adding a nice side effect of making the bundle smaller), this pr is mainly focused on making the bundle smaller (by using lazy loading). What I am trying to say is we should probably get back to #580 at some point as it will definitely be useful for people out there. I am pretty sure you @macrozone understand this perfectly, I just want to make sure others who come here get this.

exactly,

I currently create plugins my project where i am using react-page and will add more improvements there as well
