### ISSUE TITLE
version 0.8.0 not working with meteor

### ISSUE THREAD

**Issue by macrozone** [react-page/react-page#708]
continuation from https://github.com/react-page/react-page/issues/698#issuecomment-521611358

there seems to be a solution for that:

https://github.com/meteor/meteor/issues/6890

**Comment by andreastoermer** [comment]
I tried to fix it with adding the browser information directly in the package.json of the application, but it doesn't help

`{
    "name": "test",
    "private": true,
    "scripts": {
        "start:local": "cross-env NODE_OPTIONS=--max_old_space_size=8192 MONGO_URL=mongodb://localhost:32152/mugiwara API_TYPE=local meteor --port 3000",
        "test": "meteor test --once --driver-package meteortesting:mocha",
        "test-app": "TEST_WATCH=1 meteor test --full-app --driver-package meteortesting:mocha",
        "visualize": "meteor --production --extra-packages bundle-visualizer",
        "code:prettier": "prettier --write \"src/**/*.ts\""
    },
    "dependencies": {
        "@babel/runtime": "7.5.5",
        "@fortawesome/fontawesome-svg-core": "1.2.21",
        "@fortawesome/free-solid-svg-icons": "5.10.1",
        "@fortawesome/react-fontawesome": "0.1.4",
        "@material-ui/core": "3.9.3",
        "@material-ui/icons": "3.0.2",
        "@material-ui/lab": "3.0.0-alpha.30",
        "@progress/kendo-data-query": "1.5.1",
        "@progress/kendo-react-dateinputs": "3.2.2",
        "@progress/kendo-react-dropdowns": "3.2.2",
        "@progress/kendo-react-grid": "3.2.2",
        "@progress/kendo-react-inputs": "3.2.2",
        "@progress/kendo-react-intl": "3.2.2",
        "@progress/kendo-react-layout": "3.2.2",
        "@progress/kendo-react-treeview": "3.2.2",
        "@progress/kendo-react-upload": "3.2.2",
        "@progress/kendo-theme-material": "3.1.0",
        "@react-page/react-page": "0.8.0",
        "canvas": "2.6.0",
        "classnames": "2.2.6",
        "lodash": "4.17.15",
        "meteor-node-stubs": "0.4.1",
        "moment": "2.24.0",
        "react": "16.9.0",
        "react-dom": "16.9.0",
        "react-google-login": "5.0.5",
        "react-jss": "8.6.1",
        "react-redux": "7.1.0",
        "react-router": "5.0.1",
        "react-router-dom": "5.0.1",
        "react-router-redux": "4.0.8",
        "react-youtube": "7.9.0",
        "redux": "4.0.4",
        "redux-logger": "3.0.6",
        "redux-thunk": "2.3.0",
        "uuid": "3.3.2"
    },
    "devDependencies": {
        "@types/classnames": "2.2.9",
        "@types/lodash": "4.14.136",
        "@types/meteor": "1.4.29",
        "@types/node": "12.7.2",
        "@types/prop-types": "15.7.1",
        "@types/react": "16.9.1",
        "@types/react-color": "3.0.1",
        "@types/react-dom": "16.8.5",
        "@types/react-redux": "7.1.1",
        "@types/react-router-dom": "4.3.4",
        "@types/react-router-redux": "5.0.18",
        "@types/redux-logger": "3.0.7",
        "@types/slate": "0.47.1",
        "@types/slate-react": "0.22.5",
        "@types/uuid": "3.4.5",
        "cross-env": "5.2.0",
        "prettier": "1.18.2",
        "tslint": "5.18.0"
    },
    "browser": {
        "jsdom": false
    },
    "meteor": {
        "mainModule": {
            "client": "src/client.tsx",
            "server": "src/server.tsx"
        },
        "testModule": "tests/main.js"
    }
}
`

**Comment by andreastoermer** [comment]
First view on 0.8.1-alpha.0:
Everything works in my meteor application :)

You are my hero :D

**Comment by macrozone** [comment]
@andreastoermer can you try version 0.8.1 ?

this should work in meteor, altough code splitting does not work out-of-the-box. While meteor supports code-splitting, it wont fetch the `module` entry point in the package.json, but the already transpiled `main` entry point. For backwards compatiblity, this still points to a es5 bundle where all `import()` functions are changed to `require()`. So meteor won't see the `import()` functions.

You will still profit from a smaller bundle size with this release, because parse5 is removed.

I am not sure about support of `module` in meteor. Best raise an issue there. You could also try to import everything from `/lib-es`. E.g. `import Editor from '@react-page/core/lib-es'` 

If you want to check what is included in your initial bundle, use

`meteor --extra-packages bundle-visualizer --production`
