### ISSUE TITLE
chore: can't release pre-release

### ISSUE THREAD

**Issue by macrozone** [react-page/react-page#709]
i am not sure if i do the release right. I tag the repo with a version number and travis will create a release. so far so good.

but travis seems to error when trying to modify the package.json of the meta package: https://travis-ci.org/react-page/react-page/builds/572334911

it seems this line in travis-deploy.sh:

`cat ./packages/meta/package.json | sed s/0.0.0/$(git describe --tag)/g  > ./packages/meta/package.json`

creates an invalid package.json. But when i try it locally, it seems to work. 

Is there a way to debug this, e.g. see the files in travis?

@aeneasr i think you know best how the deployment works, maybe you can help?

**Comment by macrozone** [comment]
weird, running it a second time seems to solve the problem...

**Comment by PeterKottas** [comment]
I believe this will be taken care of by #734 closing here as part of cleanup
