### ISSUE TITLE
add documentation about Server side rendering

### ISSUE THREAD

**Issue by macrozone** [react-page/react-page#715]
SSR works good now, but i found a little caveat: slate uses a keygenerator which might lead to missmatch in server and client. The problem and solution is described here: https://github.com/ianstormtaylor/slate/issues/870#issuecomment-411052223

With recent react you can do also this:

```
// useCustomSlateKeygen.js

import { useRef } from "react";
import { KeyUtils } from "slate";

export default (uniqueId) => {
  const ref = useRef(null);
  if (!ref.current || ref.current !== uniqueId) {
    let key = 0;
    const keygen = () => {
      key += 1;
      return uniqueId + key; 
    };

    KeyUtils.setGenerator(keygen);
    ref.current = uniqueId;
  }
};

```

and then you can use it right before HTMLRenderer:

```
import { HTMLRenderer } from "@react-page/renderer";
import useCustomKeygen from "./useCustomKeygen";

const Content = ({ style, className, contentUniqueId, content }) => {
  useCustomKeygen(contentUniqueId);

  return (
      <HTMLRenderer plugins={plugins} state={content} />
  );
};
```

We need a section in the docs that describe these tricks, but i am too lazy right now to write that, so i leave it here for reference ;-)

**Comment by PeterKottas** [comment]
Added the docs [here](https://react-page.github.io/react-page/#/server-side-rendering)
