### ISSUE TITLE
improve lerna setup

### ISSUE THREAD

**Issue by macrozone** [react-page/react-page#719]
It seems the current lerna setup is not very ideal:

- it is very slow to build
- it does not support semantic releases
- it does not support prereleases properly
- deployments sometimes fail
- locally it can go out of memory
- it is often not very deterministic, sometimes it works, sometimes not

I would be very glad if someone with good lerna experience could revisit and improve the whole setup

**Comment by macrozone** [comment]
ok, i can try that.

**Comment by PeterKottas** [comment]
Lerna is ****ed up a lot. I usually have to repeat every command a few times with fresh clone before it starts working properly. I wonder if #734 will help with this.

**Comment by macrozone** [comment]
@PeterKottas i fixed a problem in master where it would fail to create packages. 

the reason was actually the typescript compiler or better: its caching feature.

**Comment by PeterKottas** [comment]
Awesome! Great news then. Hope it will make it much easier to work with and improve dev experience. I think there were a bunch of people who wanted to contribute in the past but simply could start the project properly :D

**Comment by macrozone** [comment]
looks better now, but still a bit slow
