### ISSUE TITLE
list of plugins for 0.1

### ISSUE THREAD

**Issue by aeneasr** [react-page/react-page#72]
- [ ] upload (d'n'd) or link to one image - @Knorrke
- [ ] embed content from soundcloud, youtube, twitter, facebook - @Knorrke 
- [ ] modify text via slate - @inyono 
- [ ] latex blocks if not already solved by slate

**Comment by lvarayut** [comment]
Hi @arekkas, is there any way to upload an image from computer or drag and drop?

**Comment by arekkas** [comment]
Hey @lvarayut this is currently not supported out of the box, the main issue is that there is no back end for the editor, so you will need to implement that yourself at the moment. We might have something here in ~2-3 months though as it's required in another project.
