### ISSUE TITLE
firefox: weird cursor jumping with newest slate

### ISSUE THREAD

**Issue by macrozone** [react-page/react-page#720]
see https://github.com/react-page/react-page/pull/716#issuecomment-525826182

**Comment by macrozone** [comment]
well, that seems this regression: https://github.com/ianstormtaylor/slate/issues/2978

**Comment by macrozone** [comment]
@Fivedark I try to downgrade as mentioned in the issue above and will push an update soon

**Comment by macrozone** [comment]
@Fivedark version 0.10.0-beta.2 should solve it (should be released soon)

**Comment by Fivedark** [comment]
Thank you for the fixing it so fast.
