### ISSUE TITLE
0.11.0 broke trigger edit mode

### ISSUE THREAD

**Issue by fernandobandeira** [react-page/react-page#724]
**Describe the bug**
We can't display the editor as edit mode by default anymore

**To Reproduce**
```
componentWillMount () {
  editor.trigger.mode.edit()
}
```

Editor will throw the following errors:
```
Invariant Violation: Could not find "store" in the context of "Connect(DropTarget(M))". Either wrap the root component in a <Provider>, or pass a custom React context provider to <Provider> and the corresponding React context consumer to Connect(DropTarget(M)) in connect options.
```

```
TypeError: Cannot read property 'includes' of null
```

**Expected behavior**
It should allow us to programatically set the edit mode of the editor, if it's not needed / supported anymore, then it should be listed in the release description as a BC.

**Comment by fernandobandeira** [comment]
Closing for now. will send a fix or reopen with more feedback

**Comment by macrozone** [comment]
@fernandobandeira that is weird, as in the example it still uses `editor.trigger.mode.edit()` :-/
