### ISSUE TITLE
add semantic-release

### ISSUE THREAD

**Issue by macrozone** [react-page/react-page#734]
doing releases is still a lot of manual work, because you have to keep track of changes, in particular breaking changes.

adopting semantic release would make that much more easy. Would also be a good oportunity to switch to version 1.0.0

**Comment by macrozone** [comment]
@PeterKottas I will add that soon (just did it in another monorepo with multiple packages). I would use the default commit message convention (the angular convention) from semantic-release https://github.com/semantic-release/semantic-release

i think we will also bump to 1.0.0 then. We can still move fast then, we just have to annotate commits with BREAKING CHANGE then, this will bump the major version

**Comment by PeterKottas** [comment]
Sounds great, I am all for this. Could you write up some quick info on how it's done and possibly put it into the new docs? Just some simple instructions on how to release.

**Comment by macrozone** [comment]
@PeterKottas with semantic release, releases would happen automatically and a new version would be calculated based on `feat:` or `fix:` or similar commits

**Comment by PeterKottas** [comment]
So I assume feat would be minor, fix would be a patch, right? How would you do major just out of curiosity? Also what if multiple PRs depend on each other, would we have to combine in a separate branch and then PR against master in one big PR? What about committing straight to master? Would that trigger a release on each commit?

**Comment by macrozone** [comment]
@PeterKottas 

> So I assume feat would be minor, fix would be a patch, right? 

yes!

> How would you do major just out of curiosity?

a major bump is done when there is a BREAKING CHANGE. 

> Also what if multiple PRs depend on each other, would we have to combine in a separate branch and then PR against master in one big PR? 

never had this problem, but probably combining them would be better.

> What about committing straight to master? Would that trigger a release on each commit?

would be the same as if you merge a PR with a commit. you usually want to have 1 commit per PR anyway (rebase or squash multiple commits into one before merge). Having said that i want to disable push to master anyway

**Comment by macrozone** [comment]
we have now semantic release! i am testing it, that's why there might be some unesseary releases on npm ;-)
