### ISSUE TITLE
deprecate "native plugins" and re-implement?

### ISSUE THREAD

**Issue by macrozone** [react-page/react-page#738]
While working on the library, i see many extra apis around "native plugins", but personally, i don't understand fully what these do. I guess, it should allow to drag and drop OS-elements like files etc. into the editor. 

But in my opinion, this is not worth the extra apis around it. There are a lot of exceptions just for these plugins. Instead, it would be better if every plugin could monitor native drop events, no matter if layout or content plugin.

I also think it would be worth to unify layout and content-plugins and no longer distinct between the two, at least not for the editor-user, but that's a differenet topic

**Comment by PeterKottas** [comment]
Makes perfect sense, I think we can close here and continue on #777

**Comment by macrozone** [comment]
i am about to refactor a lot and native plugins will be removed. i will add a way so that normal plugins can hook into drag&drop.
