### ISSUE TITLE
Can't add more than one plugin in layout plugin

### ISSUE THREAD

**Issue by rboixaderg** [react-page/react-page#739]
Hi! I am trying to add more than one plugin inside layout plugin, and I can't, 
In another project I use the version 0.11.0 and I can add two or three plugin inside background plugin. 
In addition, in master branch when i install all dependences, it throw the following error:

`@react-page/plugins-spacer: src/Controls/SpacerDefaultControls.tsx(49,17): error TS2769: No overload matches this call.
@react-page/plugins-spacer:   Overload 1 of 2, '(props: TextFieldProps, context?: any): ReactElement<any, string | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<any, any, any>)>) | (new (props: any) => Component<...>)> | Component<...>', gave the following error.
@react-page/plugins-spacer:     Type '"white"' is not assignable to type '"primary" | "secondary"'.`

This error appear in 0.14.0-beta.11 tag too. To solved it I change color to primary.

I use the version 12.13.0 of node, and 6.12.0 of npm.

Thanks!

**Comment by macrozone** [comment]
@rboixaderg that is a type error, looks like originating from here https://github.com/react-page/react-page/blob/master/packages/plugins/content/spacer/src/Controls/SpacerDefaultControls.tsx#L49

do you have a different version of material-ui in your app?

also this plugin needs refactoring... will check

**Comment by macrozone** [comment]
@rboixaderg can you try 0.14.0-beta.12?

**Comment by rboixaderg** [comment]
Hi @macrozone!
In version 0.14.0-beta.12 material error is solved. Thanks! 

So, how can I do to add more than one plugin inside de layout plugin via drag and drop ?
To check editor I use example folder in this repo.  If I use custom layout I can add more plugins but only by code in `createInitialChildren` function, and I can't resize, move or delete them. Editor only allows resize, move or delete all layout plugin, with content plugin inside it.

Was there any change in layout plugins to lose last behaviour ?

Thanks!

**Comment by macrozone** [comment]
@rboixaderg I noticed that as well, but did not investigate. 

With createInitialChildren you can create a layout plugin that already has the plugins inside that you need, but adding new plugins should work as well. I'll keep you updated

**Comment by macrozone** [comment]
@rboixaderg ok, i found the bug. Release 0.14.0-beta.13 is baked right now and should be available in 10min to install

**Comment by rboixaderg** [comment]
Hi @macrozone, thanks!
Now I can add content plugins inside layout plugins. 
But you can resize those plugins? I can't resize content plugins inside layout plugin.

**Comment by macrozone** [comment]
@rboixaderg can confirm, observed the same. I try to debug. I think its not a new bug

**Comment by macrozone** [comment]
@rboixaderg it looks like an update to react-resizable fixed that. can you try 0.14.0-beta.14 ?

**Comment by rboixaderg** [comment]
@macrozone  I have check with last version ( 0.14.0-beta.15) and the behaviour is the same, sometimes the resize works but not always.

**Comment by macrozone** [comment]
@rboixaderg weird, ok, i will check. Maybe its an upstream issue: https://github.com/STRML/react-resizable

**Comment by rboixaderg** [comment]
Hi @macrozone I have check diferent versions, like 0.11.0, 0.11.4, 0.12.0 and the last version, it seems that the bug is an old bug.

**Comment by macrozone** [comment]
@rboixaderg if you want, you can checkout the repository, `yarn install`, then `yarn start` and try to debug it. I would be very glad.  i think its not that hard to find the error

i can look at it at the weekend i think

**Comment by macrozone** [comment]
@rboixaderg i did an improvement on the resizing some time ago, can you check again with the newest version?

**Comment by rboixaderg** [comment]
Hi! @macrozone Thanks! It seems that it working fine!
