### ISSUE TITLE
Exporting to HTML

### ISSUE THREAD

**Issue by bhavesh-pandey** [react-page/react-page#741]
Hi,

I need to export the content of editor to HTML format. Is there any inbuilt function to do, if no is there any plugin to do that?

I saw this issue https://github.com/react-page/react-page/issues/507 but the links given in that are giving 404.

Thanks

**Comment by bhavesh-pandey** [comment]
Or if not, is there any way to convert this serialised JSON to PDF or DOC?

**Comment by macrozone** [comment]
you can use ReactDomServer to render to a html string:

```
import { HTMLRenderer } from "@react-page/renderer";
import ReactDOMServer from 'react-dom/server';

const html String = ReactDOMServer.renderToString(<HTMLRenderer state={yourEditorState} plugins={yourPlugins} />)
````
