### ISSUE TITLE
ci / release push failed, altough it works

### ISSUE THREAD

**Issue by macrozone** [react-page/react-page#746]
travis always says that the push on a release failed, altough it gets successfully pushed to npm...

**Comment by fernandobandeira** [comment]
@macrozone I've commited a fix to the master branch, basically lerna tries to reset the repository after publishing the packages to achieve a clean state, but we aren't pushing so it can't really reset.

**Comment by macrozone** [comment]
@fernandobandeira thank you so much!

**Comment by macrozone** [comment]
@fernandobandeira deploy on travis still seem to be a bit unreliable, can you check if you see some problems?

**Comment by PeterKottas** [comment]
This has been a while ago, I am closing as it seems it's working now. Reopen if the issue prevails.
