### ISSUE TITLE
Support for s3 image uploads

### ISSUE THREAD

**Issue by bonbonio** [react-page/react-page#755]
Hello,

Is it possible to use this editor for the following;

h1-h6 styles, bold, italic and links buttons (Appears so)
Allowing images to be added, and aligned but the image should be uploaded to an s3 bucket as part of the saving process
If not, is there any other editors that work with ReactJS and could do this? My stack is NextJS + Material-UI + Hapi.

Many thanks... I did look through the history but nothing recent or relevant I managed to find - so I am hoping this can help point me in the right direction.

**Comment by macrozone** [comment]
hi!

yes this is possible,
there is a built-in image plugin that supports custom uploader or you can create your own plugins where you have no imits.

But i have to admit, the docs need improvement. The code however never lies, in the example you find a sample with a mock upload service: https://github.com/react-page/react-page/blob/master/examples/src/plugins.ts#L50

should be easy to implement an uploader to s3 there
