### ISSUE TITLE
update slate to 0.50

### ISSUE THREAD

**Issue by macrozone** [react-page/react-page#757]
slate 0.50 is out: https://github.com/ianstormtaylor/slate/blob/master/packages/slate-react/Changelog.md

https://docs.slatejs.org/concepts/xx-migrating

it requires some refactoring, but should be an intesting thing to do. We would profit from reduction in bundle size and complexity and probably also better performance

**Comment by PeterKottas** [comment]
Hey mate, this is a plugin that fully supports the latest slate, I didn't have time to contribute here as I need to move fast, however, it could be good for inspiration (even copy-paste).

**Comment by macrozone** [comment]
@PeterKottas ok, i will take a look at it
