### ISSUE TITLE
I can't Install the package

### ISSUE THREAD

**Issue by cvjude** [react-page/react-page#760]
**Describe the bug**
I can't add the editor using npm i @react-page

**To Reproduce**
1. run npm install --save @react-page

**Expected behavior**
The package should be installed and I should be able to edit it.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] windows 10

**Additional context**
This is the error I get when I try to install

npm ERR! code EINVALIDTAGNAME
npm ERR! Invalid tag name "@react-page": Tags may not have any characters that encodeURIComponent encodes.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jchinoso\AppData\Roaming\npm-cache\_logs\2019-12-24T09_50_45_082Z-debug.log

**Comment by macrozone** [comment]
@cvjude hi!

wow, sorry, there is a typo in the quickstart!

it should be `npm i @react-page/react-page`

hope this helps! merry xmas!

**Comment by cvjude** [comment]
OK thanks, It works very well. Happy new year to you.
