### ISSUE TITLE
No longer able to provide react-dnd backend

### ISSUE THREAD

**Issue by PeterKottas** [react-page/react-page#761]
Hey, @macrozone and happy new year! I was doing some tests on mobile and after some digging I realized that as part of upgrading react-dnd, you got rid of the react-dnd backend injection api. https://github.com/react-page/react-page/commit/ceaecc192f0751a32793ccb5fe387ce1bee5ad0a#diff-55646d75364ce42cdb84abec1a1531ccL122
I was curious if you could shed some light on this, I assume it was something that changed with the latest version, however, I don't think it should be just removed. This was for instance discussed here before, https://github.com/react-page/react-page/issues/424 but after this change, it no longer works. I think we should discuss how to bring this back, hope there's no major reason why it was removed.

**Comment by macrozone** [comment]
@PeterKottas the goal was to be able to have independent editor instances, so that they can co-exist. Therefore every editor has its own context with redux and dnd-backend. This was not possible in earlier versions of react-dnd as it lead to this error: https://github.com/react-page/react-page/issues/424

Passing your own dnd-backend is no longer needed. But maybe you have a usecase for it?

**Comment by PeterKottas** [comment]
Ok I see, that makes sense. However, the issue remains as folks (including me) might want to on some occasions replace the default backend with touch backend. https://react-dnd.github.io/react-dnd/docs/backends/touch . As it stands now, it doesn't work on mobile at all.

**Comment by macrozone** [comment]
@PeterKottas i think we can either add a mobileSupport flag and provide a touch backend or we could allow to pass one. Because there are only these twos, it might be better to enable touch support ourself

**Comment by PeterKottas** [comment]
Not a good idea to go with the flag. Imagine one day, somebody comes up with a new (better) touch backend. Or entirely new backend for some specific hardware (iot/wearables ... who knows). Better have an api to provide backend from outside with reasonable default (as it was before). Because otherwise, sometime along the way, somebody will have to deal with this again.

**Comment by macrozone** [comment]
@PeterKottas i think that‘s a YAGNI ;) better they would file an issue that they need support for an editor on their wearable and we could find a proper solution to fullfill this request. I think the backend stuff of react-dnd is such an implementation detail that i would not want to expose this to the api surface of react-page. I think the same about redux. They should stay internal. 

On the other hand, just passing a a touch backend to the provider would also be easy, but i would avoid it

**Comment by PeterKottas** [comment]
I have to disagree here, also there already was this discussion and it was decided that it should be injectable. Another good example is testing, react-dnd offers a test backend, https://react-dnd.github.io/react-dnd/docs/backends/test once again, supporting this via flags seems unnecessarily complex where it's definitely an easy solution to just inject it on "use it if you need it" basis. It just seems like a more extendable and straight forward solution. Also, we wouldn't have to maintain/update dependencies for various backends from flags.

**Comment by macrozone** [comment]
@PeterKottas ok for me. Can you send in a PR? should be easy to add it

**Comment by PeterKottas** [comment]
Sounds good, I'll get to this once we revisit mobile in the next iteration. Quick question, how do you trigger release? Is it automatic? do you just need to push a new patch to GitHub? Cheers!

**Comment by macrozone** [comment]
@PeterKottas release is triggered manually through setting a tag. need to migrate that to semantic release though ;-)

**Comment by macrozone** [comment]
@PeterKottas I will open a PR with the changes. You will now be able to pass `dndBackend` to:

- `<Editable />`
- `<EditorUi />`

and also to the new umbrella component

`<Editor />`

**Comment by PeterKottas** [comment]
Ah, I see about the release, good to know, thanks! You actually did it! Awesome, I left a small comment on the PR and it's good to go then. Thanks
