### ISSUE TITLE
Unable to Install

### ISSUE THREAD

**Issue by Hellboyksr2** [react-page/react-page#770]
Unable to Install React Page using npm i @react-page/react-page

throwing the following error :

npm ERR! code E404
npm ERR! 404 Not Found: @react-page/plugins-default-native@v0.17.0-beta.8

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ksborra/.npm/_logs/2020-01-31T09_55_32_597Z-debug.log

**Comment by macrozone** [comment]
@Hellboyksr2 i'll check. there is a bug in the deployment, that sometimes does not publish some packages

**Comment by Hellboyksr2** [comment]
Nope, Seeing the same issue,
npm WARN ws@7.2.1 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.2.1 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN react-player@1.15.2 requires a peer of react@* but none is installed. You must install peer dependencies yourself.

npm ERR! code E404
npm ERR! 404 Not Found: @react-page/plugins-default-native@v0.17.0-beta.8

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ksborra/.npm/_logs/2020-02-03T09_36_25_269Z-debug.log

**Comment by Hellboyksr2** [comment]
@macrozone Now I am getting Following error

npm ERR! code E403
npm ERR! 403 Requested item is quarantined: @react-page/plugins-default-native@v0.17.0-beta.8

**Comment by macrozone** [comment]
@Hellboyksr2 it seems you using a proxy in your npmrc.

https://stackoverflow.com/questions/48270514/facing-requested-item-is-quarantined-sockjs0-3-18-while-doing-npm-install

**Comment by macrozone** [comment]
@Hellboyksr2 could you solve this problem?

**Comment by Hellboyksr2** [comment]
@macrozone Yup seems it was a proxy issue. Thanks for your quick help.
