### ISSUE TITLE
Change text color

### ISSUE THREAD

**Issue by brunomc** [react-page/react-page#773]
How to change color text?

It's possíble?

**Comment by macrozone** [comment]
sure! in the example there is a custom slate plugin that does that:

https://github.com/react-page/react-page/blob/master/examples/src/customSlatePlugin.tsx

**Comment by brunomc** [comment]
> sure! in the example there is a custom slate plugin that does that:
> 
> https://github.com/react-page/react-page/blob/master/examples/src/customSlatePlugin.tsx

Nice!

**Comment by macrozone** [comment]
@brunomc i close this for now, if you have any questions, please ask! 

we will update docs and examples soon to make it easier to get these information!
