### ISSUE TITLE
Modify width of BottomToolbar

### ISSUE THREAD

**Issue by rboixaderg** [react-page/react-page#775]
Hi @macrozone, It is possible to modify bottomToolbar width ( Min and Max ) by props? 

There is a className prop, but this prop only modify Drawer component, no?

Thanks!

**Comment by macrozone** [comment]
hi @rboixaderg ! 

theoretically, you could control that by passing a custom theme. But currently, ThemeProvider support is a bit messy.

Also BottomToolbar is an area for refactoring. I also want to discourage using the `BottomToolbar` directly. 

What is your exact usecase? which BottomToolbar do you want to change? Is it a custom plugin or all of them?

**Comment by rboixaderg** [comment]
It's for a custom add-on, I'm doing a carousel add-on and I need to customize the carousel items in the toolbar. Add a new item, edit properties, etc. And I would like increase toolbar min width

Thanks!

**Comment by PeterKottas** [comment]
I think we have a somewhat mixed approach/feelings about the UI package. While it's definitely useful for getting off the ground quickly, in my experience, it makes sense to maintain/implement this in your code, especially for bigger projects. For instance, for my company, we have https://github.com/guestbell/react-page-plugins which abstracts away some of these concerns and makes it reusable for our use cases (and probably our use-case only). I would like to see a future where this is not necessary, but at the time of writing, anything that comes to mind that would allow this kind of customization is an engineering nightmare and probably overkill. Especially when you take into consideration that every plugin effectively comes with its own UI. Although we somewhat fixed that by introducing some guidelines in separating the Rendering logic from the UI.

Maybe in the future, it would be best to go the react-table, abandoning the UI and simply exposing hooks and util functions that would make it very easy and predictable to create your own UI.

**Comment by rboixaderg** [comment]
Ok Thanks for the answer! For now I customize it in my own project.
