### ISSUE TITLE
Slate Placeholder missing

### ISSUE THREAD

**Issue by andreastoermer** [react-page/react-page#778]
**Describe the bug**
Yesterday I updated react page from 0.16 to the current 0.18 version. Everything works fine except for the thing that the placeholder "Write here..." for the slate plugin is missing. The problem is, that our editor don't know exactly where to click to edit the slate content.

**To Reproduce**
1. Use version 0.16
2. Open React Page in Browser and add a slate plugin
3. You see the "Write here ..." placeholder for the slate plugin
4. Change to current 0.18 version 
5. Go again to the react page page and add a slate plugin
6. Don't see the placeholder

**Expected behavior**
See the placeholder text

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chromium Edge
 - Version current

**Comment by macrozone** [comment]
@andreastoermer good catch, can confirm.

you could also try to set initial text content (what i usually do, thats why i proably missed that)
