### ISSUE TITLE
Video control missing

### ISSUE THREAD

**Issue by spelamourgues** [react-page/react-page#783]
**Missing controls on video tags**

**To Reproduce**
1. Go to 'Add things'
2. Add an url to a mp4 video (not youtube)
3. No controls appears

**Comment by PeterKottas** [comment]
This actually doesn't seem to be problem anymore. However, the video controls are broken. You cannot update the link. Seeing this has been there for a while, I assume not many people are using that plugin. A simple PR should fix that if anybody is interested.
