### ISSUE TITLE
Changing editor Value prop does not reflect

### ISSUE THREAD

**Issue by ashubham** [react-page/react-page#788]
https://github.com/react-page/react-page/blob/9c1feccbdc97d2cefeb99e9bdab2e9159f077884/packages/editor/src/editor/EditableEditor.tsx#L18

Due to the above line in code the useEffect is redefined everytime. This should be changed to:

```
[editorRef.current.editorState]);
```

**Comment by macrozone** [comment]
the line was meant that if you pass the referential equal value to the editor, it should not update.

with your change, the editor would never update as editorRef.current.editorState is always the same reference.

**Comment by ashubham** [comment]
if we see line 12 on the same component we see:
https://github.com/react-page/react-page/blob/9c1feccbdc97d2cefeb99e9bdab2e9159f077884/packages/editor/src/editor/EditableEditor.tsx#L12

Thus, if I pass a new `value` for the Editor Props, it does not update as the effectHook does not rerun. Because the condition mentioned originally will always return `true`.

**Comment by macrozone** [comment]
@ashubham oh, yes, you are absolutly right. I need to look into that. 

I just need to check if adding `[editorRef.current.editorState]` would lead to unneeded rerenders or not, namly if you use editor more "controlled" (with a `useState` or so).

**Comment by macrozone** [comment]
should be fixed in v0.19.0. (I need to test it in my own projects).

feel free to open
