### ISSUE TITLE
Adding Katex plugin

### ISSUE THREAD

**Issue by kss943** [react-page/react-page#789]
Hello.
Can somebody explain how  to add Katex to slate plugin in Editor component?

I found this sample of katex plugin but it work only in old version of ory-editor.
https://github.com/serlo/ory-editor-slate-katex

How to add it for latest version of react-page?

**Comment by macrozone** [comment]
@kss943 There is an example here https://github.com/react-page/react-page/blob/master/examples/src/customSlatePlugin.tsx

For katex, would look like  (i just wrote that down here, so it not might be 100% correct):


```
import { pluginFactories } from '@react-page/plugins-slate';
import React from 'react';
import { BlockMath } from 'react-katex'

import 'katex/dist/katex.min.css'

export default pluginFactories.createComponentPlugin<{
  color: string;
}>({
  addHoverButton: false,
  addToolbarButton: true,
  type: 'Katex',
  object: 'block',
  icon: <span>Katex</span>, // or add a fancy icon
  label: 'Katex',
  Component: props => {
    return <div>   <BlockMath math={props.formula} />
      {children}
</div>
  },
 schema: {
    type: 'object',
    required: ['formula'],
    properties: {
      formula: {
        type: 'string',
      },
    },
  },
});
```

**Comment by kss943** [comment]
Thanks for answer!
With your code it is possible to create math formula now.
But when i click at row with formula, error appear:

> Cannot resolve a Slate point from DOM point: [object Text],1
>     at Object.toSlatePoint (react-editor.ts:426)
>     at Object.toSlateRange (react-editor.ts:484)
>     at HTMLDocument.<anonymous> (editable.tsx:388)
>     at later (index.js:27)

I tried to edit component from your code like:
```
 Component: props => {
    return(  
      <p>
        <span data-slate-node="text">
          <span data-slate-leaf="true">   
            <BlockMath  math={props.formula} />
             {props.children}
          </span>
        </span>
      </p>
    ) 
```
But it did not help.
Maybe you have some ideas how to avoid error after clicking at row with formula in text plugin?

**Comment by macrozone** [comment]
@kss943 I remember this problem... something like this might help:

```

<div data-slate-void="true">   
   <BlockMath math={props.formula} />
      {children}
</div>
```

`data-slate-void="true"` catches some click and makes slate not threat it like a  simple text-block

**Comment by kss943** [comment]
@macrozone 
after wrapping it by `<div data-slate-void="true">`  clicking work.
But when you create formula without any text and click at it appear error:

`Error: Cannot resolve a DOM point from Slate point: {"path":[0,0,0],"offset":14}`

Also there is an error after adding more than 1 formula to same text plugin and deleting it(e.g. second formula did not vanish and then text is empty error above appear)

Do you have any idea how to handle it? Maybe it would be better to send to Editor component single plugin with Katex(furthermore, i did not find a way to make formula and text at one row)?

**Comment by macrozone** [comment]
@kss943 do you need the text content at all? What happens if you remove `children` ?

**Comment by kss943** [comment]
@macrozone 
Without children it also crash on click at formula:
```
TypeError: Cannot read property 'closest' of null

leafNode = voidNode.querySelector('[data-slate-leaf]')!
> 406 |   textNode = leafNode.closest('[data-slate-node="text"]')!
      | ^  407 |   domNode = leafNode
  408 |   offset = domNode.textContent!.length
  409 | }
```

**Comment by macrozone** [comment]
@kss943 would you mind send in a PR where you put this plugin as a new example slate plugin? Just push what you have and mark the PR as WIP. I think this would be a win-win, as i can check it out without hazle and we would end up with another nice example

**Comment by kss943** [comment]
@macrozone 
I created PR with katex plugin at examples folder.
I can show full code in my project if information in PR is not enough

**Comment by macrozone** [comment]
@kss943 i extended your PR https://github.com/react-page/react-page/pull/792 !

**Comment by kss943** [comment]
Hello @macrozone
Thanks for update! 
I tried to make everything as in you sample but when i click at formula icon error appear :
`props.useFocused is not a function`
props at Component argument of `pluginFactories.createComponentPlugin` have only `attributes` and `children ` objects

Code looks like this: 
```
...
const slatePlugin = slate(def => ({
  ...def,
  plugins: {
    ...def.plugins,
    customNamespace: {
      customPlugin: ktxPlugin <- plugin as in example
    }
  }
}))

const plugins = {
  content: [slatePlugin],
};


export const App = () => {
  const [editorValue, setEditorValue] = useState(contents[0]);
  const changeTemplate = (e) =>{
    setEditorValue(e)
  }
  return (
      <Editor plugins={plugins} value={editorValue} onChange={changeTemplate} />
  );
};
```

**Comment by macrozone** [comment]
this example needs other changes in the library, so please try it out first in the example project. I will then push a release with these changes

**Comment by kss943** [comment]
@macrozone 
I started an example project and found one error. 
When you create new text field and after that click on formula icon, this appear:

**packages/plugins/content/slate/lib-es/hooks/useAddPlugin.js:70**
```
TypeError: Cannot read property 'focus' of null

68 |   if (plugin.object === 'inline' && plugin.addExtraSpace) {
  69 |     Transforms.insertText(editor, ' ', {
> 70 |       at: editor.selection.focus
     | ^  71 |     });
  72 |   }
  73 | }
```
As I see, it appear with clicking on custom slate plugins when text field in some cases was created without focusing in it.

**Comment by macrozone** [comment]
ah ok will fix that.

can you try to select text and then click on the Σ button? this case should work, would be glad to hear your feedback for that!

**Comment by kss943** [comment]
@macrozone 
I think problem which i described above can be solved by opening modal for text editing only when text field has focus. 

While selecting text it usually works good. 
When you start to delete formula and achieve "\" appear text katex error as text string.

Also, it cover window with formula preview 
![q](https://user-images.githubusercontent.com/44510572/79365959-0cfb5600-7f54-11ea-9055-a26667dc1c6f.PNG)

**Comment by macrozone** [comment]
@kss943 yes, i noticed that too with the empty string. 

also the modal thing was intended, but somehow it does not work, will check that

**Comment by macrozone** [comment]
@kss943 pushed another change that show the dialog as intended. could not fix the problem with the empty string yet

**Comment by macrozone** [comment]
i added an example in v0.19.0! its one of many ways how to do that. Feel free to reopen if you have further questions
