### ISSUE TITLE
Restricting Rows/Columns

### ISSUE THREAD

**Issue by janus-reith** [react-page/react-page#794]
**Is your feature request related to a problem? Please describe.**
I have a custom content plugin, and if that is placed, I don't want the user to be able to add any other element besides it, i.e. it should take full width( While the actually rendered element doesn't necessarily take the full screen width).

**Describe the solution you'd like**
It should be possible to globablly disable putting things side by side, and only allow or deny it for some specific cells. In there, it should also be possible to further restrict how many elements can be nested and how.
**For now I'd be happy with a solution to just disable putting things side by side alltogether, so blocks can only be placed vertically.**

**Describe alternatives you've considered**
As MJML allows for an dynamic amount of columns I'm considering to not need such a restriction and just translate rows to mjml columns 1:1, however this won't work for an initial MVP I'm building which needs to be strict in order to work safely, also there would always be cases later on where layout blocks would have their own columns each and couldn't just be put side by side.
So, no real alternative yet that I'm aware of.

**Additional context**
As described in https://github.com/react-page/react-page/issues/786, I'm trying to build an mjml email builder based on react-page.
For that I'm recursively traversing the editor state, to generate MJML based on the plugin name and state defined in the `content` property of each cell.
In order for this to work properly, I have to set strict restrictions on which elements can work side by side or can be nested inside each other.

**Comment by macrozone** [comment]
@janus-reith have to think about that.

maybe we can add some proeprty to the Row's so that the can only contain one child

**Comment by janus-reith** [comment]
> @janus-reith have to think about that.
> 
Thank you :)

> maybe we can add some proeprty to the Row's so that the can only contain one child

@macrozone Would this work top-level aswell, or only inside a layout component?
This also made me wonder, does adding properties to rows and cells, similar to the state values used in content components, work in general?

**Comment by macrozone** [comment]
@janus-reith currently not, but it would actually make sense to unify layout plugins with rows or at least treat them similarly and make Rows customizable. It should definitly work toplevel as well in my opinion.

need more refactoring though, i would first like to unify layout plugins and content plugins more: https://github.com/react-page/react-page/issues/777

both define whats inside a Cell

**Comment by macrozone** [comment]
customizing Rows would also help to later make different rendererers for react-native or for https://github.com/react-page/react-page/issues/786

**Comment by janus-reith** [comment]
@macrozone I agree on these points, including that #777 should probably be done first.

Seems like a really flexible solution if it could work to have both Rows and Columns as both extendable but also replaceable components, where the default behaviour would be the same as now, and those components would just be created automatically when placing and dragging components, with that behaviour being customizable aswell (e.g. for the aforementioned constraints).
