### ISSUE TITLE
Stop scrollIntoView when click on a Cell

### ISSUE THREAD

**Issue by nhkhanh** [react-page/react-page#797]
Shall we stop scrollIntoView when click on a Cell in this line? https://github.com/react-page/react-page/blob/0e2d0339b907ebbf7616ae9ef504c6ee3d2bc1c4/packages/core/src/components/Cell/Content/index.tsx#L98
As in below image, When we want to edit at the bottom of very long paragraph, it scroll to the top. We have to scroll down again to see what we are typing. Furthermore, when we edit at the top of the paragraph, it scroll down a bit that we cannot see what we are typing.
![Apr-28-2020 14-24-38-480px-low-fps](https://user-images.githubusercontent.com/4928520/80459992-62c0fc80-895d-11ea-8ccd-f6d3c8758337.gif)

**Comment by macrozone** [comment]
@nhkhanh yes, its not ideal in most cases. there were some reasons to do it, but i not fully remember why i added it. Since we highlight selected cells now more prominently, its no longer usefull to sroll the page

**Comment by macrozone** [comment]
@nhkhanh will be fixed in v0.20.0. I only scroll to the cell now, when its newly added
