### ISSUE TITLE
react 16.13.1 warning context api

### ISSUE THREAD

**Issue by xavivzla** [react-page/react-page#798]
**Screenshots**
![image](https://user-images.githubusercontent.com/38009571/81308212-24a39700-9047-11ea-8674-d48fe8cfa953.png)

**Desktop (please complete the following information):**

 - Browser Chrome

**Comment by macrozone** [comment]
looks like this comes from `rc-tooltip", maybe we need to update that library

**Comment by xavivzla** [comment]
Thank you. I was following the implementation tutorial, but the buttons come out but it doesn't work

**Comment by macrozone** [comment]
@xavivzla the screenshot above is only a warning and does not indicate an actual problem. 

So maybe you update your issue description. would also be nice if you'd follow the issue template. this should help finding the actual problem

**Comment by xavivzla** [comment]
when i try to add a text
![image](https://user-images.githubusercontent.com/38009571/81314609-f033d900-904e-11ea-94d3-0fabb1fb5543.png)

my component

![image](https://user-images.githubusercontent.com/38009571/81314887-3db04600-904f-11ea-978a-d7cce6b452a3.png)
