### ISSUE TITLE
Is there a way to get html string output with inline styles?

### ISSUE THREAD

**Issue by ashishpixels** [react-page/react-page#799]
In react-page/ORY Editor currently, we can get a HTML string output by using:

```
ReactDOMServer.renderToString(
  <HTMLRenderer state={editorValue} plugins={plugins} />
)
```

However, this exports the HTML tags with pre-defined "class" names, which are then styled using the CSS files imported in the code.

I'm trying to implement something, where I use react-page/ORY on a web-page. Export the HTML, and render this is a mobile app, using react-native. CSS files cannot used in mobile app development.

Now there is no easy solution to when it comes to CSS files of react-page/ORY, because all the CSS files are distributed all along the node-modules in separate folders.

I even tried:
- putting a bunch of these CSS files in a single folder,
- creating a .html file, and importing these CSS files in that .html file,
- opening this .html file now on browser clearly shows CSS files weren't applied, maybe because of distributed nature of CSS files.

So, any ideas on getting inline-styled HTML as export from react-page/ORY?

**Comment by andreastoermer** [comment]
OK, this is maybe not really the solution you want, but for my project i write an own renderer. I use the editor object and analyse it at the page where i want to display the entries. For each Plugin I write my own Renderer which return a component per Plugin, so i have the full control over the output.

**Comment by ashishpixels** [comment]
@andreastoermer Seems like the only option that is left I guess, if there isn't any other way. Even I thought of this. Let me see if I can fit writing own renderers within the project-deadline that I have. Seems highly unlikely. Thank you, though, for the quick response and a way-around. Means a lot!

**Comment by mikeljoe1** [comment]
ReactDOMServer.renderToString(
  <HTMLRenderer state={editorValue} plugins={plugins} />
) This approach is not working with latest version of react-page
