### ISSUE TITLE
BlurGate

### ISSUE THREAD

**Issue by PeterKottas** [react-page/react-page#800]
**Describe the bug**
There is a new component that was introduced a little while ago called [Provider](https://github.com/react-page/react-page/tree/46a690f8a5b6849a6fadb23b0b1c66818bceb83e/packages/core/src/Provider). Inside this component is another component called [BlurGate.](https://github.com/react-page/react-page/blob/46a690f8a5b6849a6fadb23b0b1c66818bceb83e/packages/core/src/components/BlurGate.tsx)

This component is switching to edit mode whenever you click outside of Provider tree. There is currently no way to enable/disable this functionality from outside by external API and this is causing a problem on my end.

I will provide a fix for this in a little bit via PR

**Comment by PeterKottas** [comment]
PR in https://github.com/react-page/react-page/pull/801, could you pls take a look @macrozone ?

Also, I am curious if we should maybe consider removing the BlurGate functionality altogether. It sounds more like a userland implementation than something that should live in the core. What do you think?

**Comment by macrozone** [comment]
@PeterKottas the blur gate is really important for usability and should not be in userland. Its particularly important to work correctly, if you have multiple editors on the same page. 

Please report what is not working for you, instead of working around it. Maybe there is a bug or some glitch?

**Comment by PeterKottas** [comment]
Hmm, pls help me understand. If I have 2 editors next to each other (for some reason), and I want to be in the move mode in one, and resize mode in the other, it would keep switching to edit mode on the other one every time I work with the first editor. Right? I don't think that's good. Unless I am missing some limitations regarding react-dnd maybe.

In my case, I have an interactive tutorial implemented using https://reactour.js.org/. I lead people to switch modes and explain how it works but unfortunately, with this, every time I click inside the tutorial modal, it switches the mode back to edit making it unusable. 

I can easily imagine other examples where this should be disabled. Imagine a sidebar implemented with a drawer component. That would once again cause possibly unwanted switching between modes. 

Also, why does it switch to edit mode? Wouldn't maybe preview mode make more sense? Generally speaking, if you leave editable component ut usually reverts to it's "readonly" state. Also maybe, should it restore the previous mode once click back into the blurgate? Once again, I am not seeing your use-case clearly so this whole paragraph might not make sense.

**Comment by PeterKottas** [comment]
Anticipating your possible followup to my explanation, I cannot move the reactour component (that uses portals to display the interactive tutorial) inside the provider because this component is responsible for showing multiple tutorials across the page. Also, a part of the tutorial is navigating to the page that contains the editor, therefore when the tutorial starts, the provider is not even in the dom.

**Comment by PeterKottas** [comment]
I rechecked the code, and one thing I noticed is that this doesn't only switch mode but also triggers blur on all cells. I can see how that can be useful. But the mode switching is still eluding me.

**Comment by macrozone** [comment]
> Hmm, pls help me understand. If I have 2 editors next to each other (for some reason), and I want to be in the move mode in one, and resize mode in the other, it would keep switching to edit mode on the other one every time I work with the first editor. Right? I don't think that's good. Unless I am missing some limitations regarding react-dnd maybe.
> 
> In my case, I have an interactive tutorial implemented using https://reactour.js.org/. I lead people to switch modes and explain how it works but unfortunately, with this, every time I click inside the tutorial modal, it switches the mode back to edit making it unusable.
> 
> I can easily imagine other examples where this should be disabled. Imagine a sidebar implemented with a drawer component. That would once again cause possibly unwanted switching between modes.
> 
> Also, why does it switch to edit mode? Wouldn't maybe preview mode make more sense? Generally speaking, if you blur editable component it usually reverts to it's "readonly" state. Also maybe, should it restore the previous mode once you click back into the blurgate? Once again, I am not seeing your use-case clearly so this whole paragraph might not make sense.

the idea of switching to edit mode is that you can just click on it and edit it. I don't think the preview mode is very useful in general. Me personally and the users i observed prefered to just be able to click into the editor. But maybe make that configurable? 

> triggers blur on all cells. 

exactly that is important ;-) Because the editor will show the toolbar of whatever is selected. As the toolbar is positioned relative to the viewport, you would have multiple toolbars overlapping each other. That's why the blur all and the blurgate is important. As you seed the 

There is another gotcha why i switched to editMode, but i don't 100% remember it right now. I think when blurring, you have to make sure to switch out of "add things" mode, as this shows a panel on the left.

So a possible solution:

- when blur, switch to defaultMode if in "add things" mode, stay in other modes otherway
- defaultMode defaults to editMode, but can be change to any other mode.

what you think about that?

**Comment by PeterKottas** [comment]
> triggers blur on all cells.

I thought that was a Heureka moment :) Ok I agree with most stuff, I can implement. However, I do think we can also leave the "disable" there. I have custom implementation for pretty much the whole UI. I don't even have "add" mode at all. Also, the way we do things, we only have one editor. I understand that might be an advanced use-case but I think the disable is reasonable to have anyways. Sounds good?

**Comment by PeterKottas** [comment]
Close via #801
