### ISSUE TITLE
Duplicate button on slate editor broken

### ISSUE THREAD

**Issue by PeterKottas** [react-page/react-page#802]
**Describe the bug**
If you hit the duplicate button on slate editor, the 2 cells become somehow (through the magic of slate) intertwined leaving the editor state corrupted. I am investigating.

**To Reproduce**
1. Go to example
2. Click on any slate text.
3. Click duplicate button
4. Select text and it selects it in the duplicated cell
5. Also it does some other funky stuff and when you even remove the "offending cell", it fails completely with error:
```
Failed to execute 'getRangeAt' on 'Selection': 0 is not a valid index.
```

**Expected behavior**
Should work

**Screenshots**

**Desktop (please complete the following information):**
 Happens everywhere

**Smartphone (please complete the following information):**
 Happens everywhere

**Additional context**

**Comment by macrozone** [comment]
really weird behaviour indeed,  also have to check

**Comment by PeterKottas** [comment]
Yp, I think it's caused by the recent upgrade of Slate. I remember I had some problems with this before. Simply put, you cannot just 
```
...item
``` 
to get a new item. Because some of the nested properties are used by reference in https://github.com/react-page/react-page/blob/master/packages/core/src/actions/cell/insert.ts#L131

**Comment by PeterKottas** [comment]
In other words, the state of slate while it is a pure javascript object, it cannot simply be spread into a new object without consequences. It should be cloned deeply for this to work. I think I will have a PR soonish, looking into it now.

**Comment by PeterKottas** [comment]
Close via #801
