### ISSUE TITLE
when editor is inside a `display: none` the toolbar is positioned wrong

### ISSUE THREAD

**Issue by macrozone** [react-page/react-page#803]
**Describe the bug**

When the editor is inside a a element with `display: none` it still get rendered, but the size computation from the browser will return a 0 size box. This messes with the toolbar positioning.
when you resize afterwards (and after it became visible), the position is correct again

This happens for example if you put an Editor inside a react-admin tab (in newer react-admin versions).

**Expected behavior**

position calculation is currently done on window resize and scroll. There are some newer apis to check whether an element became visible that we can use here.

**Comment by PeterKottas** [comment]
I wonder if we should remove https://github.com/react-page/react-page/blob/master/packages/core/src/components/Dimensions/index.tsx altogether and replace it with something like https://github.com/ctrlplusb/react-sizeme. I am using that in one of my projects and it's working quite nicely. That being said, Not sure if it would fix this issues. Maybe this is a separate thing.
