### ISSUE TITLE
Consider removing spacer

### ISSUE THREAD

**Issue by PeterKottas** [react-page/react-page#806]
**Is your feature request related to a problem? Please describe.**
Once again something that came up while testing with real users. This, however, is more of a suggestion for people using this lib then actual feature that can be implemented. After all, it's up to you as developers to choose plugins you want to use. It appears that the spacer is somewhat confusing for people. Notably, the fact that for instance in slate, you just need to add empty spaces, but with image, you need to drag and drop a whole new component. 

**Describe the solution you'd like**
What we did in our code is we added an extra button to the bottomToolbar to configure padding above and/or bellow selected plugin. The implementation is kind of hairy as we needed to add this to each of our plugins. This would be much simpler if we could extend/override default rendering for internal components.

**Comment by macrozone** [comment]
i would also welcome it to remove some built-in plugin ;-) i don't use spacer as well

**Comment by PeterKottas** [comment]
Ok, once I'll sort out some implementation details on our end, I will post a few images here with this functionality and we can decide if we want this in core.

**Comment by macrozone** [comment]
@PeterKottas i think adding padding to every component is rather easy to do in userland.

with the schema-driven plugins, you would just use a property for that on the schema. 

So at the moment I would not replace it and remove it from the repository. Maybe we can put it in another repo? Reason is, that the monorepo is currently really big and slow and removing not nessecary stuff would make thinkgs faster and leaner

**Comment by PeterKottas** [comment]
It's actually not so EZ when not all of the plugins are under your control. The way I do it now is I simply add {bellow: number, above: number} to the state of every plugin, and then render additional padding component that takes this into consideration in every plugin render. This is in a way similar to what you suggested. However, if all plugins were not in my source, it might be trickier. Yeah, life people follow the guidelines on separating renderer and controls, then you can achieve it, but obviously you also have to add functionality to the bottom toolbar. I do agree though that this doesn't necessarily belong to the core.

**Comment by zehawki** [comment]
> Consider removing spacer

Fully disagree with this proposal :-)

Please dont remove stuff thats already there and working well - just because you dont use. A spacer component is a lifesaver. I saw it first some years ago on Squarespace and its a fantastic feature for page designers to add blocks of spaces where they want, to clean up the page visually.

Adding a padding to every component is cumbersome, and can never satisfy everyone's aesthetics.

**Comment by macrozone** [comment]
@zehawki i also think the spacer is handy :-)

I also agree that we should not remove stuff that is already there, unless we have better and more generic alternatives.

Adding padding-functionallity to every cell is not that cumbersome, as you could iterate through plugins and wrap the `Renderer` with another component and extend the controls.schema, but that is not that easy for every component as not every component uses the same kind of controls (currently there are two control types: "autoform" and "custom". "autoform" takes a JsonSchema and turns it into a form (using uniforms), where custom just takes a custom component.

So I am thinking about adding a helper for that and maybe allow cell Plugins to have more than one `controls`. So such a helper function would add another control that just controls the padding. I guess that could be very handy... 🤔

**Comment by zehawki** [comment]
Oh I don't mean from a dev POV, but from a end user POV. A block page builder like this may be used by someone to quickly build a page, without having to muck around with a ton of settings, esp individual padding + margin etc...

**Comment by PeterKottas** [comment]
I think there is some confusion, likely because I didn't provide enough examples and/or video of our implementation. That's on me, but frankly, at this point, it's a moot point.  Also what I mentioned:

> It appears that the spacer is somewhat confusing for people. Notably, the fact that for instance in slate, you just need to add empty spaces, but with image, you need to drag and drop a whole new component.

This is not my personal feeling. It's data that came from statistically valid testing on real users. Take it or leave it I guess :) 

Personally, I have no strong preference here as we simply redeveloped a bunch of plugins to match our exact needs. In an ideal world, plugins would be developed by the community, but from experience, you usually end up with some strong business opinions that are unlikely to be compatible with other people's needs. 

The most important question is what is the reasonable amount of plugins to keep in core and what to leave to other people or the (non-existing) community.

**Comment by macrozone** [comment]
> In an ideal world, plugins would be developed by the community, but from experience, you usually end up with some strong business opinions that are unlikely to be compatible with other people's needs.

its also my experience, that's why i also favor to improve the api to make _better_ CellPlugins more easily than to encourage sharing CellPlugins in the community. The `Renderer` of a plugin is always very opinionated and dependent on the surrounding app and the `controls` are now much simpler with `type: "autoform"`. This limits the amount of CellPlugins that makes sense to share to those that have complicated controls, like the slate/richtext plugin.
