### ISSUE TITLE
Ability to override internal components

### ISSUE THREAD

**Issue by PeterKottas** [react-page/react-page#807]
**Is your feature request related to a problem? Please describe.**
Right now, it's not possible to override any internal rendering functionality from outside. This becomes a problem when you want to implement some advanced functionality. Simple example is described in #806 . Effectively, when you want to add anything to all cells (className, style or extra functionality), you need to either PR the main lib (and userland stuff should not be put there), or implement it in the render for each and every one of the plugins in your pipeline. The draft button that was recently added is another good example. Stuff like this should be possible to do from outside.

**Describe the solution you'd like**
The components for Rows, Row, Cell ... should be overridable/extendable or both. We could, for instance, expose functions like getRowsProps that would allow us to pass extra props to rows renderer. On the other hand, we could also consider allowing people to replace these components altogether to allow folks to build completely custom experiences. I wonder how this would fit into your usage @macrozone .

**Describe alternatives you've considered**
There is at the moment no way to modify some functionality without forking/PRing the main lib.

**Comment by macrozone** [comment]
this is similar to https://github.com/react-page/react-page/issues/794

and i totally agree. Maybe we can later unify Rows also it with layout plugins.

how could the api to customize rows look like? maybe simple as

```

const Row = (rowProps) => ....

<Editor Row={Row} ... />
// or group it:

<Editor components={{Row}} ... />

```

and we would pass all needed props to it.

There are some other technical components like the drag&drop and resize components to consider. Maybe some could work with refs that we would pass to Row and Cell, where it has to be added to the outermost element 🤔

**Comment by PeterKottas** [comment]
Yeah I had something similar in mind. And you are totally right, the drag-drop and resize functionality makes it kind of tricky. Questions arise such as:
Do we consider those internal workings of the editor? Or should we allow people to replace/remove these altogether? Maybe the API you suggested would work seamlessly if we exported the Draggable/Resizable/Droppable components and instructed people via docs that while the can easily use their own custom row Components, it's advisable (not necessary) to wrap their custom rendering with these internal components. Maybe we can even expose HOC since useDraggable, UseDroppable, and so on, that you would just use on your custom row component. Just thinking out loud rly.

**Comment by PeterKottas** [comment]
Btw, I think the api without grouping looks much nicer ;)

**Comment by macrozone** [comment]
still an issue, but needs some further refactorings like https://github.com/react-page/react-page/issues/777

i started to add a lot of hooks, e.g. there is one to get the current node, but its not yet used everywhere. 

When this is used, we can clean up all types and simplify the components. This will make it much easier to also tackle extending the Rows which are currently not customizable

**Comment by macrozone** [comment]
this is now possible, but only BottomToolbar and PluginMissing is implemented, but its now easy to add more components to it.

If you have specific requirements, please open a new issue. There are also other ways how we can allow customization for cells, rows and ui elements. So its best to always have a specific (real) usecase in mind
