### ISSUE TITLE
undefined initialState

### ISSUE THREAD

**Issue by hkkvo** [react-page/react-page#808]
I followed the below steps:

$ npm i -g create-react-app
$ create-react-app .

and install the editor using npm or yarn:

$ yarn add @react-page/react-page
$ npm i --save @react-page/react-page

Next, open the file src/components/App.js and include the React Page:

I'm getting undefined initialState.

how to initialize the editor

**Comment by hkkvo** [comment]
```js
import React, {Component, useState } from "react";

// The editor core
import Editor, { Editable, createEmptyState } from "@react-page/core";
import "@react-page/core/lib/index.css"; // we also want to load the stylesheets
// Require editor ui stylesheet
import "@react-page/ui/lib/index.css";
import { Trash, DisplayModeToggle, Toolbar } from "@react-page/ui";
// Load some exemplary plugins:
import slate from "@react-page/plugins-slate"; // The rich text area plugin
import "@react-page/plugins-slate/lib/index.css"; // Stylesheets for the rich text area plugin
import background from "@react-page/plugins-background"; // A plugin for background images
import "@react-page/plugins-background/lib/index.css"; // Stylesheets for  background layout plugin

// Define which plugins we want to use. We only have slate and background available, so load those.
const plugins = {
  content: [slate()], // Define plugins for content cells. To import multiple plugins, use [slate(), image, spacer, divider]
  layout: [background({ defaultPlugin: slate() })] // Define plugins for layout cells
};

// Creates an empty editable
const content = createEmptyState()

// Instantiate the editor
const editor = new Editor({
  plugins,
  // pass the content state - you can add multiple editables here
  editables: [content],
})

class App extends Component {
  render() {
    return (
      <div>
        <div className="App-header">
          
          <h2>Welcome to React</h2>
        </div>

        {/* Content area */}
        <Editable editor={editor} id={content.id}/>

        {/*  Default user interface  */}
        <Trash editor={editor}/>
        <DisplayModeToggle editor={editor}/>
        <Toolbar editor={editor}/>
      </div>
    );
  }
}

export default App;

```

I used the above code. But I'm getting below error

![Screenshot from 2020-05-20 08-23-25](https://user-images.githubusercontent.com/62047065/82399647-3fc4cc80-9a73-11ea-9fd3-1cc2a02e5758.png)

**Comment by macrozone** [comment]
@hkkvo can you follow the quick start here? https://github.com/react-page/react-page/blob/master/docs/quick-start.md

you are using an older way of using the editor (it should still work but is not recommended in simple cases)

**Comment by hkkvo** [comment]
I followed Quick Start guide but I was getting **undefined initialState** error

from below line 

```js 
const [editorValue, setEditorValue] = useState(initialState);
```
Later I tried older version

**Comment by macrozone** [comment]
what do you pass to `initialState` ? your linter should complain that you don't have a value there. 

this is just an example and requires some react knowledge.

use `const [editorValue, setEditorValue] = useState();` then to try it out

**Comment by PeterKottas** [comment]
You can also take a quick look at [demo src](https://github.com/react-page/react-page/blob/master/examples/src/index.tsx). And yeah, we know, the docs suck at the moment. Sry about that, there are plans to improve that in the future.

**Comment by hkkvo** [comment]
I'm new to react and I tried may different possible ways.
```js
const [editorValue, setEditorValue] = useState();
```
then I got below error 

```js
./src/App.js
  Line 24:26:  'useCallback' is not defined  no-undef
  Line 25:51:  'editorvalue' is not defined  no-undef
```
Then I added below line of code to **package.json**, thinking that fetch does not work on localhost

"proxy": "http://localhost:3000"

then I changed 

```js const saveToDatabase = useCallback(() => {
    return fetch("/save", { method: "POST", body: editorvalue });
  }, []);
```
still I'm getting the same error

```js
./src/App.js
  Line 24:26:  'useCallback' is not defined  no-undef
  Line 25:51:  'editorvalue' is not defined  no-undef
```

Later I passed the **editor object** to useState() method
```js 
 [editorValue, setEditorValue] = useState( editor)
```
 **which  initiated as below**

```js 

const content = createEmptyState()
const editor = new Editor({
  plugins,
  // pass the content state - you can add multiple editables here
  editables: [content],
})```

but still, it's not working

**Comment by hkkvo** [comment]
> You can also take a quick look at [demo src](https://github.com/react-page/react-page/blob/master/examples/src/index.tsx). And yeah, we know, the docs suck at the moment. Sry about that, there are plans to improve that in the future.

I tried running example also I ended up in 'why-did-you-update' message

**Comment by PeterKottas** [comment]
Mate, it seems like you are getting a lot of stuff mixed up. Either you are using some old version of react (pre hooks where useCallaback is not defined) or you are somehow misconfiguring this. The saveToTheDatabase from https://github.com/react-page/react-page/blob/master/docs/quick-start.md is of course just a showcase of how the state can be saved into database. Changed there won't affect anything.

If trying to run the demo. Make sure to run from the latest tag or master. I don't believe why-did-you-update is configured there. 

I strongly believe the quick start guide if followed properly with reasonably recent version of react should simply work.

**Comment by PeterKottas** [comment]
Also, the errors you provided are quite self-explanatory and have nothing to do with this lib. You are either forgetting to import or define some of the mentioned variables. For such issues, please check stack-overflow that covers most of these basic javascript concepts.

**Comment by hkkvo** [comment]
> Also, the errors you provided are quite self-explanatory and have nothing to do with this lib. You are either forgetting to import or define some of the mentioned variables. For such issues, please check stack-overflow that covers most of these basic javascript concepts.

Yes, they are related to javascript but the API is related to react-page which are I'm not aware of

**Comment by PeterKottas** [comment]
You need to follow the quickstart example, the fetch or useCallback is not this editor's API. Editor cannot be assigned to editorValue, also you don't even need to create the editor on your own.

**Comment by hkkvo** [comment]
> You need to follow the quickstart example, the fetch or useCallback is not this editor's API. Editor cannot be assigned to editorValue, also you don't even need to create the editor on your own.

I'm getting the same error after following quickstart example

Failed to compile

```js 
./src/App.js
  Line 22:50:  'initialState' is not defined  no-undef
  Line 25:58:  'editorvalue' is not defined   no-undef
  Line 26:7:   'editorvalue' is not defined   no-undef
```
what value I have to assign for **initialState** parameter in useState(**initialState**) method ?

If I initialize **editorValue** without passing any value to useState(),  like below

```js 
const [editorValue, setEditorValue] = useState();
```
**I'm getting below error**

```js 
./src/App.js
  Line 24:26:  'useCallback' is not defined  no-undef
  Line 25:51:  'editorvalue' is not defined  no-undef
```
Hence I passed the **editor** value to useState() method. but still I'm getting error

**Comment by grumpyTofu** [comment]
> You need to follow the quickstart example, the fetch or useCallback is not this editor's API. Editor cannot be assigned to editorValue, also you don't even need to create the editor on your own.

I followed the quickstart guide exactly and received this error at the first step.

![image](https://user-images.githubusercontent.com/30991516/82522616-fa96ae00-9af7-11ea-9b1b-d8422d4d8053.png)

I would love to implement this library as the demos look awesome, but the docs don't really make it easy to know where to even start.

**Comment by PeterKottas** [comment]
Just remove that variable

**Comment by hkkvo** [comment]
> Just remove that variable, if you need to pass in initialState (from a db or whatnot) that's where you put it.

If I initialize editorValue without passing any value to useState(),

const [editorValue, setEditorValue] = useState();
I'm getting below error

./src/App.js
  Line 24:26:  'useCallback' is not defined  no-undef
  Line 25:51:  'editorvalue' is not defined  no-undef

**Comment by hkkvo** [comment]
After removing couple of lines of code. Finally, react-page is running, Here is the working code. But still **I'm unable to understand what initialState means and why editorValue is not getting initialised**

```js

import React, { useState, useCallback } from "react";

// The editor core

import Editor from "@react-page/editor";
import "@react-page/core/lib/index.css"; // we also want to load the stylesheets
// Require editor ui stylesheet
import "@react-page/ui/lib/index.css";

// Load some exemplary plugins:
import slate from "@react-page/plugins-slate"; // The rich text area plugin
import "@react-page/plugins-slate/lib/index.css"; // Stylesheets for the rich text area plugin
import background from "@react-page/plugins-background"; // A plugin for background images
import "@react-page/plugins-background/lib/index.css"; // Stylesheets for  background layout plugin

// Define which plugins we want to use. We only have slate and background available, so load those.
const plugins = {
  content: [slate()], // Define plugins for content cells. To import multiple plugins, use [slate(), image, spacer, divider]
  layout: [background({ defaultPlugin: slate() })] // Define plugins for layout cells
};

const App = () => {
  const [editorValue, setEditorValue] = useState();
  // save the state somewhere
  
  return (
    <div>
      <Editor plugins={plugins} value={editorValue} onChange={setEditorValue} />
     
    </div>
  );
};

export default App;


```
