### ISSUE TITLE
Broken demo link

### ISSUE THREAD

**Issue by PeterKottas** [react-page/react-page#810]
Hi @aeneasr, I have noticed the SSL on the domain that hosts the demo of the editor is not working. I was wondering if you could change the description of this repo from 
```
Next-gen, highly customizable content editor for the browser - based on React and Redux and written in TypeScript. WYSIWYG on steroids. https://ory-editor.aeneas.io
```
To
```
Next-gen, highly customizable content editor for the browser - based on React and Redux and written in TypeScript. WYSIWYG on steroids. http://ory-editor.aeneas.io
```
Removing the "https" from the link. I'd do it myself by I don't have the permissions to do so. I wonder if @macrozone has it but I doubt it. Cheers mate!

**Comment by aeneasr** [comment]
Fixed :)

**Comment by PeterKottas** [comment]
That was some quick work, cheers man!
