### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by PeterKottas** [react-page/react-page#811]
Docs are pretty much in a state of disrepair. What I would suggest is using a tool like https://docsify.js.org/ to render a new, more professional looking docs for this lib, salvaging what can be salvaged from the content of the docs and removing the rest.

**Comment by PeterKottas** [comment]
@aeneasr one extra thing for today, could you please set up github-pages from master docs folder? I will be pushing a PR from brand new docs in a minute.

**Comment by aeneasr** [comment]
Sure!

http://react-page.github.io/react-page/

**Comment by PeterKottas** [comment]
Lovely, thanks!
