### ISSUE TITLE
TypeError: Cannot read property 'defaultPlugin' of null

### ISSUE THREAD

**Issue by quyenth** [react-page/react-page#814]
I have add simple example follow document and get error **TypeError: Cannot read property 'defaultPlugin' of null**. The code is bellow

`import React, { Component } from 'react'
// The editor core
import Editor, { Editable } from '@react-page/core'
import { createEmptyState } from '@react-page/core'
import '@react-page/core/lib/index.css'
// The default ui components
import { Trash, DisplayModeToggle, Toolbar } from '@react-page/ui'
import '@react-page/ui/lib/index.css'
// The rich text area plugin
import slate from '@react-page/plugins-slate'
import '@react-page/plugins-slate/lib/index.css'
import background from "@react-page/plugins-background";
import parallax from '@react-page/plugins-parallax-background';
import '@react-page/plugins-parallax-background/lib/index.css';
// Define which plugins we want to use.
const plugins = {
  content: [slate()],
  layout: [parallax({ defaultPlugin: slate() })]
}

// Creates an empty editable
const content = createEmptyState()

const editor = new Editor({
  // pass the plugins
  plugins: plugins,
  // pass the content
  editables: [content],
  defaultPlugin:slate(),

})

class App extends Component {
  render() {
    return (
      <div className="App">
        <Editable
          editor={editor}
          id={content.id}
          
        />

        <Trash editor={editor} />
        <DisplayModeToggle editor={editor} />
        <Toolbar editor={editor} />
      </div>
    )
  }
}
export default App`

Thanks,

**Comment by PeterKottas** [comment]
Don't be so quick to mark stuff as bugs :) You are missing the provider component. Please look at https://react-page.github.io/react-page/#/quick-start. You either use the Editor component for simplicity or a combination of Provider and Editable for greatly improve customizability.
