### ISSUE TITLE
Source is included in NPM releases

### ISSUE THREAD

**Issue by PeterKottas** [react-page/react-page#815]
The source code is currently included in every release. I think that's generally not a good idea, but it's also causing some code navigation issues in typescript. When you click to go to implementation in vs code, it goes to the source file instead of the typescript definition. However, the internal vs-code tslint is taking into consideration the definition files. As a result, when you upgrade the version, you have no easy way to refresh ts-lint errors other than restarting typescript complication service. 

Generally speaking, I think the source files should be removed anyway even if it wasn't causing issues.

**Comment by PeterKottas** [comment]
Maybe this could be done during #734

**Comment by macrozone** [comment]
personally i like when source code is included in the npm package, its also considered a good practice by some. Also in the future, people might want to use the untranspiled source code (i hope for a future where we can just publish source code instead of dealing with this transpilation mess)

**Comment by PeterKottas** [comment]
I don't really have a strong preference, but imho source code belongs in the repo, properly tagged, it should be fairly easy to navigate. What people don't realize is the amount of crap you would download with each NPM package if it contains all source code. Millions of files that are basically useless, just taking up space. This is more apparent with NPM than with any other packager. NPM you can easily add one package that adds 10 more each of them 10 more. If all of them are <10 files, no big deal. But you see my point. Node_modules on most of my projects are already well over 300mb. And doing a delete or fresh install takes ages. Also, transpilation/compilation would take ages. There's a reason for compiled resources I think. Anyways, one way or another, at some point, we should probably at least look at this code navigation issue. Cause that's pretty annoying regardless of preference in terms of packaging.

**Comment by seang96** [comment]
Trying version 0.22.0-rc.2 results in my app not compiling since it tries to compile the source code as well which has typescript errors based off of my typescript configs. For this reason alone, removing them from the packed remo with .npmignore file is a good idea.

**Comment by macrozone** [comment]
@seang96 can you try 0.21.0 ? i probably just pushed a broken version (i am about to fix).

can you show your error? i am not sure that it is because of included source code.

**Comment by macrozone** [comment]
@PeterKottas @seang96 will add it to npmignore, so you can check if it helps

**Comment by PeterKottas** [comment]
@seang96 This seems like an error on your end. Your build system should ignore node_modules when compiling. As long as the compiled code is there (which should be pretty straight forward to verify), it should resolve to that. AFK now boys, please check if the new version builds on your systems. Cheers!

**Comment by macrozone** [comment]
i close this as it is now on npmignore in latest versions
