### ISSUE TITLE
Simple editor does not render components

### ISSUE THREAD

**Issue by abanchev** [react-page/react-page#816]
**Describe the bug**
Following the quick start there is nothing rendered, on screen and the render view is 0px sized, preventing the user from adding any new components.

**To Reproduce**
1. Create a new react app
2. follow the quick start at https://react-page.github.io/react-page/#/quick-start
3. Look at the output

**Expected behavior**
We should be able to see at least the default component and be able to edit the content.

**Screenshots**
![Annotation 2020-05-23 122436](https://user-images.githubusercontent.com/1948184/82728460-7fe4b300-9cf0-11ea-857c-f5df267eaf2c.png)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser Chrome
 - Version 81

**Additional context**
Even if i get example serialized content and pass it as value to the editor, nothing is rendered.

**Comment by macrozone** [comment]
@abanchev what does your console log show?

**Comment by abanchev** [comment]
There is nothing in the console, the problem has to do with the way the value is passed via reference to the editable in EditableEditor

**Comment by MuhammedRafi** [comment]
Same problem here

**Comment by macrozone** [comment]
@abanchev did you import all css files? do you see the editor component in the react-devtools?

**Comment by abanchev** [comment]
Everything is imported, the editor is there, however there are no editables in it.

**Comment by macrozone** [comment]
@abanchev i just checked the documentation and the `defaultPlugin` is missing there, i will add it.

i opened an issue about this https://github.com/react-page/react-page/issues/828

**Comment by MonteKrysto** [comment]
Having the same problem, I just copied the code from the quick start guide, which has the `defaultPlugin` added
```
const plugins = {
  content: [slate()], // Define plugins for content cells. To import multiple plugins, use [slate(), image, spacer, divider]
  layout: [background({ defaultPlugin: slate() })] // Define plugins for layout cells
};

const App = () => {
  const [editorValue, setEditorValue] = useState();
  return (
    <Editor
      plugins={plugins}
      defaultPlugin={slate()}
      value={editorValue}
      onChange={setEditorValue} />
  );
```

**Comment by macrozone** [comment]
@MonteKrysto the warning has probably nothing to do with the problem and i think i already fixed that, but i have to check.

did you load the css files needed?

**Comment by MonteKrysto** [comment]
@macrozone Thank you for the quick reply!  This is the code I have, which is directly copied from the quick start guide, I _believe_ I do have all the css files

```
import React, { useState, useCallback } from "react";

// The editor core
import Editor from "@react-page/editor";
import "@react-page/core/lib/index.css"; // we also want to load the stylesheets
// Require editor ui stylesheet
import "@react-page/ui/lib/index.css";

// Load some exemplary plugins:
import slate from "@react-page/plugins-slate"; // The rich text area plugin
import "@react-page/plugins-slate/lib/index.css"; // Stylesheets for the rich text area plugin
import background from "@react-page/plugins-background"; // A plugin for background images
import "@react-page/plugins-background/lib/index.css"; // Stylesheets for  background layout plugin

// Define which plugins we want to use. We only have slate and background available, so load those.
const plugins = {
  content: [slate()], // Define plugins for content cells. To import multiple plugins, use [slate(), image, spacer, divider]
  layout: [background({ defaultPlugin: slate() })] // Define plugins for layout cells
};

const App = () => {
  const [editorValue, setEditorValue] = useState();
  return (
    <Editor 
      plugins={plugins} 
      defaultPlugin={slate()}
      value={editorValue} 
      onChange={setEditorValue} />
  );
};

export default App;
```

On another issue, I have tried using this in a typescript version and got all sorts of type errors, do you have a TS example?

**Comment by macrozone** [comment]
@MonteKrysto which version do you use? do you see any other error in the console?

maybe also disable strictmode, i am not sure if that is supported (yet)

TS works, we use it in typescript projects, its written in typescript and the example project here in this repo is also in typescript: https://github.com/react-page/react-page/tree/master/examples/src

Can you share some type errors?

**Comment by MonteKrysto** [comment]
Thanks @macrozone!  I am using `"@react-page/react-page": "^0.22.0-rc.2",` and no errors in the console other than the warning above.  

Let me rerun the typescript version and I'll share the messages with you

**Comment by BHVampire** [comment]
Hi!

I got the same problem, and it's pretty weird.

But watch this!

I can't add or edit anything with ORY, but when I edit some **State** not related to the editor, it start to work.
![Untitled Project](https://user-images.githubusercontent.com/67548031/91127721-77dc3c80-e66c-11ea-90f4-848c0461a128.gif)

BTW:

The Editor looks pretty amazing, it's really weird to see something really well done in the internet, I must say, the developer has a very very good taste and skills, Thanks you for all your work <3

**Comment by macrozone** [comment]
@BHVampire did you import all css?

**Comment by macrozone** [comment]
@BHVampire can you share a reproduction?

**Comment by macrozone** [comment]
@BHVampire @abanchev i identified a problem that occures under certain conditions, it should be fixed in latest version. can you guys check and give us feedback? thx! <3
