### ISSUE TITLE
@react-page/plugins-html5-video not included in the @react-page/react-page package

### ISSUE THREAD

**Issue by abanchev** [react-page/react-page#817]
**Describe the bug**
react-page/plugins-html5-video is not added as a dependency to the meta package, so it needs to be added separately to the project

**Comment by macrozone** [comment]
@abanchev i think that is ok. Personally, i would get rid of the meta package anyway and let the users install what they need.

maybe we have to mention to install it somewhere?

**Comment by macrozone** [comment]
meta package won't be updated anymore. 

The suggested way is now to use `@react-page/editor`  and add the plugins that you need
