### ISSUE TITLE
Internet Explorer 11 auto scroll to top when change mode.

### ISSUE THREAD

**Issue by quyenth** [react-page/react-page#827]
I got scroll problem with Internet explorer 11. Each time i change mode or drag plugin, page auto scroll to top. It works fine with Chrome & Firefox.
Thanks you.

**Comment by macrozone** [comment]
@quyenth in general, IE11 is only supported in readOnly mode, because you can expect that everyone who needs to edit content on your application could also use a modern browser.

Having said that, if you can provide a PR that fixes the issue on IE11, we will happily merge it
