### ISSUE TITLE
handle defaultPlugin better when its not passed

### ISSUE THREAD

**Issue by macrozone** [react-page/react-page#828]
you need to pass a `defaultPlugin` to the editor, otherways it will be empty. i also already fell into this trap.

I am not sure if we should handle this differently, maybe the first content plugin is the default plugin if none is passed?

**Comment by hkkvo** [comment]
After passing defaultPlugin prop also, it is still the same. No rendering is happening, unable to add any elements.

**Comment by macrozone** [comment]
> After passing defaultPlugin prop also, it is still the same. No rendering is happening, unable to add any elements.

i fixed it in 0.25.8, see https://github.com/react-page/react-page/issues/834

**Comment by macrozone** [comment]
defaultPlugin will no longer be reqired in the coming 1.0.0
