### ISSUE TITLE
I can't edit or add components untill I edit some not related state on the page.

### ISSUE THREAD

**Issue by BHVampire** [react-page/react-page#834]
Hi!

First of all, the Editor looks pretty amazing, it's really weird to see something really well done in the internet, I must say, the developer has a very very good taste and skills, Thanks you for all your work <3

I have a weird problem but I got a temporal solution and can work with it with no problem for what I want to do.

I can't add or edit anything with ORY, and the buttons are Horizontally arranged instead of Vertical.
But when I edit some **State** not related to the editor, it start to work.
![Untitled Project](https://user-images.githubusercontent.com/67548031/91127721-77dc3c80-e66c-11ea-90f4-848c0461a128.gif)

`<hr>`

The console is empty:
![image](https://user-images.githubusercontent.com/67548031/91128712-45cbda00-e66e-11ea-979c-67d43069e52d.png)

I used Yarn to install it.
Node version: v14.7.0
My React is version: 16.13.1

I don't need a solution right now, but I saw other post like this, so I share you my src folder of react with the simple component (With Context API) I use in the video to use ORY. I hope it helps the people with troubles to see the behavior.
[src.zip](https://github.com/react-page/react-page/files/5121601/src.zip)

Thanks <3

**Comment by macrozone** [comment]
@BHVampire wow, i think i found the issue. Sorry for the late response.

it should be fixed in 0.25.8 (currently on the "next" npm channel, i am pushing to latest right now). can you check?

**Comment by BHVampire** [comment]
@macrozone Hi! Sorry for the late response, I had a lot of work these days. :( 

It worked!

I installed using "next"and got the 0.28.1 version.

At first the example in the Quick Start documentation page didn´t worked, it seems the Background and Slate plugins are not pre-installed in the package.

So I installed them separatedly.
```
yarn add @react-page/plugins-background
yarn add @react-page/plugins-slate
```

After that it coompiled succesfully except for the:
`import { simpleDefaultState } from './Simple-default-state';`

So I deleted it and emptied the default value of the editorValue state:
`const [editorValue, setEditorValue] = useState();`

It worked and looks like this:
![image](https://user-images.githubusercontent.com/67548031/94936944-910ab100-0494-11eb-9134-7bfbe293ac93.png)


The bar was still Horizontal.

So I took the state value from your Next Demo page:
![image](https://user-images.githubusercontent.com/67548031/94937217-eb0b7680-0494-11eb-8cf9-7cc1cde14066.png)

And voila!
![image](https://user-images.githubusercontent.com/67548031/94937408-27d76d80-0495-11eb-9d7f-ae7e8e847638.png)


It works like charm. Except of course for the missing plugins.


Maybe Updating the Getting Started example should be enough for most users.

I can help with that, I'll write a Getting Started example later.

Thanks for all your support. <3

**Comment by macrozone** [comment]
@BHVampire no worries :-) english is also not my mother language. 

We are updating all docs and examples. Everything is not built automatically, so we should find problems earlier.

The built in plugins are indeed not bundled, that is intentional.

I also consider removing them from the repo and put them in their own repos. The exception is slate, which will be used by most projects i guess.

The reason for that is that in many projects you will probably end with most plugins beeing custom plugins and i want to encourage users to create their own component plugins (using `@react-page/create-plugin-materialui`) and show why this is a powerful feature.
