### ISSUE TITLE
How to disable the right side toolbar?

### ISSUE THREAD

**Issue by matheusrocha89** [react-page/react-page#836]
On my project I want a very simple Rich Text Editor and I saw that I can configure which options of slate I want. 
My question is? How can I disable the right sidebar menu? Should I just hide with CSS or there is a more elegant way that the lib allows me to do?

**Comment by macrozone** [comment]
poor mans way is indeed hiding the right sidebar.

We could also add an option to disable it in @react-page/editor so that it does not get rendered at all.

**Comment by matheusrocha89** [comment]
I prefer to have that option, cause I don't wanna render and hide with CSS 😄 It's not a good approach

**Comment by macrozone** [comment]
@matheusrocha89 if you want, you can open up a PR for that <3

**Comment by matheusrocha89** [comment]
I will, for sure. I can start work on that later tonight

**Comment by macrozone** [comment]
@matheusrocha89 basically you need to adjust this line: https://github.com/react-page/react-page/blob/master/packages/ui/src/EditorUI/index.tsx#L19

something like `displayModeBarDisabled ? null : <DisplayModeToggle stickyNess={stickyNess} />`

and then you would need to pass this prop through https://github.com/react-page/react-page/blob/master/packages/editor/src/editor/EditableEditor.tsx 

not sure what the best name would be for the property 🤔

**Comment by matheusrocha89** [comment]
Got it. Gonna do that, thanks @macrozone

**Comment by matheusrocha89** [comment]
@macrozone I already did the changes, it seems that I discovered where to change by myself, when I checked your message I saw that was the same file and the same place I did the change. The project structure was good and easy to understand 😄 .

Just one question: How is the structure of the tests? I saw that was not by component.

**Comment by macrozone** [comment]
> @macrozone I already did the changes, it seems that I discovered where to change by myself, when I checked your message I saw that was the same file and the same place I did the change. The project structure was good and easy to understand 😄 .
> 
> Just one question: How is the structure of the tests? I saw that was not by component.

tests are not that good structured, feel free to use what makes sense for you

**Comment by matheusrocha89** [comment]
👍
