### ISSUE TITLE
Converting circular structure to JSON --> starting at object with constructor 'InnerLoadable' 

### ISSUE THREAD

**Issue by PYYuriy** [react-page/react-page#838]
**Describe the bug**
I am trying to connect editor base on example [quick-start](https://react-page.github.io/react-page/#/quick-start)
but got error, if I am not use `defaultPlugin={slate()}` looks like initialisation with empty value work fine, but same error become when  I try drop text plugin to editor 

**To Reproduce**
1. yarn add @react-page/react-page
2. create file [with](https://react-page.github.io/react-page/#/quick-start?id=simple-example) 
3. use component in place where you need it 

**Screenshots**
![image](https://user-images.githubusercontent.com/9697716/93195066-796fc080-f751-11ea-81ed-8c99e6940a93.png)
![image](https://user-images.githubusercontent.com/9697716/93195234-acb24f80-f751-11ea-9bf8-55496a743522.png)

**Desktop (please complete the following information):**
 - OS: [iOS]
 - Browser [chrome, safari]
 - Rect: 16.13.1

**Comment by PYYuriy** [comment]
related to https://github.com/gregberge/loadable-components/issues/629

**Comment by jcgertig** [comment]
same issue

**Comment by PYYuriy** [comment]
@jcgertig can be solve by adding `[resolutions](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/)` to package.json 
```
  "resolutions": {
    "@react-page/react-page/**/@loadable/component": "5.13.1"
  },
```

**Comment by macrozone** [comment]
@PYYuriy thanks for posting the issue and the workaround. So solution is to downgrade/fix the loadable component library for the time beeing?

**Comment by PYYuriy** [comment]
@macrozone yes, at least until this [task](https://github.com/gregberge/loadable-components/issues/629) become closed
