### ISSUE TITLE
Better Docs

### ISSUE THREAD

**Issue by Mangatt** [react-page/react-page#840]
Hi, is it possible to provide better docs for this project? Right now, neither one of examples from Quick start is working and there is no description whatsoever for any of provided components. Demo page is not working as well.

This project looks amazing, but is is really hard to start from scratch in current state of things.

**Comment by macrozone** [comment]
will try to setup a new demo page next week.

for the time beeing, best check it out and run the example

**Comment by macrozone** [comment]
demo project is fixed and docs are now automatically updated. There is still some work to make them better, but the foundation is now set

**Comment by Mangatt** [comment]
Great, thanks
