### ISSUE TITLE
On layout plugins there is no feature for disallowing to add siblings

### ISSUE THREAD

**Issue by hb90dev** [react-page/react-page#842]
**Is your feature request related to a problem? Please describe.**
In our application we are building books with react page, and we need to have layout plugin and all other plugins must be in layout, so we need to disable to drag near base layout plugin

**Describe the solution you'd like**
There can be new option on layout type plugin component, for example allowNeighbours, and if it will be set to true we would be able to drag only inside layout item.

**Describe alternatives you've considered**

**Additional context**

**Comment by macrozone** [comment]
in beta there will be a new option

```
allowNeighbour?: (item: Cell) => boolean;
```

if this function returns false, you cannot drop an element next to any cell that contains this plugin.

**Comment by hb90dev** [comment]
Cool !! Thanks.

**Comment by macrozone** [comment]
@hb90dev if you try beta, be aware that it will migrate the state. but I think its pretty stable and i will release a release candidate soon. I really appreciate any feedback!

**Comment by hb90dev** [comment]
Should I use the package from github because this release was not available in npm?

**Comment by macrozone** [comment]
@hb90dev you can instlall from npm using the beta tag: yarn add @react-page/editor@beta

be aware that they are some migration steps, its in the changelog, but not in a compiled way. But I can gather all steps soon into one small document. Its straight forward though.

Do you use `@react-page/editor` or the "old" approach of having `<Provider><Editable /><UI /><Provider />`?

**Comment by hb90dev** [comment]
I am using @react-page/editor

**Comment by macrozone** [comment]
@hb90dev i started to gather migration steps, but i have to check whether its complete already: https://github.com/react-page/react-page/blob/beta/UPGRADE.md

**Comment by hb90dev** [comment]
Sorry but also with beta tag it doesn't work. @react-page/editor last version is beta.24 but the @react-page/core latest version is beta.14 and the changes are not present

**Comment by macrozone** [comment]
@hb90dev the core package no longer exists, its explained in https://github.com/react-page/react-page/blob/beta/UPGRADE.md

**Comment by hb90dev** [comment]
Ah ok, I get it. thanks.

**Comment by hb90dev** [comment]
Sorry and one question, can we have plugin that will be not removable and will be prerendered instead of showing add button

**Comment by macrozone** [comment]
> Sorry and one question, can we define plugin that will be not removable and will be prerendered instead of showing add button?

i noticed that as well. I think you relate to cell plugins with children? (layout plugins)

maye we could define a min/max number of childrens. It would not show add button or delete button when limit is reached

**Comment by macrozone** [comment]
@hb90dev would you mind creating a feature request for that?
