### ISSUE TITLE
Providing translations for Editor and its plugins

### ISSUE THREAD

**Issue by DcBD** [react-page/react-page#865]
# @react-page `translations`

## The main concept of defining translations:

The main concept is to pass an `translation` object into the editor eg.

```jsx
const translations = {
  "right_panel": {
      "edit_things_button": "Edit things",
      "move_things_button": "Move things"
  }
}

() => {

  return  (
    <Editor plugins={plugins} translations={translations} />
  )
}



```

the translations object is just my example how could it look, but in that way developer would have a full
controll over the labels all over the editor. Im not sure how the implementation of that would look, considering that
the every plugin has its own bottom drawer and other things.

## Alternative

There would be hard coded translations somewhere in the code, and developers from other coutries could submit
theirs translations. And the editor would take a `lang` prop and based on that property it would load translation for specific language.

# The most important translations/labels I'd like to be able to change are

### Right panel
- `Edit things`
- `Add things`
- `Move things`
- `Resize things`
- `Preview result`

### Left drawer
- `Add plugin to content`
- `Search plugins` - its the placeholder of search textbox
- `Content plugins`
- `No plugins found` - where we type something in search box and there aren't any plugins by that phrase.

### Slate plugin
- `Write here...`  - the text editor when its empty
- `Align left` *and other buttons title* - the titles of those buttons.

### Plugin Bottom drawer
- the titles of the button's e.g (`Toggle size`, `Content is visible` and so on).

**Comment by macrozone** [comment]
i think we can use react-i18next or similar. The editor would have a new Context provider from i18next and whereever we need a label, we can use the hook from i18next.

One goal would also be to lazy load default translations (using `import()`) and we should encourage an api where users would also lazy load their custom translations. This avoids increase in bundle size for users who just view your content.

we can also provide some default translations as you suggested as well. 

The `<Editor />` would receive a new property `uiLang` or similar that would control the language of the editor ui. It shouldn't be confused with the `lang` property that controls which content-language version is displayed.

**Comment by 643364103** [comment]
The function is an enhancement.And it's nice!

**Comment by macrozone** [comment]
devinitly still on the roadmap, personally had no time and driver for it.

**Comment by rexebin** [comment]
It is a big hassle to add translations to all internal components. 

What if the `Editor` component accepts an optional function t: `(text?: string) => string`, then it gets passed to an internal context provider and default it to return given text `(text?: string) => text`. Then just prefix all the labels with the `t` function from context. No structure or prop changes to existing components. 

Then it is lib users' responsibility to implement the `t` function and replace labels with whatever they want. 

At first, we as end-users of react-page won't have all the labels at first, but we can collect the labels from our little `t` function and generate a dictionary automatically, then get the dictionary translated as needed.  We could even contribute the dictionary back, with these dictionaries ready, react-page could support multiple languages out of the box.

**Comment by macrozone** [comment]
> It is a big hassle to add translations to all internal components.
> 
> What if the `Editor` component accepts an optional function t: `(text?: string) => string`, then it gets passed to an internal context provider and default it to return given text `(text?: string) => text`. Then just prefix all the labels with the `t` function from context. No structure or prop changes to existing components.
> 
> Then it is lib users' responsibility to implement the `t` function and replace labels with whatever they want.
> 
> At first, we as end-users of react-page won't have all the labels, but we can collect the labels from our little `t` function and generate a dictionary automatically, then translate the dictionary. We could even contribute the dictionary back, with these dictionaries ready, react-page could support multiple languages out of the box.

yes, something like that. Maybe use i18next, that has some additional features and is widely adopted. we would pass the i18n instance and wherever we use translations, we can use its hook.

maybe a t function as you propose is also enough 🤔. You could still bridge it with i18next or any other translation library

**Comment by rexebin** [comment]
Using i18next would limit users to i18next. I think accepting a `t` function is better, we could just pass i18next's `t` function to `Editor`, or we could implement our own.

**Comment by rexebin** [comment]
@macrozone what is your final decision? I am going to use react-page as a starting point to develop a contract/invoice/document etc. editor for one of my project. The project needs to support multiple languages...

I guess adding a provider, then add a hook in components with labels and wrap the labels with `t`, isn't as hard as passing translations props around and rewrite some code. It doesn't even require an understanding of how the code works. 

Do you accept PR? Is there a contribution guideline somewhere, please?

**Comment by macrozone** [comment]
> @macrozone what is your final decision? I am going to use react-page as a starting point to develop a contract/invoice/document etc. editor for one of my project. The project needs to support multiple languages...
> 
> I guess adding a provider, then add a hook in components with labels and wrap the labels with `t`, isn't as hard as passing translations props around and rewrite some code. It doesn't even require an understanding of how the code works.
> 
> Do you accept PR? Is there a contribution guideline somewhere, please?

sure a PR is welcomed. Contribution guidelines are here: https://react-page.github.io/docs/#/CONTRIBUTING

Make sure that you checkout the `beta` branch at the moment, as i am about to release soon a new version.

Also, its best to add an example in examples/pages/examples (examples is a nextjs app). Running `yarn dev` in the project will start that example project on localhost:3000.

One thing though:

return a t function from a hook, identical to how react-i18next does it. We have to make sure that all these hooks rerun when translations have changed.

Also notice that there is a `lang` property on the Editor, which controls the language of the content, not the editor-ui.

So if you need to introduce a language property for the ui, name it something like `uiLang` or `uiLanguage` or so (suggestion welcome).

**Comment by rexebin** [comment]
Unless react-page has one or more out of box language support, a language property is not required. The lib may introduce one later. We pass in the `t` function, we are responsible for the change of Languages outside of lib's scope. 

As far as I know, the `t` function always re-runs on every render, so we have to optimize as much as possible i.e. small dictionary and performant algorithm. As I understand it, this is the main reason that run-time/dynamic i18n solutions like i18next are not as good as Angular's static compile-time i18n solution.  What do you mean when you say "we have to make sure that all these hooks rerun...", what's in your mind please @macrozone?

In my current project, I am using a custom `t` function, not using i18next. With it and my Dotnet backend, I generate dictionaries and save them to a dedicated SQLite database.  I then use react-query to update dictionaries when translations change.  If the dictionaries changes, my UI updates, no issue.

**Comment by macrozone** [comment]
> Unless react-page has one or more out of box language support, a language property is not required. The lib may introduce one later. We pass in the `t` function, we are responsible for the change of Languages outside of lib's scope.
> 
> As far as I know, the `t` function always re-runs on every render, so we have to optimize as much as possible i.e. small dictionary and performant algorithm. As I understand it, this is the main reason that run-time/dynamic i18n solutions like i18next are not as good as Angular's static compile-time i18n solution. What do you mean when you say "we have to make sure that all these hooks rerun...", what's in your mind please @macrozone?
> 
> In my current project, I am using a custom `t` function, not using i18next. With it and my Dotnet backend, I generate dictionaries and save them to a dedicated SQLite database. I then use react-query to update dictionaries when translations change. If the dictionaries changes, my UI updates, no issue.

i mean, if you change the language, you expect that it changes all the labels ;-)

but i think this will be the case. developers just need to make sure that they pass a new t function to the editor when they want to change the translations.

so as you proposed: pass a translator function to the editor (name: uiTranslator ?), put that in context (you can use optionContext or use a new), add a hook that returns this  uiTranslator function, use the hook everywhere.

**Comment by rexebin** [comment]
> > Unless react-page has one or more out of box language support, a language property is not required. The lib may introduce one later. We pass in the `t` function, we are responsible for the change of Languages outside of lib's scope.
> > As far as I know, the `t` function always re-runs on every render, so we have to optimize as much as possible i.e. small dictionary and performant algorithm. As I understand it, this is the main reason that run-time/dynamic i18n solutions like i18next are not as good as Angular's static compile-time i18n solution. What do you mean when you say "we have to make sure that all these hooks rerun...", what's in your mind please @macrozone?
> > In my current project, I am using a custom `t` function, not using i18next. With it and my Dotnet backend, I generate dictionaries and save them to a dedicated SQLite database. I then use react-query to update dictionaries when translations change. If the dictionaries changes, my UI updates, no issue.
> 
> i mean, if you change the language, you expect that it changes all the labels ;-)
> 
> but i think this will be the case. developers just need to make sure that they pass a new t function to the editor when they want to change the translations.
> 
> so as you proposed: pass a translator function to the editor (name: uiTranslator ?), put that in context (you can use optionContext or use a new), add a hook that returns this uiTranslator function, use the hook everywhere.

That is the plan. This job is pure labour, no brain power required.

**Comment by rexebin** [comment]
Risk being seen as an idiot, I need some help working on the PR. I added the new prop, a context and a hook, run 'yarn dev', the example page is up. The 'Editor' in example now takes a new prop. However, the prop is ignored and new code is not running. I can see code is updated in @react-page folder under node_module in example project. Is there something I need to do to get the changes in editor source code running in example project?

**Comment by macrozone** [comment]
@rexebin no one that wants to help shall be called idiot ❤️

> However, the prop is ignored and new code is not running. I can see code is updated in @react-page folder under node_module in example project. Is there something I need to do to get the changes in editor source code running in example project?

no, it should hotreload changes automatically. Maybe you import something in the example project by a path instead of the main-module, that happend to me sometimes. Can you open up a pull request with your changes? Just mark it as draft and update it regularly, so its easier for me to help and give feedback

**Comment by rexebin** [comment]
> @rexebin no one that wants to help shall be called idiot ❤️
> 
> > However, the prop is ignored and new code is not running. I can see code is updated in @react-page folder under node_module in example project. Is there something I need to do to get the changes in editor source code running in example project?
> 
> no, it should hotreload changes automatically. Maybe you import something in the example project by a path instead of the main-module, that happend to me sometimes. Can you open up a pull request with your changes? Just mark it as draft and update it regularly, so its easier for me to help and give feedback

I am an idiot. I went to the example folder and run `yarn dev`. Backing away from my computer and let my mind taking a break and work out what is going on got me out of the trouble.  It is working now, took some time to compile, but I can see my translations of the sidebar on localhost:3000.

**Comment by macrozone** [comment]
> > @rexebin no one that wants to help shall be called idiot ❤️
> > > However, the prop is ignored and new code is not running. I can see code is updated in @react-page folder under node_module in example project. Is there something I need to do to get the changes in editor source code running in example project?
> > 
> > 
> > no, it should hotreload changes automatically. Maybe you import something in the example project by a path instead of the main-module, that happend to me sometimes. Can you open up a pull request with your changes? Just mark it as draft and update it regularly, so its easier for me to help and give feedback
> 
> I am an idiot. I went to the example folder and run `yarn dev`. Backing away from my computer and let my mind taking a break and work out what is going on got me out of the trouble. It is working now, took some time to compile, but I can see my translations of the sidebar on localhost:3000.

just make sure you run `yarn dev` **in the root folder**, not the examples folder

**Comment by rexebin** [comment]
As per your request, I have created the PR as a draft. Haven't checked tests or anything.
