### ISSUE TITLE
Does React page have a problem with React 17?

### ISSUE THREAD

**Issue by andreastoermer** [react-page/react-page#872]
**Describe the bug**
Until today I had used React 16.13.1 in my project where I use React page. Everything was running normally.

However, after updating to React 17.0.1 I noticed the following:

When I click on a field in the edit mode, the toolbar appears for a short time, but then disappears again.

Now that I have reset React to version 16.13.1 everything runs as before.

Can someone reproduce this problem or is there something in my project that causes the problem after updating React, but the cause is completely different?

I noticed the problem with version 0.23.3 of React Page, but even after updating to version 0.30 it still exists.

**To Reproduce**
1. Use React 16.13.1 and React Page 0.23.3 (everything works fine)
2. Update React to Version 17.0.1
3. Test it again (it's broken)

**Expected behavior**
After clicking on a text field in edit mode, the toolbar appears below

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Edge, Chrome and Firefox

**Comment by macrozone** [comment]
@andreastoermer currently untested, but i plan to test it for version 1.0.0 of react-page. Its also unclear if all dependencies support react 17 (in particular slate). I am pretty sure that without resolutions field, you will end up with multiple react versions.

currently, i would stay at 16.* until this is resolved.

**Comment by macrozone** [comment]
i found an issue with Blurgate, that will be fixed in version 1.0.0-beta.12

**Comment by macrozone** [comment]
@andreastoermer https://react-page.github.io/beta seems to run with react 17!

**Comment by macrozone** [comment]
fixed in current beta
