### ISSUE TITLE
Layout plugin enhancements

### ISSUE THREAD

**Issue by hb90dev** [react-page/react-page#884]
**Is your feature request related to a problem? Please describe.*
Now there is no possibility to have such plugin (layout) which will be not removable. Something that will be prerendered, instead of showing add button. 

**Describe the solution you'd like**
Maybe we could define a min/max number of children

**Comment by macrozone** [comment]
this is partly implemented (you can define childConstraints.maxChildren) on plugins, but it currently just hides the (+) button.

i am thinking about adding minChildren as well, and that would either hide the delete button or use `createInitialChildren` on the plugin to "reset" it to a default state
