### ISSUE TITLE
This is a fake image upload service, please provide actual implementation via plugin properties

### ISSUE THREAD

**Issue by zehawki** [react-page/react-page#893]
Hello,

>This is a fake image upload service, please provide actual implementation via plugin properties

Given this message in the demo, I assume that there is no inbuild mechanism for image upload?

If so:
No editor / page builder can actually be used without having an inbuilt way to upload images - its such an intrinsic necessary feature. Please do create a mechanism for hooking into a backend API via a promise for image uploaded. The promise will resolve with the URL of where the image has been uploaded. This is how Quill and CK works - both of which I use as rich editors.

React page is so promising as a page builder, but crippled without this.

**Comment by macrozone** [comment]
hi @zehawki 

ReactPage is agnostic to the backend and therefore cannot implement any file storage, but you can easily add an upload to an S3 storage, to your file system on the server, in the database or whatever. it works as you described: you implement a function that returns a promise with the url of the image.

The documentation shows the example that is used in the demo: https://react-page.github.io/docs/#/builtin_plugins?id=react-pageplugins-image

you can easily imaging to add an s3 upload there.

hope this helps

> React page is so promising as a page builder, but crippled without this.

that is a harsh statement, so i am glad that we actually support your use case!

**Comment by zehawki** [comment]
>The documentation shows the example that is used in the demo: https://react-page.github.io/docs/#/builtin_plugins?id=react-pageplugins-image

Right, I'd seen that, but I'm a bit confused since it says at multiple places "The image plugin does not support uploads." "The image plugin is not configurable.".

But now I do see the code below. So let me explore. Thanks for pointing this out.

> that is a harsh statement, so i am glad that we actually support your use case!

Sorry sorry :-) not meant to be harsh all. It was more of disappointment on my side since react-page seems to be the sweetest project as a page builder, and I've evaluated the entire universe of them.

**Comment by macrozone** [comment]
@zehawki maybe the documentation needs improvement, i am happy to accept PRs with improvements, english is also not my mother tongue, so sometimes it maybe missleading. Can you point me to where it says "The image plugin does not support uploads."?  I don't think that  "This is a fake image upload service, please provide actual implementation via plugin properties" is missleading, but in the demo it could stress more that you can actually implement any upload logic you want .

**Comment by zehawki** [comment]
Its right there on that page above the code. Please see screenshot:

![image](https://user-images.githubusercontent.com/8095144/108204741-2eb40380-714a-11eb-8daa-c45f99abefc4.png)

I'm happy to redo all the documentation if I can get things to work :-)

**Comment by macrozone** [comment]
> Its right there on that page above the code. Please see screenshot:
> 
> ![image](https://user-images.githubusercontent.com/8095144/108204741-2eb40380-714a-11eb-8daa-c45f99abefc4.png)
> 
> I'm happy to redo all the documentation if I can get things to work :-)

🙈 ok allright, that is very missleading, sorry for that 🙈, i'll try to improve the wording

**Comment by zehawki** [comment]
All done on my side, working perfectly.

**Comment by macrozone** [comment]
would probably nice to have an s3 upload example, that should be easy to do 🤔

**Comment by zehawki** [comment]
Yup, I'm going to provide all the docs together once I've finished - with examples using JS (since I'm not using TS). 

(I've already integrated react-page in the stack and its ready for production release. Now struggling with TS -> JS conversion for custom plugins.)

**Comment by PatoDeVille** [comment]
@zehawki  I am currently working in a project implementing [supabase.io](supabase.io), react admin and react-page. But im working in JS and my image uploader is not working as it should. Im getting the upload in my database and returning a Promise{url: 'uploadedURL'}. 
It would be amazing if you could provide me an example with JS using the image plugin.

**Comment by zehawki** [comment]
@PatoDeVille thats here already https://react-page.github.io/docs/#/builtin_plugins?id=image

**Comment by zoutigo** [comment]
Hello.
As it is a common use case , 
can you please provide example of uploadhandler function when it comes to insert image and fecth the url from api .
In docs , you just mention 

**You can create the promise that will actually upload the image to some server and resolve with { url: someUploadedURL }**

but the function is not built for that:

`function uploadImageShim(defaultUrl) {
  return function (file, reportProgress) {
    return new Promise(resolve => {
      setTimeout(() => {
        resolve({ url: defaultUrl });
      }, 2000);
    });

  };
};`

**Comment by zehawki** [comment]
> but the function is not built for that

Well sure :-) this is just an example.

The actual function depends on your API/service/backend/library, and once it has uploaded, all this foo has to do is resolve with the uploaded URL. Eg in my case, I use axios and do a axios.post to my API which uploads to S3 and sends back a URL. Further example, which is just saying the same thing as in the doc:

```
function uploadImage(defaultUrl) {
  return function (file, reportProgress) {
    // Do something here and finally resolve
    resolve({ url: defaultUrl });
  };
};
```

**Comment by zoutigo** [comment]
Thanks for your answer.
It is working fine when i'm oploading , then posting my form to the server.
However , when comes the time to show the document , the image is not showing, but the text does.

my config is 
form side:

`
```
  const uploadImage = useCallback(
    () => async (file, reportProgress) => {
      const data = await apiPostImage({ file, Token })
      return { url: data.url }
    },[]
  )
const cellPlugins = [
    slate(),
    imagePlugin({
      imageUpload: uploadImage(),
    }),
    divider,
    spacer]
......

 <Editor
             cellPlugins={cellPlugins}
              value={editorValue}
              lang="fr"
              onChange={(newvalue) => handleChange(newvalue)}
              cellSpacing={cellSpacing}
              // uiTranslator={useUiTranslator()}
            />
```

And , after storing all the stuff in the api the fetching .... the read only is 

```
const cellPlugins = [slate()]

function PageScreen({ content }) {
  const value = useCallback(JSON.parse(content), [])

  return <Editor cellPlugins={cellPlugins} value={value} readOnly />
}
```

I don't know why i'm not getting that image, even if i can see the image url when i console.log(content).
>{id: "qguz0y", version: 1, rows: Array(1)}

is there something that im doing wrong ?

Thanks for your help.

**Comment by zoutigo** [comment]
ok.
i found the problem.
in the readOnly mode , my cellPlugins should include image plugin as well .

`const cellPlugins = [slate(), image]`
