### ISSUE TITLE
TypeError: plugins.filter is not a function

### ISSUE THREAD

**Issue by zehawki** [react-page/react-page#896]
Trying to use this example: https://react-page.github.io/docs/#/builtin_plugins?id=react-pageplugins-spacer

Made 2 changes:
1. Set initial state as null as per #869 
2. prop plugins renamed to cellPlugins

Error:

![image](https://user-images.githubusercontent.com/8095144/108401943-e9273180-7242-11eb-95dd-b0855ef20a1a.png)

**Comment by macrozone** [comment]
sorry, there is a typo, its `cellPlugins` not `plugins`. Your IDE might warn you about that

**Comment by zehawki** [comment]
Yup, you can see I've done that already:

> Made 2 changes:
> 1. Set initial state as null as per #869
> 2. prop plugins renamed to cellPlugins

**Comment by macrozone** [comment]
the docs used an outdated example. i removed that for the time beeing
