### ISSUE TITLE
Resize and move cells without dragging

### ISSUE THREAD

**Issue by macrozone** [react-page/react-page#898]
Currently you only can move cells around by draging them.

Idea:

we add new buttons (something like ◀️ , ▶️, 🔼, 🔽) either in the bottom toolbar or next to the new Tab above the cell (or both).

pressing ◀️ would move the cell to the left (swap its position with its left neighbor). ▶️  would do the same to the right

🔼 would probably move the cell out of the current row and put it as a new row above the previous row, full width. Or it would move it somewhere as a neighbor in the previous row. Not sure what "feels" better. Similar for 🔽.

**Comment by mlbrgl** [comment]
I like that idea. It makes moving cells around more predictable and would address some of the current issues:

- target location outside of the visible viewport (it is currently only possible to scroll down while dragging a cell, not up.)
- several possible drop zones near the target location (e.g. small cells) currently require precise movements to find and "lock" the correct one

I also noticed there is a lot happening visually when dropping a cell (bottom bar, back button, resize bar animations, cell animation, sometimes the surrounding cell around flicker):

https://user-images.githubusercontent.com/13406362/109142317-05edc880-775f-11eb-8e9f-963c2c70b251.mov

Here is a similar action in Notion for comparison:

https://user-images.githubusercontent.com/13406362/109142336-0dad6d00-775f-11eb-8ed7-69b614387c7a.mov

All in all, I would actually be in favour of improving the dragging UX before adding another way of moving blocks (e.g. keyboard shortcuts?). It might end up not being that necessary for a significant portion of users. What do you think?

**Comment by macrozone** [comment]
@mlbrgl thank you for the detail videos!


> I also noticed there is a lot happening visually when dropping a cell (bottom bar, back button, resize bar animations, cell animation, sometimes the surrounding cell around flicker):

it currently focuses the cell after drag, maybe we disable that because its distracting as you pointed out.

> All in all, I would actually be in favour of improving the dragging UX before adding another way of moving blocks (e.g. keyboard shortcuts?). It might end up not being that necessary for a significant portion of users. What do you think?

the reducers for dragging are currently implemented in a very complicated way and while I refactored most of the code recently, its the one area where i a still feel uncomfortable and is definitly worth to improve it.

I therefore thought that I would be nice to start with having some new hooks for some actions as they are easy to define:

- `useMoveCellToLeft(nodeId: string)` would swap the given cell with its left neighbour (after calling the returned function)
- `useMoveCellToRight(nodeId: string)` would swap the given cell with its right neighbour

or then

- `useMoveCellToLeftOf(nodeId: string, targetNodeId: string)` would move the given cell to the left of the targetNodeId cell

they already exist in a way [here](https://github.com/react-page/react-page/blob/9c2781fb8344e892b102a59e6caff13f90830069/packages/editor/src/core/components/hooks/dragDropActions.ts#L55) but can be further refactored and streamlined

I think its easier to start with these button actions to get more into the whole move-cell mechanism and after that improving the dragging.

**Comment by mlbrgl** [comment]
hey @macrozone, thanks for the background information! If I understand correctly, what you suggest makes sense to me: get the move actions / reducers sorted out first, and then build upon them to improve drag / drop behaviour.

I don't know about implementation but I would consider `useMoveCellToLeft` a special case of `useMoveCellToLeftOf`. `useMoveCellToLeftOf` could be used for other use cases, such as moving a cell to the beginning of a row, or copy/paste next to an existing cell.

> maybe we disable that because its distracting as you pointed out.

yes, let's try that!

**Comment by macrozone** [comment]
> 
> > maybe we disable that because its distracting as you pointed out.
> 
> yes, let's try that!

just tested it, actually i was wrong. It re-focuses the cell when it was already focused. So I try to  change it that it blurs all cells after drag

**Comment by macrozone** [comment]
@mlbrgl i published 1.1.0 with the the change: moving cells does no longer focus them afterward. See https://react-page.github.io/

**Comment by mlbrgl** [comment]
Thanks @macrozone, that's much better!

I just created [another issue](https://github.com/react-page/react-page/issues/915) to keep track of potential drag / dropping improvement at a later stage.

Thanks again, moving cells around feels more peaceful now :)

**Comment by macrozone** [comment]
is actually in progress

**Comment by macrozone** [comment]
this is available in the beta

**Comment by macrozone** [comment]
this is available in the latest version. I missed updating or referencing this ticket though
