### ISSUE TITLE
Make it easier to "decorate" or "extend" cell plugins

### ISSUE THREAD

**Issue by macrozone** [react-page/react-page#904]
as discussed in https://github.com/react-page/react-page/issues/806

you might want to add the same, basic functionallity to some or all of your cell plugins.

One example is to add padding or margin to cells.

A `CellPlugin` is an object with some properties, important for this case is the `Renderer` and the `controls`.

If you have a CellPlugin `pluginA`, its easy to adjust it to have additional (fixed) padding:

```
const pluginA: CellPlugin = {
    id: "...",
    Renderer: SomeComponent,
    controls: {....}
}

const addPadding = (p: CellPlugin) => {
   return {
      ...p,
      Renderer: (props) => <div style={{padding: 20}}><Renderer {...props} /></div>
   }
}


const pluginAWithPadding = addPadding(pluginA);

```

if we want the plugin to be controllable, its a bit trickier:

```


const addPadding = (p: CellPlugin) => {
   return {
      ...p,
      controls: // we have to mix p.controls with some additional controls, how we should do that?
      Renderer: (props) => <div style={{padding: props.padding}}><Renderer {...props} /></div>
   }
}


```

When controls are of type `autoform` its a bit easier, you just have to add additional properties to the controls.schema, but its not obvious what to do with `type: "custom"` controls.

So the idea is to allow `CellPlugin.controls` to be an array of `CellPluginControls`. If you select a cell with multiple controls, all controls are rendered in the BottomToolbar (either one after the other or as Tabs or so) and the resulting `data` of the cell is the merged object of all controls values.

Intead of an array, it could also be a `type: "multiple"` or so, that could take additional properties (e.g. whether to render them as tabs or just one after the other).

Typings might get a bit tricky, every single of the multiple control would only manage `Partial<Data>`...  🤔 Well i guess i figure that out.

**Comment by zehawki** [comment]
Ok, so is there a way I can add padding only to the existing plugins? Also #622 

I was using the following which works just fine for my purposes for text and images etc.

```
.react-page-cell-inner-leaf {
  padding: 32px 32px 0 32px;
}
```
However now I see that my custom (existing) components are also rendered inside this class (of course), and end up looking a bit weird due to this extra padding.

**Comment by macrozone** [comment]
> Ok, so is there a way I can add padding only to the existing plugins? Also #622
> 
> I was using the following which works just fine for my purposes for text and images etc.
> 
> ```
> .react-page-cell-inner-leaf {
>   padding: 32px 32px 0 32px;
> }
> ```
> 
> However now I see that my custom (existing) components are also rendered inside this class (of course), and end up looking a bit weird due to this extra padding.

as mentioned, you can always just wrap the `Renderer`. Additionaly there is a `cellStyle` function on every CellPlugin that you can define to set the style of the cell, its missing in the documentation, but you see it on the type here: https://github.com/react-page/react-page/blob/master/packages/editor/src/core/types/plugins.ts#L103

**Comment by zehawki** [comment]
Yup, for custom components I am creating - its clear. Obviously I have full control on that, either by wrapping the `Renderer,` or defined inside the component, or even (as you shows, there's a sweet little `cellStyle` prop.

I'm asking about setting the padding of the existing plugins ie background, image, and slate. How do I control their padding?
