### ISSUE TITLE
Massive number of nested DIVs

### ISSUE THREAD

**Issue by zehawki** [react-page/react-page#906]
Every block is created with a large number of nested DIVs, leading to a many DOM elements on the page.

A row has:
1. DIV with class react-page-row-droppable-container
2. Nested DIV with class react-page-row

Then into the cells:
3. DIV with class react-page-cell react-page-cell-sm-6 react-page-cell-xs-12
4. Another DIV inside
5. Nested DIV with class react-page-cell-droppable
6. Nested DIV with class react-page-row-droppable-container
7. Nested DIV with class react-page-row
8. Nested DIV with class react-page-cell react-page-cell-sm-12 react-page-cell-xs-12 react-page-cell-has-plugin react-page-cell-leaf
9. Another nested DIV inside
10. Nested DIV with class react-page-cell-droppable react-page-cell-droppable-leaf
11. Nested DIV with class react-page-cell-draggable-in-edit
12. Nested DIV with class react-page-cell-inner react-page-cell-inner-leaf
13. Another nested DIV inside
14. Another nested DIV inside

Then into text:
15. A < p >
16. A < span > inside
17. Another < span > inside
18. Yet another < span > inside

That's EIGHTEEN levels. Imagine with 100s of cells on a page, thats an incredible number of DOM elements,

**Comment by macrozone** [comment]
@zehawki its much less in read only mode: https://react-page.github.io/readonly, that's what end-users see and what is relevant for discussing performance.

There is certainly room for improvement, but i did not experience performance problems with that and programmers tend to overestimate the impact of dom nesting. There is probably other areas where you can get more improvements.

I close this as it is neither a bug nor a performance problem. Feel free to open new issues if you can point out real-world performance problems.
