### ISSUE TITLE
Minor issue - spacer shows a dotted border in read-only model

### ISSUE THREAD

**Issue by zehawki** [react-page/react-page#907]
A spacer shows a dotted line around it in read only mode. As shown in the image:

![image](https://user-images.githubusercontent.com/8095144/108602545-7778f000-73c8-11eb-8b1e-faf8230a73a7.png)

The same can be seen in the demo (https://react-page.github.io/readonly), at the bottom:

![image](https://user-images.githubusercontent.com/8095144/108602587-b27b2380-73c8-11eb-81f5-d9f7351b9c8e.png)

That's this piece of code:

`<div class="react-page-plugins-content-spacer" style="border: 1px solid rgba(0, 0, 0, 0.12);"><div style="height: 24px;"></div></div>`

**Comment by zehawki** [comment]
Workaround via a CSS override:

```
.react-page-plugins-content-spacer {
  border: unset!important;
}
```

**Comment by macrozone** [comment]
thank you, probably a bug i introduced recently.
