### ISSUE TITLE
Make BottomToolbar optional

### ISSUE THREAD

**Issue by avoskresensky** [react-page/react-page#909]
We use our own set of plugins with our own plugin controls. In version 0.x we had an ability to display our own toolbox, but we seem to have lost that ability in 1.x.

BottomToolbar is now always mounted inside the PluginComponent -- even when plugin.controls is null.

We suggest to mount BottomToolbar conditionally -- only when plugin.controls is set. That would allow us to have our own version of it mounted in the Renderer component.

**Comment by macrozone** [comment]
The bottom toolbar also contains tools independent of the plugin, like deleting cells, hiding cells in a language, check translation status and It will contain more in the future.

By removing it you would lose features. 

I would like to hear what you use in your custom toolbar? Remember that you can also use plugin.controls.type === "custom" to render something else in the BottomToolbar.

**Comment by avoskresensky** [comment]
We have our own implementation of the bottom toolbar controls.

Material UI doesn't work for us -- our application has a different look and feel, so we have our own implementation of all of the UI components: the bottom toolbar, the plugin drawer, the mode switcher.

In 0.x the entirety of the UI was sitting in a separate package which was just great from our perspective -- we only depended on the "core" and the "renderer". In 1.x some of the UI became incorporated into the main "editor" package which is not ideal from our perspective. But as long as we're able to suppress it and exclude the dependencies at the webpack level, we are okay.

**Comment by avoskresensky** [comment]
I totally understand your reasoning -- thanks for taking the time to explain.

> Feel free to post a proposal or Pull request! I am happy to help! Everything you need to create a custom Bottom Toolbar is now available as simple hooks, so it should not be complicated to create a custom BottomToolbar.

As I mentioned before, we already have everything in place. We can mount our version of the BottomToolbar inside our Renderer component, like we did in 0.x.

The only help we need right now is in suppressing the standard BottomToolbar that pops up regardless of what we do with "plugin.controls" setting.

My suggestion is to make a tiny modification to PluginComponent/index.tsx and make <BottomToolbar> element conditional on whether "plugin.controls" is null or not.

One unfortunate side effect of the change as proposed will be the need to add some sort of empty "controls" to the standard Divider plugin. So if that doesn't sounds like a good idea to you, another suggestion would be to add another "type" to "plugin.controls".

plugin.controls.type === "none"

**Comment by macrozone** [comment]
> My suggestion is to make a tiny modification to PluginComponent/index.tsx and make <BottomToolbar> element conditional on whether "plugin.controls" is null or not.

I would definitly not do that and instead make the BottomToolbar as a whole configurable. Also `type: "none` is not correct. The BottomToolbar is not (only) considered to be the control of the plugin, but for the cell itself (it has duplication button, delete button, hide button, language controls and I plan to add more as well like moving and resizing). `CellPlugin.controls` is just responsible for what is shown in the plugin area of the BottomToolbar.

**Comment by avoskresensky** [comment]
@macrozone, I'm just trying to find a way of not to have to maintain a separate repo of this project just for ourselves. But not being able to get rid of BottomToolbar in its entirety is a showstopper for us.

**Comment by macrozone** [comment]
@avoskresensky so you are invited to do a pull request which allows you to replace the BottomToolbar with a custom Component, its probably not that hard to do or you wait until I or someone else finds time to do that. I might have time later this week.

**Comment by avoskresensky** [comment]
@macrozone, I'll try to come up with something in the next couple of days

**Comment by macrozone** [comment]
i think that is solved now in the latest version. Feel free to reopen if there is still something amiss
