### ISSUE TITLE
Minor enhancements

### ISSUE THREAD

**Issue by zehawki** [react-page/react-page#910]
All the plugins have a single line explaining what is does, Would be good to add one for background as well. Eg:

description: 'Add a background color or image',

Image showing missing description:

![image](https://user-images.githubusercontent.com/8095144/108695987-f2f0b380-7526-11eb-9cb7-60d728b6cac2.png)

**Comment by zehawki** [comment]
Consider changing the current icon for toggling the size of the BottomToolbar control. It always makes me think that its controlling font size.

![image](https://user-images.githubusercontent.com/8095144/108696061-0d2a9180-7527-11eb-8e36-df3d11aeafc0.png)

to this perhaps: `'@material-ui/icons/Height';`

**Comment by zehawki** [comment]
Change some text appearing in the left selector panel:

![image](https://user-images.githubusercontent.com/8095144/108696441-8cb86080-7527-11eb-9685-148a124285b0.png)

The word "plugin" is too technical for the layperson. Consider changing to "block". Ie Add block to content, Search blocks, Content blocks

**Comment by zehawki** [comment]
Change some text appearing in the right control:

![image](https://user-images.githubusercontent.com/8095144/108696603-c8532a80-7527-11eb-91d0-d74dbb1d6729.png)

The word "things" can similarly be replaced by "blocks". This is a block editor and its creating and editing blocks on the page.

**Comment by macrozone** [comment]
agree with these proposals.

Translation overhaul is on the todo list anyway (see https://github.com/react-page/react-page/issues/865).

**Comment by macrozone** [comment]
> '@material-ui/icons/Height'



> Consider changing the current icon for toggling the size of the BottomToolbar control. It always makes me think that its controlling font size.
> 
> ![image](https://user-images.githubusercontent.com/8095144/108696061-0d2a9180-7527-11eb-8e36-df3d11aeafc0.png)
> 
> to this perhaps: `'@material-ui/icons/Height';`

That is also a bit confusing. 
I keep it for the moment as in https://github.com/react-page/react-page/issues/898 i want to add some new functionalities and I have to revisit the icons then.

**Comment by zehawki** [comment]
Yeah, just couldnt find anything better in material icons.... This '@material-ui/icons/AspectRatio'; is ideal, but already used for spacer.

**Comment by zehawki** [comment]
Another one: change text from "Loads an image from an url." to "Load image from local or URL"

**Comment by macrozone** [comment]
@zehawki feel free to post a Pull Request! i will gladly review & merge it!

**Comment by zehawki** [comment]
On it. (Sent the 1st PR for docs.)

**Comment by zehawki** [comment]
Released in [v2.0.1](https://github.com/react-page/react-page/releases/tag/v2.0.1)

**Comment by zehawki** [comment]
@macrozone some more stuff:

1. The icon is not showing up in the bottomtoolbar. This can be seen on the demo page.

![image](https://user-images.githubusercontent.com/8095144/114884091-1e0acb80-9e23-11eb-801a-a9ff0adb4f81.png)

![image](https://user-images.githubusercontent.com/8095144/114884242-3e3a8a80-9e23-11eb-83bc-ad811961683b.png)



2. A ugly scrollbar is showing on the panel, but only on my side and not in the demo. Any idea how to remove?

![image](https://user-images.githubusercontent.com/8095144/114883736-d08e5e80-9e22-11eb-88ba-6817c6413f81.png)

**Comment by thitipat-artisan** [comment]
@macrozone how to set default size bottomToolbars

**Comment by macrozone** [comment]
@zehawki 

> The icon is not showing up in the bottomtoolbar. This can be seen on the demo page.

wow, good catch, that was a typo in the code. Fixed in master!

> A ugly scrollbar is showing on the panel, but only on my side and not in the demo. Any idea how to remove?

tbh, no clue its probably from the overflow: auto. Do you happen to know what changes you have?

Please open up an issue with a reproduction if possible
