### ISSUE TITLE
data passed to cells is null instead of an empty object on newly added cells

### ISSUE THREAD

**Issue by zehawki** [react-page/react-page#912]
**Describe the bug**
Exception at run time when something has gone wrong in the underlying JSON data. I've faced 2 issues so far, both are similar. See also #764  by @PeterKottas 

**Expected behavior**
I strongly feel nothing should crash especially in `readonly` mode since that totally degrades the user experience. Instead there should be some graceful handling of such error, and affect only that plugin - so localized error handling.

**To Reproduce**
### 1. Missing key in background

The first is regarding the inbuilt plugin `react-page/plugins-background` and this occurred in standard use, without even trying to do anything funky - after a save, and reload, react-page kept crashing with the error:

```
Uncaught TypeError: Cannot read property 'darken' of undefined
    at BackgroundHtmlRenderer (BackgroundHtmlRenderer.tsx:95)
```

After various debugging, I narrowed it down to this bit:

```
      "id": "zknvlh",
      "cells": [
        {
          "id": "5u9hgf",
          "size": 12,
          "plugin": {
            "id": "ory/editor/core/layout/background",
            "version": 1
          },
          "dataI18n": {
            "default": null
          },
```

Somehow the default key under dataI18n had become null. Manually changing this to 

```
            "default": {
              "darken": 0.57
            }
```

made the issue go away.

But how and why did this key disappear? The page has 3 backgrounds, and only 1 had the missing key.

### 2. Missing key in a custom plugin

I created a custom plugin without `controls` and saved. So obviously the default is null:

```
          "id": "c5eri6",
          "size": 12,
          "plugin": {
            "id": "contact-form",
            "version": 1
          },
          "dataI18n": {
            "default": null
          },
```

Then I added an autoform, with a field called `blurb` and tried to use that in the Renderer as:

```
  Renderer: ({ data }) => {
    return <ContactForm blurb={data.blurb} />
  },
```

In this case, though technically there is no error, react-page crashes since for the earlier saved JSON, there is no data.blurb key. This is understandable, and perhaps migration will solve this, nevertheless it shouldnt crash.

**Comment by PeterKottas** [comment]
Sadly focused more on business these days than joys of coding :-) Anyways, first is an easy fix. [This](https://github.com/react-page/react-page/blob/master/packages/plugins/layout/background/src/Renderer/BackgroundHtmlRenderer.tsx#L100) needs default initialization. Feel free to file a PR, great things happen to your karma when you contribute here :P

The second, I would call userland error. Since we internally don't know your schema (a design decision to keep things simple), it makes more sense for you to handle errors. Eg, either initialize "data" to something meaningful or at least access blurp like this:
```
data?.blurp || ''; // Or whatever that is a meaningful default for blurp.
```

Hope that helps.

**Comment by zehawki** [comment]
Agree and disagree with what you said :-)

Re # 2 - The fix is obvious once its been seen in dev. I've already made that change and rolled it out. That's fine and not the point.

Same with # 1 - you are able to suggest a fix since we've seen the issue and debugged it.

But looking forward - its entirely possible that various changes made in the core, may end up crashing someone's page on some day in the future and so on. Like # 2 which is a bug and has been since whenever.

So the end user who uses this to create a page, may, without warning, find a crash and not know whats going on. The page itself wont load and all the user gets is a blank screen. And the debugging is no easy task - imagine looking thru the entire JSON to figure out what 1 bit caused the crash.

Isn't it so much more elegant to deal with this at the plugin level, such that there is a common behavior for all plugin (built in or custom) error handling, a point I believe you were making in #764. The error is handled gracefully, and something is written to console or a call back foo is called for sending the crash info somewhere etc etc,...

**Comment by PeterKottas** [comment]
Yeah, what I said here is IMHO not in contradiction to what you're saying or what lives in #764. I strongly believe that should be done (on top of general error handling on plugin level of course). We did this via some error boundaries. I think @macrozone already contributed this into the core. I haven't seen the code though. AFK not sure if it's plugin level. I think so though. Bottom line, all you can do is at least only "crash" the plugin not the whole tree (that is if the plugin doesn't handle the error gracefully). Tbh one way or another, users will not like it. So I assume the strategy here is to stick to the same schema and only make changes if you really really need them and understand the implications. Also, pure renderer should simply ignore broken stuff. Thus avoiding the blank screen issue. Once again, I thought this was already done via the code Marco contributed.

Howevetr, you are somewhat incorrectly saying that 

> But looking forward - its entirely possible that various changes made **in the core**, may end up crashing someone's page on some day in the future and so on.

I disagree here as it's almost never core that is broken (if the core is broken you should file an issue and revert to the older version until it's fixed). Just like if they broke react in some version for instance. It's almost always the plugin that misbehaves. The confusion is the plugins are in the "core repo". In an ideal world, they shouldn't be. Hence this problem would land in a much smaller background plugin repo, where somebody could contribute some error handling (or default values for the state which is the usual culprit).

**Comment by zehawki** [comment]
Got it. I used "core" loosely to mean "core  + inbuilt plugins"

**Comment by PeterKottas** [comment]
Yeah, that's the issue. Slate managed to solve this very nicely. They were fortunate enough to be widely used and big enough to simply just kick everything "not core" out and let people pick it up elsewhere. Can't really do this here as we are more niche. But it certainly leads to some confusion. Maybe an opportunity to create a known issues section or something like that.

**Comment by zehawki** [comment]
> Silver lining: Core here is much more stable and mature than it might seem initially. Some peace of mind for you maybe :-)

I know exactly what you mean. This one is a gift from the universe. https://github.com/react-page/react-page/discussions/905

**Comment by macrozone** [comment]
when a cell has no data, it passes `null`. It used to be an empty object in earlier versions. I changed that deliberatly, but to be honest, i don't remember why.

I guess i had the impression that we would also allow non-objects for the data-type, but that makes little sense, so the type has now to be a `Record<string, any>`. In this sense an empty Record would be more convenient than null.

I'll check if I can change that back

**Comment by zehawki** [comment]
And I hit this again :-(

Marco, possible to fix this and release? I don't yet feel confident on touching anything inside the code.

![image](https://user-images.githubusercontent.com/8095144/109148642-88d94800-778c-11eb-9645-a4cd85cc5de7.png)

**Comment by macrozone** [comment]
@zehawki can you try version 1.0.6 ? I quickfixed it in the background plugin

**Comment by zehawki** [comment]
I'm fairly certain I'm already on 1.0.6:

```
"@react-page/editor@^1.0.1", "@react-page/editor@^1.0.6":
  version "1.0.6"
  resolved "https://registry.npmjs.org/@react-page/editor/-/editor-1.0.6.tgz#6fad8ba56fe4965d69bd256c0b8390b9e317d055"
  dependencies:
    "@loadable/component" "^5.14.1"
    "@welldone-software/why-did-you-render" "^6.0.5"
    ajv "^7.1.1"
    classnames "^2.2.6"
    fast-deep-equal "^3.1.3"
    is-hotkey "~0.1.6"
    lodash.debounce "^4.0.8"
    lodash.flatten "^4.4.0"
    lodash.throttle "^4.1.1"
    react-color "^2.19.3"
    react-dnd "^11.1.3"
    react-dnd-html5-backend "^11.1.3"
    react-draggable "4.4.3"
    react-portal "^4.2.1"
    react-redux "^7.2.2"
    react-use "^17.1.1"
    redux "^4.0.5"
    redux-thunk "^2.3.0"
    redux-undo "^1.0.1"
    uniforms "^2.6.0 || ^3.0.0"
    uniforms-bridge-json-schema "^2.6.0 || ^3.0.0"
    uniforms-material "^2.6.0 || ^3.0.0"
```

**Comment by macrozone** [comment]
sorry, i meant 1.0.7 or newer

**Comment by macrozone** [comment]
see https://github.com/react-page/react-page/releases

**Comment by macrozone** [comment]
should now be fixed
