### ISSUE TITLE
When drag / drop / move cell, next one up gets highlighted

### ISSUE THREAD

**Issue by mlbrgl** [react-page/react-page#915]
When drag / dropping a cell left or right in a row, the one above gets highlighted (unless highlight recaptured by current cell).

**Expected behavior**
Ideally, no cell gets highlighted (not even the cell being dropped), unless a new mouse mouvement is registered after the drop of the cell on mouse up.

**Screenshots**
In this example, the "React page works..." cell should not be highlighted.

https://user-images.githubusercontent.com/13406362/109160800-8cfa6b00-7776-11eb-8d0e-773ae2bc3513.mov

**Additional context**
Follow up to https://github.com/react-page/react-page/issues/898#issuecomment-785802699

**Comment by macrozone** [comment]
thats odd, i also see it. But its weird, because this highlight is just a :hover css effect. 

i think when dropping, the cell that was behind your mouse cursor picks up the ":hover" state or so

**Comment by macrozone** [comment]
maybe something like https://stackoverflow.com/questions/11989289/css-html5-hover-state-remains-after-drag-and-drop
