### ISSUE TITLE
Cell spacing (grid gutters)

### ISSUE THREAD

**Issue by avoskresensky** [react-page/react-page#918]
Add an ability to have cell spacing (grid gutters).

Currently the only way to add something like that would be via .react-page-cell-inner-leaf padding (as it is done in the examples). This solution is very simple and straightforward, but has the following problems:
- padding is added to the outside perimeter of the grid (including nested grids)
- if a plugin has any chrome (content on a card, a border etc) this starts to look weird
- won't work on backgrounds sitting in a row next to each other or any other layout plugins

We would like to be able to specify cellSpacing as an Editor prop (`number | number[]`). Ideally we would also like to be able to override this property inside a layout plugin to have different cell spacing in the nested grid.

The flexboxgrid that the CSS is based on had a part of that functionality built in via --gutter-width property. Applying padding to .react-page-cell and a negative margin to .react-page-row seems to do the trick for horizontal gutters.

Vertical gutters are trickier and require some additional checks, but the general idea is still the same: padding + negative margin.

We would like to propose a fairly straightforward implementation:
https://github.com/react-page/react-page/compare/master...avoskresensky:cell-spacing-v1

This is just a demonstration of the approach and it lacks certain features like HTMLRenderer modifications, separate horizontal/vertical settings for cellPadding, some drag-and-drop guides are misaligned etc.

If the general idea is acceptable, we can finalize the PR.

**Comment by macrozone** [comment]
@avoskresensky its already possible to set the cell style for a CellPlugin:

```
 cellStyle: {
    padding: 0,
  },
```

so you can "globally" set the padding with css and override it for certain cellPlugins

https://github.com/react-page/react-page/blob/master/packages/plugins/layout/background/src/createPlugin.tsx#L31
https://github.com/react-page/react-page/blob/master/examples/pages/examples/constraints.tsx#L30

**Comment by avoskresensky** [comment]
@macrozone, cell padding is not gutters. In order to become gutters it needs to be compensated around the grid. That's what the negative margin is for.

Also, as I mentioned above there is a cosmetic matter of being able to highlight just the contents of the cell -- not the cell plus its adjoining "gutters".

**Comment by macrozone** [comment]
you can also set negative margin with `cellStyle` its applied to the outer div.

**Comment by avoskresensky** [comment]
@macrozone, negative margin needs to be applied on enclosing element -- a row in case of horizontal gutters. See the flexgrid CSS. With vertical gutters the compensation is even trickier.

**Comment by avoskresensky** [comment]
@macrozone, another issue is illustrated by this screenshot.

![image](https://user-images.githubusercontent.com/10179521/109626346-49e12480-7af5-11eb-89a0-c7b83bf0f9c6.png)

Green rectangles are those outside divs that cellStyles are applied at. Red rectangles are the padded cells.
The layout is slate + background with padding and slate inside + slate.

Without any compensation (via a negative margin or otherwise), background plugin's padding grew taller and wider than desired.

**Comment by macrozone** [comment]
i see, 

i saw your PR but i was a bit reluctant because there were some significant changes in the layout and i hope it does not break anything.

you can open the PR here and then we can look over it.

**Comment by avoskresensky** [comment]
@macrozone, we tried to keep the layout changes to the minimum. The only really significant one (in my opinion) is the split of .react-page-cell into two divs -- the outer one gets all the paddings and the inner one gets highlighted on cell selection.

I'm going to send the PR as it is now, so we could discuss.
It needs some more cosmetic work around resize and drop placeholders. Also HTMLRenderers need to be modified accordingly.

**Comment by macrozone** [comment]
@avoskresensky there is one layout problem:

<img width="1020" alt="Bildschirmfoto 2021-03-09 um 11 33 04" src="https://user-images.githubusercontent.com/1972353/110457794-4e947280-80cb-11eb-837b-ee2a7df38d7d.png">

inline elements no longer float correctly

also on mobile there is something wrong there:

<img width="1340" alt="Bildschirmfoto 2021-03-09 um 11 34 28" src="https://user-images.githubusercontent.com/1972353/110457908-71bf2200-80cb-11eb-9067-a03ba66eed3b.png">



can you fix that?

**Comment by macrozone** [comment]
@aeneasr it still does not float in read only mode:

https://react-page.github.io/beta/readonly

compare:

https://react-page.github.io/readonly

**Comment by macrozone** [comment]
@avoskresensky i did not yet check if it works in my projects, but does the beta version work for you? If so i will release it soon

**Comment by avoskresensky** [comment]
@macrozone , we don't have this version in production yet, but in our development it works as expected.

Since I have you on the line, let me share one observation regarding a different recent modification:

```
const optionsMemoized: Options = useMemo(() => {
    return {
      cellPlugins,
      pluginsWillChange,
      allowMoveInEditMode,
      allowResizeInEditMode,
      editModeResizeHandle,
      languages,
      childConstraints,
      components,
    };
  }, [
    pluginsWillChange && cellPlugins,
    allowMoveInEditMode,
    allowResizeInEditMode,
    editModeResizeHandle,
    languages,
    JSON.stringify(childConstraints ?? {}), // its an object, we prevent unnecessary rerenders by stringify it
    ...Object.keys(components ?? {}),
    ...Object.values(components ?? {}), // minimize unnecessary rerenders by forcing shallow comparison of "components" object
  ]);
```

If "components" are added/removed after the Editor was created, react complains:

```
The final argument passed to useMemo changed size between renders. The order and size of this array must remain constant.
```

**Comment by macrozone** [comment]
> @macrozone , we don't have this version in production yet, but in our development it works as expected.
> 
> Since I have you on the line, let me share one observation regarding a different recent modification:
> 
> ```
> const optionsMemoized: Options = useMemo(() => {
>     return {
>       cellPlugins,
>       pluginsWillChange,
>       allowMoveInEditMode,
>       allowResizeInEditMode,
>       editModeResizeHandle,
>       languages,
>       childConstraints,
>       components,
>     };
>   }, [
>     pluginsWillChange && cellPlugins,
>     allowMoveInEditMode,
>     allowResizeInEditMode,
>     editModeResizeHandle,
>     languages,
>     JSON.stringify(childConstraints ?? {}), // its an object, we prevent unnecessary rerenders by stringify it
>     ...Object.keys(components ?? {}),
>     ...Object.values(components ?? {}), // minimize unnecessary rerenders by forcing shallow comparison of "components" object
>   ]);
> ```
> 
> If "components" are added/removed after the Editor was created, react complains:
> 
> ```
> The final argument passed to useMemo changed size between renders. The order and size of this array must remain constant.
> ```

that's interesting, i did not know that the deps array has to have a fixed length. What would solve it i think is that we merge components with an object with all possible components as keys and value null each, so that the object has a fixed size and therefore the created arrays have. a fixed size. 

Maybe there is a different way alltogether to solve this. (In future, immutable records might help)

Do you have an idea?

**Comment by avoskresensky** [comment]
@macrozone , internally in our projects we decided not to go this "clever dependencies" route. The runtime penalty associated with this, the incompatibility with `react-hooks/exhaustive-deps` linting -- all that steered us away at the end.

Instead we solve this though a combination of typings (for callbacks) and developer mode checks for everything else.
The latter is a combination of `welldone-software/why-did-you-render` and a couple of ad-hoc checks at critical places.

**Comment by macrozone** [comment]
@avoskresensky i tried to update our project with the beta. i noticed that we broke the existing gutter mechanism.

We had this:

```
.react-page-row {
    /** react-page **/
    --outer-margin: 15px;
    --half-gutter-width: 15px;
    --gutter-width: 30px;
    --gutter-compensation: -15px;
}
```

This no longer works, as the cell now receives a padding of 0.

Maybe we remove setting padding if its 0?

or we release it as breaking change, but we should make sure to remove the above css variables because they are useless now

**Comment by macrozone** [comment]
the bigger problem is, that its no longer possible to have different gutter spacing based on media queries. For me thats currently not a requirement, but i fear that it might come up. what do you think?

**Comment by avoskresensky** [comment]
@macrozone, 

We do overwrite the CSS settings unconditionally. I sorta though that those horizontal gutters were just the relic of the original flexboxgrid project which is no longer used.

One can return them back to life right now by adding "!important" at all the places where --half-gutter-width and --gutter-compensation are used, but that's hardly a nice solution.

What we can and probably should do though, is refraining from generating any inline padding/margin styles in case cellSpacing is not explicitly set.

**Comment by macrozone** [comment]
> Edit: And your project should look the same as before if you set cellSpacing to {x: 15, y: 0}

yes, verified that, looks good! I will add a message in the changelog to highlight this.

Will it release soon

**Comment by zehawki** [comment]
>the bigger problem is, that its no longer possible to have different gutter spacing based on media queries. For me thats currently not a requirement, but i fear that it might come up. what do you think?

This is certainly a requirement - bigger screen = bigger gutters etc.
