### ISSUE TITLE
Cannot have two HTML5 backends at the same time.

### ISSUE THREAD

**Issue by vsachini** [react-page/react-page#929]
I'm not sure if I'm doing something wrong. I'm using the Editor on 2 screens and both are working fine, but when I go to another screen that has a **useEffect** I get this error. Removing the useEffect fix this issue. Is that the right way to use it?

My component:

```
import React from 'react'
import Editor, { Value } from '@react-page/editor'
import { makeStyles } from '@material-ui/core'

import slate from '@react-page/plugins-slate'
import '@react-page/editor/lib/index.css'

import '@react-page/plugins-slate/lib/index.css'

import background from '@react-page/plugins-background'
import '@react-page/plugins-background/lib/index.css'

import spacer from '@react-page/plugins-spacer'
import '@react-page/plugins-spacer/lib/index.css'

import { imagePlugin } from '@react-page/plugins-image'
import '@react-page/plugins-image/lib/index.css'

import video from '@react-page/plugins-video'
import '@react-page/plugins-video/lib/index.css'

const useStyles = makeStyles(() => ({
  root: {
    margin: '2em 0',
    minHeight: 500,
  },
  readOnly: {
    margin: '4em 0',
    minHeight: 'unset',
  },
}))
const TextEditor: React.FC<{
  content: Value | undefined
  onUploadMedia: (file: File) => Promise<{ url: string }>
  onChange: (e: Value) => void
}> = ({ content, onUploadMedia, onChange }) => {
  const classes = useStyles()

  const handleChange = (e: any) => {
    onChange(e)
  }

  const handleUploadMedia = async (file: File) => {
    const result: { url: string } = await onUploadMedia(file)
    return result
  }

  const cellPlugins: any = [slate(), imagePlugin({ imageUpload: handleUploadMedia }) as any, video, spacer, background({})]

  return (
    <div className={classes.root}>
      <Editor
        cellPlugins={cellPlugins}
        value={content}
        onChange={handleChange}
        allowResizeInEditMode={true}
        allowMoveInEditMode={true}
      />
    </div>
  )
}
```

**Expected behavior**
useEffect fetch data after change screen;

**Screenshots**
<img width="580" alt="image" src="https://user-images.githubusercontent.com/51142321/111721226-68d40a80-889a-11eb-931e-353c7806c67e.png">

**Comment by macrozone** [comment]
- can you show the code where it is failing?
- can you check whether your application uses react-dnd? (react drag and drop)
- you should not re-initialize `cellPlugins` and `onChange` in every render as it will rerender the whole editor on every change. Either put them outside as constants or useMemo

**Comment by vsachini** [comment]
@macrozone  Thanks for the help. Just fixed the cellPlugins and onChange.

I'm using mui-datatables on the other screen that is failing and noticed that it has react-dnd as dependency:

`npm view mui-datatables dependencies                                                  
{
  '@babel/runtime-corejs3': '^7.12.1',
  clsx: '^1.1.1',
  'lodash.assignwith': '^4.2.0',
  'lodash.clonedeep': '^4.5.0',
  'lodash.debounce': '^4.0.8',
  'lodash.find': '^4.6.0',
  'lodash.get': '^4.4.2',
  'lodash.isequal': '^4.5.0',
  'lodash.isundefined': '^3.0.1',
  'lodash.memoize': '^4.1.2',
  'lodash.merge': '^4.6.2',
  'prop-types': '^15.7.2',
  'react-dnd': '^11.1.3',
  'react-dnd-html5-backend': '^11.1.3',
  'react-sortable-tree': '^2.7.1',
  'react-to-print': '^2.8.0'
}`

**Comment by macrozone** [comment]
> @macrozone Thanks for the help. Just fixed the cellPlugins and onChange.
> 
> I'm using mui-datatables on the other screen that is failing and noticed that it has react-dnd as dependency:
> 
> `npm view mui-datatables dependencies { 'react-dnd': '^11.1.3', 'react-dnd-html5-backend': '^11.1.3', }`

alright, there is a way to share the dnd backend, but let me check

**Comment by vsachini** [comment]
@macrozone  do you know how can I share the backend?

**Comment by macrozone** [comment]
@vsachini 

on `<Editor />` you can pass a `dndBackend`:

`<Editor dndBackend={HTML5Backend} />`

i guess you have to pass the same dndbackend that you also pass to mui-datatables, see https://github.com/gregnb/mui-datatables#custom-components

```
<MUIDataTable
                columns={columns}
                data={data}
                components={{
                  DragDropBackend: HTML5Backend,
                }}
            />
```

where`HTML5Backend` is

```
import { HTML5Backend } from 'react-dnd-html5-backend';
```

i guess that is a singleton with some internal state.

You can also check your yarn.lock or package-lock file if you have multiple versions of react-dnd and maybe you can dedupe that if the version ranges check out.

**Comment by vsachini** [comment]
Thanks @macrozone! I will do some tests on that.
