### ISSUE TITLE
How to custom styles display mode toggle bar and drawer same bottomToolBar

### ISSUE THREAD

**Issue by thitipat-artisan** [react-page/react-page#932]
current override style in css file is work for development but production or yarn build and start is not work class name is change 
Ex. reactPage-MuiFab-secondary => reactPage-reactPage

**Comment by macrozone** [comment]
@thitipat-artisan hi! What do you try to achieve? maybe there is a better solution

**Comment by thitipat-artisan** [comment]
How to custom or override theme color

ในวันที่ ศ. 26 มี.ค. 2021 18:09 Marco Wettstein ***@***.***>
เขียนว่า:

**Comment by macrozone** [comment]
@thitipat-artisan its not fully possible yet, but i plan to add ability to pass a (Mui)-theme to the editor very soon.

**Comment by thitipat-artisan** [comment]
@macrozone thank you.

**Comment by 643364103** [comment]
@macrozone   I have many custom plugins,so i need  custom the drawer to change it's layout. But now I can't custom the drawer. 
If the drawer can be custom,it would be a great feature.

**Comment by thitipat-artisan** [comment]
@643364103 Version 1.7.0 can custom ui elements.

**Comment by 643364103** [comment]
@thitipat-artisan sorry,i only know it can custom bottomtoolbar.How to custom drawer? Do you have any example? Thank you,most~

**Comment by thitipat-artisan** [comment]
@643364103 https://github.com/react-page/react-page/blob/master/examples/pages/examples/customEditorChildren.tsx maybe help you.

**Comment by macrozone** [comment]
> @macrozone I have many custom plugins,so i need custom the drawer to change it's layout. But now I can't custom the drawer.
> If the drawer can be custom,it would be a great feature.

what do you actually want to change / customize?

**Comment by 643364103** [comment]
@macrozone  yes,I want to classify the plugins, and then users can filter out the plugins by classification

**Comment by macrozone** [comment]
> @macrozone yes,I want to classify the plugins, and then users can filter out the plugins by classification

can you open up another issue and specify exactly what you need? I think it has nothing to do with styling the display mode toggle

**Comment by 643364103** [comment]
@thitipat-artisan Thank you. customEditorChildren.tsx is custom toolbar but not drawer

**Comment by 643364103** [comment]
@macrozone ok,I will.

**Comment by rexebin** [comment]
> @thitipat-artisan Thank you. customEditorChildren.tsx is custom toolbar but not drawer

The idea is that you could inject a whole new drawer component, because all the react-page internal hooks and commands are available. It doesn't have to be a drawer, it can be a toolbar, a menu, a modal etc.

**Comment by 643364103** [comment]
@rexebin Thanks, I should to try the feature.
