### ISSUE TITLE
Slate Error: Cannot resolve a Slate point from DOM point

### ISSUE THREAD

**Issue by rexebin** [react-page/react-page#936]
**Describe the bug**
Delete initial content in a slate cell and start typing any Chinese characters will break the cell and throw an error: `Cannot resolve a Slate point from DOM point: [object Text],2`. Number 2 is the number of characters I was trying to type.

It is a slate bug being caught, and `ErrorCell` is kicked in. 

Related slate issue: https://github.com/ianstormtaylor/slate/issues/4136 (hint from there: no placeholder text no error)

**To Reproduce**
1. Go to the `react-page` demo page
2. Choose any slate editor or create a new one
3. Make sure there is some content in it, then delete everything, so the cell placeholder text is showing
4. Type Chinese characters with Microsoft Pinyin Input Method(IME), or other IMEs
5. Error thrown

**Expected behaviour**
No error should throw.

**Screenshots**
![error](https://user-images.githubusercontent.com/10893959/112732425-c965e600-8f31-11eb-9ee6-38703290381e.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome
 - Version 89.0.4389.90 (Official Build) (64-bit)

**Additional context**
All errors should be handled at development time. A red error block with a `Remove` button is not very friendly to the app users. I tried to comment out `ErrorCell` in `CellErrorGate` component, the same error throws in the console and nextjs throws. The slate cell, however, can still be used without issues. The typings that cause the error didn't appear. As an end-user, I think I would rather see a nice error message somewhere and continue to use the cell if it still works.

**Comment by rexebin** [comment]
@macrozone would be best if this bug can be fixed, it may require a PR on the slate repo. It is really not a `react-page` bug.  
Do you consider refactor the `CellErrorGate` component: 
1. maybe allow us to provide our own cell error handler. I would want the `children` rendered regardless, though...maybe passed the `children` to the handler and allow us to return something for the `render` method in the `CellErrorGate` component.
2. or allow us to skip the `CellError.`

**Comment by rexebin** [comment]
Chromium (89.0.4389.90 (Official Build) snap (64-bit)) on ubuntu 20.04 doesn't have this error.

**Comment by macrozone** [comment]
@rexebin i know that a similar error happens when there is a selection, but the content is deleted. I thought we fixed these problems. Can you check if its only related to chinese characters?

**Comment by h-sakano** [comment]
The same problem occurs when multibyte characters are entered immediately after an inline element, as shown below.

![output](https://user-images.githubusercontent.com/26650149/116025298-1e109400-a68b-11eb-9605-1c74285b9dfe.gif)
