### ISSUE TITLE
Two rows in a non-plugin cell cause the editor to mistakenly suggest there is a parent

### ISSUE THREAD

**Issue by avoskresensky** [react-page/react-page#943]
**Describe the bug**
In a configuration where there are two rows in a non-plugin cell, the editor suggests to "select a parent" while no such parent exists.

**To Reproduce**
1. Add three slate plugins in the following configuration:
![image](https://user-images.githubusercontent.com/10179521/113546346-a88c3900-95a0-11eb-9195-152f87f22d1e.png)
(two cells on top of each other in the left column, one cell in the right column)
2. Select one of the two plugins in the left column
3. Observe there is a "select parent" button in the drawer
4. Clicking this button selects something that is not a plugin cell

In this configuration this problem is just a nuisance, but if we put this layout inside a Background plugin, this bug makes it impossible to select the actual parent (Background) from one of those two left column cells. Here is what gets selected instead:
![image](https://user-images.githubusercontent.com/10179521/113546761-7af3bf80-95a1-11eb-8ee6-f0a87cdbe6ce.png)

**Expected behavior**
The search for the parent plugin should skip non-plugin cell containers.

**Comment by macrozone** [comment]
i'll check

**Comment by macrozone** [comment]
@avoskresensky ok, i'll analyzed it. There is another cell there that gets selected, but it has no plugin and currently it does not show the bottom toolbar.

I'll skip that cell now (is currently beeing built for version 1 and beta (2)

**Comment by macrozone** [comment]
fixed in 1.5.1 and 2.0.0-beta.9
