### ISSUE TITLE
Being able to drop a plugin into an empty layout plugin

### ISSUE THREAD

**Issue by avoskresensky** [react-page/react-page#944]
**Is your feature request related to a problem? Please describe.**
Right now it seems to be impossible to drop a plugin into an empty layout plugin. The only way to add content to an empty layout plugin seems to be using the "+" button.

**Describe the solution you'd like**
It would probably be ideal to have the "insert-new" component as a drop target. Highlighting and all.

**Comment by macrozone** [comment]
i know, i actually failed to implement that correctly ;-) Maybe i give it another try now, because i run into that problem just yesterday myself

**Comment by macrozone** [comment]
ok fixed in beta and master (currently building)

i also increased the size of the insert new to 50%

**Comment by macrozone** [comment]
fixed in 1.6.0
