### ISSUE TITLE
useDebouncedCellData bug

### ISSUE THREAD

**Issue by avoskresensky** [react-page/react-page#948]
**Describe the bug**
`useDebouncedCellData` has a bug that causes it to "forget" updates that get overrun by further updates within the 200 ms debounce timeout.

**To Reproduce**
Perform two plugin state updates within 200 ms of each other. The first one will get lost.
In order for the bug to manifest, React state batching must be in effect. This is the most common case, but to make sure, wrap those two update calls inside `ReactDOM.unstable_batchedUpdates`.

This happens because of a bug in `useDebouncedCellData`:

```
const [data, setData] = useState(cellData);
const dataRef = useRef(data);
dataRef.current = data;
```

You can do this to props, but it won't work for the state because of state batching. React won't rerender in between setState calls, so this hook won't be called, and this code won't have a chance to update the state ref. The ref update must happen right before setState inside the onChange function that gets returned to the user:

```
const [data, setData] = useState(cellData);
const dataRef = useRef(data);

const onChange = useCallback((update) => {
    dataRef.current = {...dataRef.current, ...update};
    setState(dataRef.current);
}, [setData]);

return [data, onChange];
```

It makes a lot of sense to return `dataRef` instead of just `data` from this hook, but that's a different story.

Edit:

Another, somewhat smaller problem with useDebouncedCellData is that it returns a referentially unstable onChange function which is not what you usually expect from a hook. onChange needlessly depends on `data` which can be easily helped since there is a ref there.

**Comment by macrozone** [comment]
can you fix it?

the current code is the result of dealing with these kind of issues, and it worked very well so far, but is probably far from beeing correct..

**Comment by avoskresensky** [comment]
> can you fix it?

Sure. Will send a PR shortly.
