### ISSUE TITLE
Allow certain blocks to be show / hidden based on material media breaks

### ISSUE THREAD

**Issue by zehawki** [react-page/react-page#954]
It would be very useful to have a selector per block that allows it to be enabled / disabled based on screen size. A simplistic approach could be selection just between mobile and larger screens and a more complex approach could be selectors based on all the media breaks - xs, sm etc.

This would allow use cases like this to be realized:
1. Blocks designed separately for small screens and larger screens and the selector would determine which one shows up
2. Show a certain block on a mobile while hiding on a larger screen, or vice versa

**Comment by macrozone** [comment]
you can already kindof hide a cellPlugin by using media queries, but that would still render an empty cell, not sure if that is good enough.

I'd also like to introduce a property to define the component for the cell itself at some point
