### ISSUE TITLE
Module not found: Can't resolve 'react/jsx-runtime' in '...\node_modules\react-dnd\dist\esm\core'

### ISSUE THREAD

**Issue by zehawki** [react-page/react-page#961]
**Describe the bug**
Unable to compile with error: Module not found: Can't resolve 'react/jsx-runtime' in '...\node_modules\react-dnd\dist\esm\core'

**To Reproduce**
1. Upgrade this package to latest (including plugins)

**Comment by macrozone** [comment]
delete node_modules
run yarn install or npm install agin

**Comment by zehawki** [comment]
OK. I'm also updating CRA scripts to 4+ to see if that helps.

**Comment by zehawki** [comment]
And that has taken me down a different rabbithole https://github.com/facebook/create-react-app/issues/9870

**Comment by zehawki** [comment]
>delete node_modules
run yarn install or npm install agin

Nope. Still same error

**Comment by zehawki** [comment]
Would this be something on your side? As per this https://stackoverflow.com/questions/65913201/uncaught-error-cannot-find-module-react-jsx-runtime

**Comment by zehawki** [comment]
And here: https://github.com/react-dnd/react-dnd/issues/3137

**Comment by zehawki** [comment]
Well solved with this https://github.com/adazzle/react-data-grid/issues/2230 (I was on version "16.13.1")

**Comment by macrozone** [comment]
how did you solve it? i think you should try to upgrade to react 17.x. and latest create-react-app

I did not see the error on my apps (all nextjs)

**Comment by zehawki** [comment]
By upgrading to react 16.14.0 from 16.13.1, as suggested in that comment I shared (https://github.com/adazzle/react-data-grid/issues/2230#issuecomment-781937689)

**Comment by macrozone** [comment]
the problem is as it seems that react-dnd switched to jsx-factory in this release https://github.com/react-dnd/react-dnd/releases/tag/13.0.0

and that seems to require react 16.14.

react-dnd correctly declares react 16.14 as min peer dependency.

We should also bump the min version to 16.14.


i also recommend to try to upgrade to react 17 already. I did not experience any problem with it.

**Comment by zehawki** [comment]
> i also recommend to try to upgrade to react 17 already. I did not experience any problem with it.

A bit afraid to do yet that since I have a really huge project on my side.

**Comment by Goutham0931** [comment]
Solved in my case.
Giving it as "latest" rather than mentioning version in package,json dependencies
"@emotion/react": "latest",
    "@emotion/styled": "latest",
    "@material-ui/core": "latest",
    "@material-ui/icons": "latest",
