### ISSUE TITLE
Consider switching to react-jsonschema-form from vazco / uniforms

### ISSUE THREAD

**Issue by zehawki** [react-page/react-page#966]
**Is your feature request related to a problem? Please describe.**

Each of the cellPlugins need various fields to be entered by the user, ie forms which are the bedrock of user input. This is currently realized with Uniforms. I would like to be able to show headings / help text / error messages etc for the form inputs on the cellPlugin control panel and this cannot be realized by Uniforms.

**Describe the solution you'd like**

Vazco / uniforms has a lot of limitations - it is not fully controllable from the schema and instead needs code (component) changes even to realize simple things like headings, help text for fields, error messages. See https://github.com/vazco/uniforms/discussions/912. The complicated solution from uniforms is this: https://uniforms.tools/docs/tutorials-customizing-your-form-layout.

Also the playground and docs of Uniforms is very limiting, without any details about the schema - https://github.com/vazco/uniforms/discussions/916

I'm proposing that we use react-jsonschema-form instead. Of course this might be a huge impact on the code, not to mention backward compatibility aspects.

Nevertheless, perhaps its worth discussing.

**Comment by zehawki** [comment]
As a practical example, here's a Blurb plugin: 

![image](https://user-images.githubusercontent.com/8095144/114887368-04b74e80-9e26-11eb-937c-0088a4626a34.png)

Now I want to be able to have a helptext for the "outside margin" field that says something as follows: _No value uses default outside margin._

I dont see a way to do that using Uniform's schema.

**Comment by macrozone** [comment]
you can show a helpertext simply with:

```
schema: {
  type: "object",
  properties: {
    outsideMargin: {
      type: "number",
      uniforms: {
        helperText: "No value uses default outside margin",
      },
    },
  },
};


```

**Comment by zehawki** [comment]
Oh nice. Is there something for headings and error messages as well?
