### ISSUE TITLE
Hardcoded zIndex on BottomDrawer Paper makes it unusable in Mui Dialogs. Consider exposing paper props on BottomToolbar

### ISSUE THREAD

**Issue by hinsxd** [react-page/react-page#970]
In line https://github.com/react-page/react-page/blob/70ed998b98e6c063e36892874d857cf2a1c4442f/packages/editor/src/ui/BottomToolbar/Drawer.tsx#L52-L54, there is no way to change the zIndex of the drawer's paper. 

Currently we are using 
```tsx
<Editor
  components={{
    BottomToolbar: CustomToolbar,
  }}
  cellPlugins={cellPlugins}
  value={value}
  onChange={(value) => setValue(name, value)}
/>;
const useStyles = makeStyles({
  drawer: {
    "&, & > *": {
      // Passed to MuiPaper
      zIndex: `1200 !important`,
    },
  },
});
const CustomToolbar = memo<BottomToolbarProps>((props) => {
  const classes = useStyles();
  return <BottomToolbar {...props} className={classes.drawer} />;
});
```
as a workaround.

Perhapes exposing `PaperProps`, or even all other styling options would be more convenient to style the drawer

**Comment by macrozone** [comment]
it needs to have a certain z-index. In which case did you have problem with it? Slate also uses dialogs and i did not observe a problem

**Comment by hinsxd** [comment]
MUI dialogs has zIndex 1400. If we use react-page inside a fullscreen dialog, the plugin selection drawer and bottom drawer would be completely covered by the dialog.

**Comment by zarybnicky** [comment]
Still a problem, I'd rather not have to fork just to change a single zIndex prop.

**Comment by macrozone** [comment]
> Still a problem, I'd rather not have to override the entire toolbar just to change a single zIndex prop.

can you file a pull request?
