### ISSUE TITLE
Clicking '+' icon on background DOESNT add block to background

### ISSUE THREAD

**Issue by zehawki** [react-page/react-page#972]
**Describe the bug**
Clicking '+' icon on background DOESNT add block to background

**To Reproduce**
1. Add a background
2. Click on the + (for adding a cell plugin) on a background -> the side selector panel opens up. 
3. Click to add anything - say text
4. This new cell plugin gets inserted at the bottom of the page, and the page scrolls down

**Expected behavior**
The inserted cell plugin should logically be placed ON the background, thus matching the user expectation

**Additional context**
I have a feeling this is a regression. I dont quite remember this behavior from earlier.

**Comment by estebanpanelli** [comment]
Having the same issue since updating to 2.0.1. Any hints?

**Comment by macrozone** [comment]
wow, indeed a regression. Will fix asap
