### ISSUE TITLE
Minor - hover on the '+' icon shows "not-allowed" icon

### ISSUE THREAD

**Issue by zehawki** [react-page/react-page#973]
**Describe the bug**
When the mouse is hovering on the '+' icon, the browser shows "not-allowed" icon

**Expected behavior**
Should show normal cursor or maybe pointer

**Screenshots**
![image](https://user-images.githubusercontent.com/8095144/115433575-5a746800-a225-11eb-8d36-d24dc3ed80cf.png)

**Additional context**
Prolly due to this piece of code: https://github.com/react-page/react-page/blob/eb15fcb12d26c614e5ebe4ed66a1b948aadcb47b/packages/editor/src/core/components/Cell/InsertNew.tsx#L59

```
      style={{
        pointerEvents: 'all',
        zIndex: isLayoutMode ? 10 : 1,
        overflow: 'hidden',
        width: '50%', // just so that it leaves some room to click on the parent element
        minWidth: 120,
        margin: 'auto',
        cursor: isAllowed ? 'auto' : 'not-allowed',
      }}
```

**Comment by macrozone** [comment]
thx for reporting!

should probably be `cursor: isOver && !isAllowed ? 'not-allowed' : 'auto',`
