### ISSUE TITLE
http://myeditor.cool invitation

### ISSUE THREAD

**Issue by sskyy** [react-page/react-page#974]
Hello, I'm the author of MyeditorCool. [http://myeditor.cool](http://myeditor.cool) is website reads user's file in github/onedrive/etc. through openapi, and allow user to edit it with any editor published to npm and has 'myeditorcool' field in package.json.

By supporting myeditorcool, react-page can soon be used by users to edit their own map file online without installing anything!

I'm inviting react-page to join myeditorcool, be our recommended editor. Only a few works need to be done, the docs are here: https://github.com/MyEditorCool/editors/blob/master/DevelopAnEditor.md. Looking forward to your reply.

**Comment by macrozone** [comment]
hi @sskyy ! How could i say no to someone showing Lorenor Zorro as an example image? ;-)

<img width="436" alt="Bildschirmfoto 2021-04-21 um 14 37 58" src="https://user-images.githubusercontent.com/1972353/115554991-51c87400-a2af-11eb-90c6-e640bc5f1289.png">

However, I don't see any synergy between the two projects. ReactPage is a content editor and not a file editor. But of course feel free to integrate ReactPage into your project as you please!
