### ISSUE TITLE
handle the slash '/' command to open the insert plugin sidebar 

### ISSUE THREAD

**Issue by karthick3018** [react-page/react-page#982]
**Is your feature request related to a problem? Please describe.**
Since all the editor related options like notion , rich editor , slab handles the slash command people tends to go for "/" command  
**Describe the solution you'd like**
We can have the global listener and handle the slash command

**Comment by macrozone** [comment]
nice idea.

Its probably good to make it customizable. E.g. on swiss-german keyboards like mine, there is no dedicated `/`-key

**Comment by karthick3018** [comment]
@macrozone unlike slash we can have a control key and any letter combination ,I would love to work on the sutff if assigned

**Comment by macrozone** [comment]
@karthick3018 sure thing! PRs are highly welcomed!

the slate (rich text) plugin has hotkey support, maybe you can use that as inspiration: https://github.com/react-page/react-page/blob/master/packages/plugins/content/slate/src/components/hotkeyHooks.ts

**Comment by karthick3018** [comment]
sure 🎉

**Comment by macrozone** [comment]
--> this currently leads to the situation that you can no longer type in a "/" char in the slate (rich text) editor

**Comment by karthick3018** [comment]
@macrozone  have you fixed this issue ? I could reproduce the issue in current live version !

**Comment by macrozone** [comment]
its fixed in live, or what do you mean?

we no longer open the insert plugin sidebar when any cell is focused

**Comment by karthick3018** [comment]
Imagine like while being active in the rich editor I need to insert a divider plugin so I can type "/" to get the cell plugins . "we no longer open the insert plugin sidebar when any cell is focused" this one also make sense it just depends on the scenario of our application .

**Comment by macrozone** [comment]
@karthick3018 I also thought about that, so you can now press ESC to unselect any cell, which makes it a bit easier to open the toolbar

**Comment by karthick3018** [comment]
yeah @macrozone  current version looks so cool 🎉🎉
