### ISSUE TITLE
Upgrade to v2.1.4 failed. I can't load previous content built with v0.30.0

### ISSUE THREAD

**Issue by maximo-calero** [react-page/react-page#983]
**Describe the bug**
I just upgraded in my project to version 2.1.4 of @react-page/editor, but I can't load the content I previously created with 0.30.0 version.
I have the following exception in migratePluginDataForCell:
TypeError: Cannot read property 'find' of undefined

**To Reproduce**
1. Upgrade library from 0.30.0 to 2.1.4

**Expected behavior**
I expected to work properly with new version. I don't know if I'm missing something to work with new version. I looked for some information about upgrading but I didn't find anything.

**Screenshots**
![image](https://user-images.githubusercontent.com/35887433/116972209-f937a480-acba-11eb-8394-0fbe271c4829.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser Chrome
 - Version [90.0.4430.93]

**Additional context**

**Comment by macrozone** [comment]
ok, let me check

**Comment by macrozone** [comment]
@maximo-calero there are certain breaking changes between 0.x and 1.x (and also between 1.x and 2.x). Related to you problem is that you have to pass `cellPlugins` as an array instead of the object you had to pass to `plugins`

**Comment by maximo-calero** [comment]
Thank you very much @macrozone , I will read upgrade document.

**Comment by macrozone** [comment]
@maximo-calero if you should encounter any other problem not mentioned there, please let me know and i'll try to help (and update the document accordingly)

**Comment by macrozone** [comment]
@maximo-calero did you manage to upgrade? 

Content will be migrated (on next save), I still recommend to make a backup. If you encounter any problem, feel free to ask and i'll check
