### ISSUE TITLE
Vertical spacer behavior has changed on mobile

### ISSUE THREAD

**Issue by zehawki** [react-page/react-page#986]
**Describe the bug**
Vertical / column spacers, largely used on desktop, are getting converted to rows on a mobile screen, leading to unexpected layout shifts on mobile.

**Expected behavior**
Vertical spacers should be silently dropped on mobile

**Screenshots**
![image](https://user-images.githubusercontent.com/8095144/117725370-aaca5e80-b202-11eb-990a-f57d40c00b23.png)
![image](https://user-images.githubusercontent.com/8095144/117725464-ce8da480-b202-11eb-8be3-62266d8685ca.png)

**Additional context**
I could be wrong, but I distinctly think this is a regression. In the initial days when I started using this package, I was pleasantly surprised to see the expected behavior, which made a lot of sense. However now I'm noticing a changed behavior.

**Comment by PeterKottas** [comment]
> Please note that there might be some conflict between what I'm calling a vertical spacer vs you. Maybe that's leading to a misunderstanding?

I am leaning towards this. The vertical spacer is a plugin that lets you choose the height in pixels. Not more not less. Taking that into consideration, I hope you see the mobile behavior is actually expected. It simply takes up space (heightwise). Your use of this for "horizontal use case" is something it was not designed to do. 

To keep things totally simple, replace your spacer with empty text and I am pretty sure you'll have what you're looking for. There might however be some extra (little) padding. If you want to avoid that create a custom plugin that renders empty div with no padding.

**Comment by PeterKottas** [comment]
No worries. I don't recall this disappearing on mobile TBH. Maybe you had some styles for that at some point? We might have changed some class structure and if your selector was too specific, maybe that changed the behavior for you. Anyways, glad it works now!
