### ISSUE TITLE
Default value of "use parallax effect" on background should be OFF

### ISSUE THREAD

**Issue by zehawki** [react-page/react-page#987]
**Describe the bug**
With the default _use parallax = on_ on background plugin, certain pages which have ~20 backgrounds on them have noticeably poor performance on mobile. The page crawls, and the text shimmers when scrolled. Overall it feels very sluggish.

**Additional context**
I have narrowed this down to the setting of parallax = on. Parallax effect is meaningless for backgrounds without image, ie only color. Hence having this ON by default is of no use and in fact is causing a performance hit.

**Comment by PeterKottas** [comment]
You can change the default when setting up the plugin. https://github.com/react-page/react-page/blob/master/packages/plugins/layout/background/src/types/settings.ts#L21

**Comment by zehawki** [comment]
Is this broken? Setting `defaultIsParallax = false` shows parallax on by default.

**Comment by zehawki** [comment]
After tracing thru, I've narrowed it down to this piece of code https://github.com/react-page/react-page/blob/673abb34a215f8d5291e54304d4050f771bffe00/packages/plugins/layout/background/src/Controls/sub/Image.tsx#L47

Changing this to `isParallax = this.props.defaultIsParallax` seems to fix the issue

**Comment by PeterKottas** [comment]
Looks good to me, could you PR this by any chance?

**Comment by zehawki** [comment]
I can, but here are 2 thoughts :-)

1. I'm not sure this is correct. Maybe I'm missing something, so it would be good if @macrozone reviews
2. He can just throw this tiny change into his next update, without us going thru a full PR overhead?

**Comment by macrozone** [comment]
a pr would be great, happy to merge it (i will quickly review it, but i guess its a one liner, right?

**Comment by PeterKottas** [comment]
No worries, that's it. Simply make that change and it's good to go

**Comment by PeterKottas** [comment]
I or macrozone can merge it then.
